### ISSUE TITLE
Inject external package

### ISSUE THREAD

**Issue by chrisoftech** [Milad-Akarie/injectable#1]
I love your package since simplifies dealing with DI using get it.
My question is, how would i inject and external package like dio and SharedPreference (which is a future to be awaited before returning its instance) ie. getIt.registerLazySingleton(() => await SharedPreferences.getInstance())?

**Comment by Milad-Akarie** [comment]
Hey @chrisoftech, 
I was seriously considering providing some sort of an inline annotation to register external types but then I thought external types are usually independent and don't require a lot of boilerplate code so we might as well register them manually.
and if you need to await for the instance you need to register you're gonna have to make your whole configure function async or maybe relay on the signal you get from GetIt when you set signalsReady to true.

so this's how I'd register my shared prefs

```
@injectableInit
void configure() async {
  $initGetIt(); // make sure you still register the generated deps
// await for the instance outside of the register function
  final prefs = await SharedPreferences.getInstance();
  getIt.registerLazySingleton(() => prefs);
}
```

**Comment by chrisoftech** [comment]
Okay thanks. Will give it a go on my current project.

**Comment by Milad-Akarie** [comment]
Let me know if you encounter any trouble and good luck.
