### ISSUE TITLE
Why this project has flutter as a dependency?

### ISSUE THREAD

**Issue by abner** [Milad-Akarie/injectable#10]
First of all i want to say thanks for this amazing package.

But i just want ask: 

Why both injectable and injectable_generator has `flutter` as a dependency?

I just saw `flutter` is not used at all in both packages code. I think it is not necessary and is preventing to use this amazing package with pure dart code. 

It would be nice to use it in pure dart projects as well.

So i would like to suggest to remove the flutter dependency on both packages.

Thanks in advance!

**Comment by Milad-Akarie** [comment]
@abner I was trying out something and I forgot it there..will be removed in the next build.
Thanks for reporting.

**Comment by Milad-Akarie** [comment]
@abner removed in v0.2.2
