### ISSUE TITLE
prefer relative imports

### ISSUE THREAD

**Issue by mars3142** [Milad-Akarie/injectable#101]
I'm using the **effective dart** lint package and I always get the following warning for your generated code: https://dart-lang.github.io/linter/lints/prefer_relative_imports.html

Would it be possible to change the import generation to use relative imports? That would be awesome.

**Comment by Milad-Akarie** [comment]
hey @mars3142  what version are you on? injectable_generator: 1.0.2 is using relative imports by default

**Comment by mars3142** [comment]
Oh, I was on ^0.4.0. So I close the issue. Thanks for the hint.
