### ISSUE TITLE
Injectable build speed while developing app (build_runner watch + hot reload)

### ISSUE THREAD

**Issue by fedotxxl** [Milad-Akarie/injectable#103]
Hello. Thank you for the great package. The only problem I've got - it slowdowns  buid_runner rebuild even when I change a file without Injectable annotations.

My basic workflow:
1. My services are marked with Injectable. They should be rebuilt on change.
2. My widgets are not marked with Injectable. When I change something `build_runner` makes a significantly slow rebuild and it breaks hot reload feature. What's the point to rebuild classes when I changed widget which is not related to Injectable?

Is it possible to improve the rebuild process and make it only when it's needed?

**Comment by Milad-Akarie** [comment]
> What's the point to rebuild classes when I changed widget which is not related to Injectable
Mainly to check if there are new injectables added. but, ya It's time I focused on optimizing injectable. I'll see what I can do to.
