### ISSUE TITLE
Injectable generator not handling multiple instances of generic types

### ISSUE THREAD

**Issue by dalewking** [Milad-Akarie/injectable#107]
injectable generator is giving errors if you have multiple generic specializations of the same type. Consider this module:

```
@module
abstract class MyModule {
  @singleton
  List<int> get foo => [1, 2, 3];

  @singleton
  List<String> get bar => ["a", "b", "c"];
}
```

The generator fails with this error because it is ignoring the generic types:

```
Injectable Generator ---------------------------------------------------
List [List] env: [] 
is registered more than once under the same environment
------------------------------------------------------------------------ 
```
But get_it itself has no problems with this scenario and this hand written get_it code works fine:

```
  GetIt.I.registerSingleton<List<int>>([1, 2, 3]);
  GetIt.I.registerSingleton<List<String>>(["a", "b", "c"]);
```

**Comment by dalewking** [comment]
I tried some hacking of injectable_generator and the problem is just with the validation logic. If I comment out the guts of `_validateDuplicateDependencies` I get the correct code generated:

```
  gh.singleton<List<int>>(myModule.foo);
  gh.singleton<List<String>>(myModule.bar);
```

**Comment by dalewking** [comment]
Looks like this can be fixed with this:

      var registered = validatedDeps.where((elm) =>
          elm.type.identity == dep.type.identity &&
          elm.type.typeArguments == dep.type.typeArguments &&
          elm.instanceName == dep.instanceName);

But you probably also want to enhance the error message to show the type arguments in the message.

**Comment by dalewking** [comment]
No that then doesn't show an error if you do have duplicates (i.e. 2 List<int>)

**Comment by Milad-Akarie** [comment]
@dalewking sweet! will push the fix soon enough.

**Comment by Milad-Akarie** [comment]
@dalewking I'll just compare the full name as String

**Comment by dalewking** [comment]
Here is the correct fix by changing ImportableType (requires adding dependency on collection library:

  @override
  String toString() => typeArguments.join() == null || typeArguments.isEmpty ? name : "$name<${typeArguments.join(", ")}>";

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportableType &&
          runtimeType == other.runtimeType &&
          identity == other.identity &&
          ListEquality().equals(typeArguments, other.typeArguments);

  @override
  int get hashCode => import.hashCode ^ name.hashCode ^ ListEquality().hash(typeArguments);

**Comment by dalewking** [comment]
Guess that also requires changing the validator to use the this comparison

**Comment by dalewking** [comment]
The above changes to ImportableType toString, == and hashCode along with this change to the validation seems to do what you want:

      var registered = validatedDeps.where((elm) {
        return elm.type == dep.type && elm.instanceName == dep.instanceName;
      });

But I could be missing something
