### ISSUE TITLE
Improvements to generator function

### ISSUE THREAD

**Issue by dalewking** [Milad-Akarie/injectable#108]
For a more functional flow it would be nice if instead of returning void that $initGetIt returned the GetIt instance passed to it.

It would be nice if instead of using the default name of $initGetIt that you could allow specifying the name. So I would propose an additional parameter be added to `InjectableInit`:
- String initializerName = "$initGetIt": This is the name of the generated initializer. It would have a default value of $initGetIt so if you don't specify it you get the current behavior

I was also thinking now that extension methods are a thing in dart it might be nice to have an option to generate it as an extension method. So I would propose an additonal parameter be added to `InjectableInit`:
- String extensionName: This would be the name on the extension block . If this is not specified a normal function is generated like today. If this is specified it triggers the generation as an extension method instead. This can be specified as an empty string in which case you will get an unnamed extension block which would only be usable using a part declaration

So for example this annotation:

```
    @InjectableInit(initializerName: "foo", extensionName: "bar")
```

would generate this

```
extension bar on GetIt {
  GetIt foo({String env}) {
    final gh = GetItHelper(this, environment);
    // ... This part is unchanged
    return this;
  }
}
```

which could be used as:

```
    GetIt getIt = GetIt.I.foo()
```

**Comment by Milad-Akarie** [comment]
@dalewking This is so beautiful!
I don't think the name of the extension matters that much, how about making it more readable?
I'm thinking something like this
`@InjectableInit(initializerName: "foo", asExtension: true)`

**Comment by dalewking** [comment]
It probably doesn't matter much. In general it's only significance is for use in show and hide clauses on imports and in this case it is the only thing importable in the file so as long as you picked a reasonable name,  e.g. `InjectableExtension` that would be fine.

I wonder though if there is an issue importing 2 different extensions with the same name. Not currently at the computer to try it,  but as long as there is no issue with that I am good with the change
