### ISSUE TITLE
Incorrect case on imports leads to as parameter being ignored

### ISSUE THREAD

**Issue by dalewking** [Milad-Akarie/injectable#109]
So not sure if this should really be a bug but it took me a couple hours to figure it out. I was trying to use the as parameter of Injectable and it steadfastly just ignored it.

So here is a reproducible test case

So with this in a file called Service.dart
```
abstract class Service {}
```

And in a file called ServiceImpl.dart:
```
import 'service.dart';
import 'package:injectable/injectable.dart';

@Injectable(as: Service)
class ServiceImpl implements Service {}
```

When you run injectable you get no errors but you only get this:

    gh.factory<ServiceImpl>(() => ServiceImpl());

The actual issue was surprising. The problem was this import:
```
import 'service.dart';
```

The case is wrong. That should be:

```
import 'Service.dart';
```

And when you change that it works as expected:

```
  gh.factory<Service>(() => ServiceImpl());
```

So not sure having the case wrong on an import is valid in dart, but Injectable should at least give an error that it ignored the as parameter

**Comment by Milad-Akarie** [comment]
@dalewking How do I reproduce this?
everything looks fine on my end. 
![img](https://i.ibb.co/6gYK32x/Screen-Shot-2020-08-01-at-11-41-09-AM.png)

**Comment by dalewking** [comment]
The key thing for me was that in Service_impl.dart that the import of Service.dart had the capitalization different than the actual file name, i.e.:

    import 'service.dart';

There is a chance that this could be OS dependent. I was on Mac which has a file system that is case insensitive,  but case preserving. Windows is the same, while Linux is case sensitive and case preserving. See https://en.m.wikipedia.org/wiki/Case_preservation. Which may mean that it would just fail on Linux.

**Comment by dalewking** [comment]
Did some more playing around with it and if you have that case wrong it definitely does as I said. But with it that way you will get errors from Dart as that is not valid in Dart. I didn't see errors from Dart, but I think that was cause I was in the middle of some major refactoring that was causing the Dart analyzer in Android Studio to crash.

So in the normal case this should not be an issue as you would see errors from Dart but injectable_generator should not generate the wrong code.

**Comment by Milad-Akarie** [comment]
@dalewking alright then, closing this for now.
