### ISSUE TITLE
[Enhancement] Consider using a template engine for code generation

### ISSUE THREAD

**Issue by dalewking** [Milad-Akarie/injectable#111]
Currently your generators are hand written code that is difficult to see the big picture in and if some one wanted to customize the generation they would need to modify code either by asking you for changes or copying the code into their project and making the changes.

The openApiGenerator project takes a different approach that you could benefit from as well. All generation is done using mustache template files. They set up a context of all the things necessary for the generation then pass that to the template engine. The templates are just text files that can be more easily edited than code and they contain some of the logic.

The nice part of this is that someone wants to  customize the generation they can copy the templates to their project edit them and tell the tool to use their templates instead of the standard ones.

There are a couple different mustache libraries for dart and one for liquid which is a bit more powerful than mustache.

**Comment by Milad-Akarie** [comment]
ya that sounds good, not sure how I can adapt my code to use these template engines thu, I recently thought about giving  [Code Builder](https://pub.dev/packages/code_builder) a try,  what do you think about it?

**Comment by dalewking** [comment]
Would certainly be an improvement over what you have. The advantage of the templates is that you could allow someone to supply their own set of template files to tweak the output to their liking.
