### ISSUE TITLE
Style tweak

### ISSUE THREAD

**Issue by dalewking** [Milad-Akarie/injectable#113]
Have you considered instead of creating the gh variable in the generated code and starting each line with gh., using the [cascade notation](https://dart.dev/guides/language/language-tour#cascade-notation-) (i.e. the ..) to make the generated code more readable?

**Comment by Milad-Akarie** [comment]
@dalewking ya I used the cascade notion with the first couple releases but when I started adding things like env checks (old way) and the preResolve thingy when you await a feature and register it as a resolved value things started to get a little complected so I just got red of the cascade notation all together.
