### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by magicpro97** [Milad-Akarie/injectable#114]
Hi, I'm new with injectable. I try to apply this for my project but I got a problem.

>[SEVERE] injectable_generator:injectable_builder on lib/injector_container.dart:
Error running Instance of 'InjectableGenerator'
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
[WARNING] injectable_generator:injectable_config_builder on lib/injector_container.dart:
Missing dependencies in mg/injector_container.dart
[EncryptedStorage] depends on unregistered type [Box] from package:hive/hive.dart
[UserServiceImpl] depends on unregistered type [Dio] from package:dio/dio.dart
Did you forget to annotate the above classe(s) or their implementation with @injectable?

This is my code.

```
final getIt = GetIt.instance;

final logger = Logger();

class Name {
  static const baseUrl = "BaseUrl";

  static const cachedBox = "CachedBox";
}

@module
abstract class DioModule {
  @Named(Name.baseUrl)
  String get baseUrl => Api.BASE_URL;

  @lazySingleton
  Dio dio(@Named(Name.baseUrl) String url) {
    final dio = Dio(
      BaseOptions(
        baseUrl: url,
      ),
    );

    dio.interceptors.addAll([
      LogInterceptor(
        request: true,
        responseBody: true,
        responseHeader: true,
        error: true,
      ),
      ErrorHandlerInterceptor(dio),
    ]);

    return dio;
  }
}

@module
abstract class HiveModule {
  @preResolve
  Future<void> get initHive => Hive.initFlutter();

  @Named(Name.cachedBox)
  Future<Box<String>> get prefs => Hive.openBox<String>('cached');
}

@injectableInit
Future<void> setup() => $initGetIt(getIt);
```

```
@lazySingleton
class EncryptedStorage {
  final Box<String> _cachedBox;

  EncryptedStorage(@Named('CachedBox') this._cachedBox);

  Future<void> saveToken(String token) => _cachedBox.put(_Keys.TOKEN, token);

  String getToken() => _cachedBox.get(_Keys.TOKEN);
}

class _Keys {
  static const TOKEN = 'token';
}
```

```
abstract class UserService {
  Future<Result<LoginResponse>> login({String username, String password});

  Future<void> signOut();

  Future<User> fetchUser(String id);
}

@LazySingleton(as: UserService)
class UserServiceImpl extends UserService {
  final Dio _dio;

  UserServiceImpl(this._dio);

  @override
  Future<User> fetchUser(String id) async {
    // TODO: implement fetchUser
    throw UnimplementedError();
  }

  @override
  Future<Result<LoginResponse>> login({
    String username,
    String password,
  }) =>
      _dio
          .get('')
          .then((value) => BaseResponse.fromJson(
                value.data,
                (json) => LoginResponse.fromJson(json),
              ).data)
          .catchError((error) => Result.error(error));

  @override
  Future<void> signOut() {
    // TODO: implement signOut
    throw UnimplementedError();
  }
}
```

Please tell me what I'm wrong. And any solution for this? Thanks.

**Comment by Milad-Akarie** [comment]
@magicpro97 everything looks fine. actually. I have no idea what's going on here.

**Comment by Milad-Akarie** [comment]
Actually after a closer look, this line is what causing the error, You're trying to register void!
replace void with whatever Hive.initFlutter is returning; 
```dart
  @preResolve
  Future<void> get initHive => Hive.initFlutter();
```

**Comment by chrisoftech** [comment]
Am currently experiencing this issue and noticed that `injectable` ultilizes individual class imports while i use collective imports exported from a separate class in my implementations.

example:
I use collective export to access a feature's files
`export 'auth_usecases/get_auth_status.dart';
export 'auth_usecases/initiate_hand_shake.dart';
export 'auth_usecases/sign_out.dart';
`
which results to `import 'package:project_name/domain/usecases/usecases.dart';`

while Injectable accesses injectable-annotated class with individual file imports 
which results to `import 'package:project_name/domain/usecases/auth_usecases/get_auth_status.dart';`

And this means they are not the same with `Injectable` since access imports are different
Am currently not sure how to resolve this since i prefer using `collective imports`

Any assistance is appreciated

**Comment by tdnghia98** [comment]
> Am currently experiencing this issue and noticed that `injectable` ultilizes individual class imports while i use collective imports exported from a separate class in my implementations.
> 
> example:
> I use collective export to access a feature's files
> `export 'auth_usecases/get_auth_status.dart';`
> `export 'auth_usecases/initiate_hand_shake.dart';`
> `export 'auth_usecases/sign_out.dart';`
> 
> which results to `import 'package:project_name/domain/usecases/usecases.dart';`
> 
> while Injectable accesses injectable-annotated class with individual file imports
> which results to `import 'package:project_name/domain/usecases/auth_usecases/get_auth_status.dart';`
> 
> And this means they are not the same with `Injectable` since access imports are different
> Am currently not sure how to resolve this since i prefer using `collective imports`
> 
> Any assistance is appreciated

I also have the same issue, have you found out how to resolve it?

**Comment by casvanluijtelaar** [comment]
> Am currently experiencing this issue and noticed that `injectable` ultilizes individual class imports while i use collective imports exported from a separate class in my implementations.
> 
> example: I use collective export to access a feature's files `export 'auth_usecases/get_auth_status.dart';` `export 'auth_usecases/initiate_hand_shake.dart';` `export 'auth_usecases/sign_out.dart';`
> 
> which results to `import 'package:project_name/domain/usecases/usecases.dart';`
> 
> while Injectable accesses injectable-annotated class with individual file imports which results to `import 'package:project_name/domain/usecases/auth_usecases/get_auth_status.dart';`
> 
> And this means they are not the same with `Injectable` since access imports are different Am currently not sure how to resolve this since i prefer using `collective imports`
> 
> Any assistance is appreciated

@Milad-Akarie  it seems to indeed be an issue with import locations, I use barrel files and have similar issues

**Comment by ariefwijaya** [comment]
Same Here, anyone please vote for this problem because many of us are facing this problem

**Comment by tomwyr** [comment]
I experience the exact same issue.
The "missing" type can be added to `ignoreUnregisteredTypes` but it then makes you lose the benefit of build time safety.

**Comment by ariefwijaya** [comment]
> I experience the exact same issue. The "missing" type can be added to `ignoreUnregisteredTypes` but it then makes you lose the benefit of build time safety.

I don't think `ignoreUnregisteredTypes` can solve the issue, the thing is, we need it to be registered and Injectable couldn't generate it especially for collective export

**Comment by PatrickWulfe** [comment]
Also facing the 'export' issue.  Just removing exports/barrel files of abstract classes and importing them specifically resolved it for me, though not exactly a solution.

**Comment by ariefwijaya** [comment]
> Also facing the 'export' issue. Just removing exports/barrel files of abstract classes and importing them specifically resolved it for me, though not exactly a solution.

Thanks, this solved the issue, the problem happened because the limitation of injectable plugin.

**Comment by tomwyr** [comment]
@Milad-Akarie Have you tried investigating this issue but found some obstacles that would make fixing the warnings too complex or is it still something to be explored?

**Comment by fajarainul** [comment]
I am facing the same issues, removing the barrel files resolved the issues.

**Comment by jonathanfilbert** [comment]
> Am currently experiencing this issue and noticed that `injectable` ultilizes individual class imports while i use collective imports exported from a separate class in my implementations.
> 
> example: I use collective export to access a feature's files `export 'auth_usecases/get_auth_status.dart';` `export 'auth_usecases/initiate_hand_shake.dart';` `export 'auth_usecases/sign_out.dart';`
> 
> which results to `import 'package:project_name/domain/usecases/usecases.dart';`
> 
> while Injectable accesses injectable-annotated class with individual file imports which results to `import 'package:project_name/domain/usecases/auth_usecases/get_auth_status.dart';`
> 
> And this means they are not the same with `Injectable` since access imports are different Am currently not sure how to resolve this since i prefer using `collective imports`
> 
> Any assistance is appreciated

Can confirm this solution has fixed my problem, thanks!
