### ISSUE TITLE
Ignore unregistered type message

### ISSUE THREAD

**Issue by rubgithub** [Milad-Akarie/injectable#125]
Hi there, I'm using [flutter_data](https://github.com/flutterdata/flutter_data) that register object factories automatically inside get_it.

`i.registerSingletonWithDependencies<Repository<Todo>>`

Is there a way to ignore this injectable warning?

```
class MyBloc extends Bloc<MyBlocEvent, MyBlocState> {
  MyBloc(this._repo) : super(MyBlocState.initial());
final Repository<Todo> _repo;

```
unregistered type [Repository<Todo>] from package:flutter_data/flutter_data.dart

**Comment by Milad-Akarie** [comment]
final added in injectable 1.2.2
`  ignoreUnregisteredTypes: [ServiceA],`
