### ISSUE TITLE
config file is generated in a slightly different order depending on the platform used.

### ISSUE THREAD

**Issue by britannio** [Milad-Akarie/injectable#129]
![image](https://user-images.githubusercontent.com/33752528/91472640-ac7c0e00-e88f-11ea-9f21-f36ae67c4191.png)

Occurs when the base class has the same name. The screenshot is a git diff when running code generation on Windows after making a commit on MacOS.

It's similar to https://github.com/Milad-Akarie/injectable/issues/42.

**Comment by Milad-Akarie** [comment]
@britannio  is this an issue in the current release?
