### ISSUE TITLE
Injectable Generator: Failed to snapshot build script 

### ISSUE THREAD

**Issue by Holofox** [Milad-Akarie/injectable#13]
When I run the command in the terminal:
```dart
flutter packages pub run build_runner watch --delete-conflicting-outputs
```
I received the following error:
> [SEVERE] ../../Flutter/.pub-cache/hosted/pub.dartlang.org/injectable_generator-0.2.2/lib/dependency_resolver.dart:40:52: Error: The getter 'declaration' isn't defined for the class 'PropertyAccessorElement'. - 'PropertyAccessorElement' is from 'package:analyzer/dart/element/element.dart' ('../../Flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.0/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'declaration'.        final arrowReg = RegExp('${accessorElement.declaration}\\s+=>([^;]*)');                                                   ^^^^^^^^^^^
pub finished with exit code 78

But I haven’t even written a line of code.

Injectable: v0.2.2
Get ID: v3.1.0 or v4.0.0-release-candidate

**Comment by Milad-Akarie** [comment]
@Holofox fixed in v0.2.3
Thanks for reporting
