### ISSUE TITLE
Missing dependencies warning when an abstract class extends on another abstract

### ISSUE THREAD

**Issue by gloryluu** [Milad-Akarie/injectable#132]
```
abstract class A {} 

abstract class B extends A {}

@LazySingleton(as: B)
class ApiClient extends B { }

class UserRepository {B client}
```

When I run the generator, I got the warning like

```
Missing dependencies in microsat/services/injection/injection.dart
[UserRepository] depends on unregistered type [B]
```

How can I get rid of this warning ?

**Comment by amebrahimi** [comment]
This is after the latest update, I'm seeing this too but it doesn't break my code and it runs successfully.

**Comment by nhwilly** [comment]
Mine's broken.

**Comment by windrunner414** [comment]
+1 meet the same issue.It broke the usage of retrofit

**Comment by adamsmaka** [comment]
as mentioned in #125 use `ignoreUnregisteredTypes: [B]` in your `InjectableInit` configuration to mute the warnings
