### ISSUE TITLE
Restricted Generic Type (T Extends SomeClass) Problem

### ISSUE THREAD

**Issue by Peng-Qian** [Milad-Akarie/injectable#134]
#### Problem
when generating the restricted generic type as follow, the dynamic will filled in and result in exceptions
#### Annotation
```dart
@injectable
class Repository<T extends Entity> {
  ...
}
```
#### Generated code
```dart
  gh.factory<Repository<dynamic>>(() => Repository<dynamic>());
```
which will not compile...

**Comment by Milad-Akarie** [comment]
@Peng-Qian I see. This should normally register without a type? 
how would you manually register it?
