### ISSUE TITLE
Unable to import files from test folder

### ISSUE THREAD

**Issue by ashank96** [Milad-Akarie/injectable#137]
<img width="766" alt="Screenshot 2020-09-22 at 7 41 22 PM" src="https://user-images.githubusercontent.com/22197948/93893976-db10cb80-fd0b-11ea-83f2-88f1ba836eb4.png">

The above is corresponding to my @InjectableInit
<img width="640" alt="Screenshot 2020-09-22 at 7 44 08 PM" src="https://user-images.githubusercontent.com/22197948/93894111-fda2e480-fd0b-11ea-8528-3c8b7185d6d1.png">

**Comment by Milad-Akarie** [comment]
Hey, could you import it manually?
How does the import statement look like?

**Comment by ashank96** [comment]
No, even if I import manually, it shows the error. @Milad-Akarie 
This is my lib structure
<img width="415" alt="Screenshot 2020-09-22 at 8 08 58 PM" src="https://user-images.githubusercontent.com/22197948/93897238-76f00680-fd0f-11ea-99f8-267488d13965.png">

This is my test structure
<img width="389" alt="Screenshot 2020-09-22 at 8 09 28 PM" src="https://user-images.githubusercontent.com/22197948/93897291-8707e600-fd0f-11ea-8340-6f724c4f1a2c.png">

**Comment by Milad-Akarie** [comment]
Yes, because you can't import files outside of the lib folder to the lib folder. It only works the other way around.

**Comment by ashank96** [comment]
Yeah that make sense, but what if I dont want my mock classes inside lib folder, as they are not a part of production code?
Any suggestions on that part ?

**Comment by ashank96** [comment]
Also this seems contradicting with the fact that we have a `generateForDir:` param in `InjectableInit` that can accept `test` dir as a string. @Milad-Akarie

**Comment by ganeshrvel** [comment]
Facing the same issues. How did you get it working?

**Comment by ashank96** [comment]
I learnt that, test code should be separate from that of production thats why, may be this package doesnt support building for test folder.
So I am setting up a manual getIt registration framework for test folders. Not using injectable for mock classes now.

**Comment by ganeshrvel** [comment]
Actually I misread the title. I had an issue importing files from lib to test folder.

**Comment by ValeriusGC** [comment]
Hi! I got just like the same problem (with some other flavor):
Subj has made `config.file` correct but import is invalid:
![Screenshot from 2021-08-12 07-26-38](https://user-images.githubusercontent.com/3320861/129129520-04e8da13-3010-4f9d-bee0-71c4629e9813.png)
![Screenshot from 2021-08-12 07-29-29](https://user-images.githubusercontent.com/3320861/129129524-dc7538a4-cd5c-4f00-ab71-a279b1352639.png)
here is my function:
```
@InjectableInit(
  generateForDir: ['test', 'lib'],
  initializerName: r'$initGetIt', // default
  preferRelativeImports: true, // default
  asExtension: false, // default
)
void configureDependencies(String environment) =>
    $initGetIt(getIt, environment: environment);

```

**Comment by ValeriusGC** [comment]
BTW, with   `preferRelativeImports: false` it doesn't work too.

**Comment by ikicodedev** [comment]
I want to have a separate configuration for the test/ module when generating the .config.dart file import as you have indicated @ValeriusGC. Changing it manually would be invalid as it would break the CI/CD.

Any workaround solution?
