### ISSUE TITLE
Dependency Injection in microlibrary packages

### ISSUE THREAD

**Issue by geovin89** [Milad-Akarie/injectable#139]
More of a knowledge question rather than an issue. My project is using a micro-library architecture where each layer is separated into different packages as shown here  https://dart.dev/guides/libraries/create-library-packages. I would like to use injectable for dependency injection in this project but couldn't find a way to do it reading about it in the injectable library. 

I would greatly appreciate it for any help that you could provide regarding this

**Comment by GoncaloPT** [comment]
I'm developing the implementation of such a feature. I'll push this as a PR in the next week

**Comment by GoncaloPT** [comment]
I've finished a 0.1 version of it.
you can see it in the following fork: https://github.com/GoncaloPT/injectable/blob/master/README.md#support-for-micro-packages
I'll talk to injectable owners to see their interest in pushing this as a new feature...

**Comment by rafampessoa** [comment]
Very interesting on it

**Comment by fryette** [comment]
Any news on it?
@geovin89

**Comment by jhancock4d** [comment]
Ditto. I'd love to see this so that we can inject without manually having to define them in a module.
