### ISSUE TITLE
When class with @injectable is located in the bin direcotry injection.iconfig.dart import the file from asset insted of package

### ISSUE THREAD

**Issue by guyluz11** [Milad-Akarie/injectable#14]
I am using pure dart and my main file is in `bin` instead of `lib`, my class is also located in bin.

When class with `@injectable` is located in the `bin` directory of the project `injection.iconfig.dart` try to import the file from `asset` instead of `package`.

Moving the file to the `lib` directory fix the issue.

Do we need to fix it or moving all the classes to the lib in pure dart is the correct way to work?

**Comment by Milad-Akarie** [comment]
@guyluz11 hmmm honestly I haven't got the chance to play with pure dart yet. do you have like a playground app or something I can play around with?

**Comment by guyluz11** [comment]
Not relay, do you want me to send new pure dart project ?

**Comment by Milad-Akarie** [comment]
@guyluz11 That would be great. Thanks.

**Comment by guyluz11** [comment]
https://github.com/guyluz11/Pure-dart-program

**Comment by Milad-Akarie** [comment]
@guyluz11 
Finally fixed in 
injectable: 0.4.0
injectable_generator: 0.4.0
Thanks for your effort and patience lol
