### ISSUE TITLE
Using environments - hope this helps someone else.

### ISSUE THREAD

**Issue by nhwilly** [Milad-Akarie/injectable#142]
When I upgraded to the latest package, I missed the detail about environments.

If you have some of them set in your injections like this:
```
@LazySingleton(as: IPreviousUserLocalDataSource, env: [Environment.dev])
```

then you must have a configure line like this:
```
void configureDependencies() => $initGetIt(getIt, environment: Env.dev);
```

If you don't it tries to create multiple injectables with an `as` clause followed by the package name (as far as I can figure out).  Then it tells you when you run `build runner` that you don't have anything registered.

It might have been something I did, so no real reason to think there's a bug.  It's just the error message sent me down the rabbit hole.

Threw me for a loop.  All good now.

HTH

**Comment by Milad-Akarie** [comment]
Thanks
