### ISSUE TITLE
Generated code not support null safety

### ISSUE THREAD

**Issue by Abdktefane** [Milad-Akarie/injectable#147]
```dart
final getIt = GetIt.I;

@InjectableInit(
  initializerName: r'$initGetIt', // default
  preferRelativeImports: true, // default
  asExtension: false, // default
)
Future<GetIt> initAppDependencies({String? environment}) async =>
    await $initGetIt(getIt);
```
the generated code 
```dart
Future<GetIt> $initGetIt(
  GetIt get, {
  String environment, // should be String? environment
  EnvironmentFilter environmentFilter, // EnvironmentFilter? environmentFilter
}) async {
.........
}
```

**Comment by Overman775** [comment]
Please add null safety prerelease version like in other packages 👍

**Comment by Noteofman** [comment]
Any movement here?

**Comment by heman4t** [comment]
My current project is using null safety. Although not a big deal in just adding 2 "?" everytime I run build runner. i.e.

```dart
Future<GetIt> $initGetIt(
  GetIt get, {
  String? environment, // should be String? environment
  EnvironmentFilter? environmentFilter, // EnvironmentFilter? environmentFilter
}) async {
...
```

and everything runs smoothly.

@Milad-Akarie can't we just add these 2 "?" in nullsafety version?. Because I have tested it on both android and web. And everything runs smoothly.

**Comment by Milad-Akarie** [comment]
@heman4t I've already started refactoring the code to support null safety, this might take some time though.

**Comment by essarn** [comment]
@Milad-Akarie is there an eta on when this will be done?

**Comment by Milad-Akarie** [comment]
@heman4t @essarn the generated code can now include null safety suffixes in version `1.1.0`, 
```dart
@InjectableInit(
  usesNullSafety: true,
)
```
this will only add (?) suffix to (environment & environmentFilter) 
the official null-sefety version will properly be uploaded sometime tomorrow. 
(please confirm)
Thanks for your patience

**Comment by heman4t** [comment]
> @heman4t @essarn the generated code can now include null safety suffixes in version `1.1.0`,
> 
> ```dart
> @InjectableInit(
>   usesNullSafety: true,
> )
> ```
> 
> this will only add (?) suffix to (environment & environmentFilter)
> the official null-sefety version will properly be uploaded sometime tomorrow.
> (please confirm)
> Thanks for your patience

That's cool. Working perfectly.
