### ISSUE TITLE
Object/factory with with name __environments__ and type Set<String> is already registered inside GetIt.

### ISSUE THREAD

**Issue by Pawelo93** [Milad-Akarie/injectable#148]
Hello

Im using two configuration of getIt, one in main project and one in other module. When both configurations meet, there is error:
Object/factory with with name __environments__ and type Set<String> is already registered inside GetIt.

```
  configureModuleInjection(moduleGetIt, Environment.dev);
  configureMainInjection(mainGetIt, Environment.dev);
```
im trying to join two separate DI, in mainGetIt i need one class from module with all it dependencies

I think it was working before on older version.

**Comment by Pawelo93** [comment]
I was missing
GetIt.asNewInstance()

**Comment by giovanigm** [comment]
Hey @Pawelo93, I'm having the same issue trying to accomplish the same thing. Could you please explain better how did you manage to make it work?
