### ISSUE TITLE
How to use accross multiple chained packages? (Object/factory with with name __environments__ and  type Set<String> is already registered inside GetIt)

### ISSUE THREAD

**Issue by Gintasz** [Milad-Akarie/injectable#153]
I have a root flutter package and business logic package, placed in a local `packages/packagename` directory. I need dependency injections in both of these packages. I also need a shared getIt instance so that I can use business logic dependencies inside a root flutter package.
So currently I have `service_injections.dart` file inside root package:
```
final getIt = GetIt.instance;
@InjectableInit(
  initializerName: r'$initGetIt',
  preferRelativeImports: true,
  asExtension: false,
)
// ignore: await_only_futures
Future configureDependencies() async => await $initGetIt(getIt);
```

and also inside business logic package at `packages/packagename/service_injections.dart`:
```
final getIt = GetIt.instance;
@InjectableInit(
  initializerName: r'$system_initGetIt',
  preferRelativeImports: true,
  asExtension: false,
)
// ignore: await_only_futures
Future configureSystemDependencies() async => await $system_initGetIt(getIt);
```

Then I do in main.dart:
```
  await configureSystemDependencies();
  await configureDependencies();
```

But at run time I get this error on line `final gh = GetItHelper(this, environment, environmentFilter);` in one of the generated config files:
```
Exception has occurred.
ArgumentError (Invalid argument(s): Object/factory with with name __environments__ and  type Set<String> is already registered inside GetIt. )
```

**Comment by Milad-Akarie** [comment]
@Gintasz  are you sure you're using the latest injectable version?

**Comment by Gintasz** [comment]
@Milad-Akarie  yes, 1.0.5

**Comment by Gintasz** [comment]
I did `GetIt.instance.allowReassignment = true;` before initializing both and it looks like it's not crashing anymore

**Comment by tungtd95** [comment]
`GetIt.instance.allowReassignment = true;` is just a workaround for this issue. this relate to a bug I've fix in this PR, please take a look [https://github.com/Milad-Akarie/injectable/pull/163](https://github.com/Milad-Akarie/injectable/pull/163)
@Milad-Akarie

**Comment by pro100svitlo** [comment]
> GetIt.instance.allowReassignment = true;

Looks like a dirty hook. It might leak to many problems later...

It would be nice to have some other solution for supporting multi-modal projects
