### ISSUE TITLE
Factory not registered? It is!

### ISSUE THREAD

**Issue by migalv** [Milad-Akarie/injectable#155]
I'm having an issue while using the Injectable package for Flutter: https://pub.dev/packages/injectable

I'm getting an error telling me that I don't have a factory registered, but I'm trying to get it

This is the class I'm trying to get but as you can see it's annotated with *@injectable*

> auth_bloc.dart

    import 'package:freezed_annotation/freezed_annotation.dart';

    @injectable
    class AuthBloc extends Bloc<AuthEvent, AuthState> {
    
    }

Also in the *injection.config.dart* you can clearly see that the AuthBloc has it's factory defined

```
Future<GetIt> $initGetIt(
  GetIt get, {
  String environment,
  EnvironmentFilter environmentFilter,
}) async {
  final gh = GetItHelper(get, environment, environmentFilter);

  ...

  gh.factory<AuthBloc>(() => AuthBloc(get<IAuthRepository>()));

  ...

  return get;
}
```

This is my main.dart

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  configureInjection(Environment.dev);
  runApp(MyApp());
}
```

Here is where I'm trying to getIt 

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider<AuthBloc>(
          create: (context) {
            return getIt<AuthBloc>() // <============ HERE
              ..add(
                const AuthEvent.authCheckRequested(), 
              );
          },
        ),
      ],
      child: MaterialApp(
         ...
      ),
    );
  }
}
```

This is the injection.dart file
```
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:sales_app/injection.config.dart';

final GetIt getIt = GetIt.instance;

@injectableInit
void configureInjection(String env) {
  $initGetIt(getIt, environment: env);
}
```

This is the error message I'm getting 
```
Object/factory with  type AuthBloc is not registered inside GetIt. 
(Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
Did you forget to register it?)
'package:get_it/get_it_impl.dart':
Failed assertion: line 298 pos 9: 'instanceFactory != null'
```

These are my pubspeck.yaml dependencies
```
...
dependencies:
  injectable: ^1.0.5
...
dev_dependencies:
  injectable_generator: ^1.0.6
...
```

**Comment by samtuga1** [comment]
> I'm having an issue while using the Injectable package for Flutter: https://pub.dev/packages/injectable
> 
> I'm getting an error telling me that I don't have a factory registered, but I'm trying to get it
> 
> This is the class I'm trying to get but as you can see it's annotated with _@Injectable_
> 
> > auth_bloc.dart
> 
> ```
> import 'package:freezed_annotation/freezed_annotation.dart';
> 
> @injectable
> class AuthBloc extends Bloc<AuthEvent, AuthState> {
> 
> }
> ```
> 
> Also in the _injection.config.dart_ you can clearly see that the AuthBloc has it's factory defined
> 
> ```
> Future<GetIt> $initGetIt(
>   GetIt get, {
>   String environment,
>   EnvironmentFilter environmentFilter,
> }) async {
>   final gh = GetItHelper(get, environment, environmentFilter);
> 
>   ...
> 
>   gh.factory<AuthBloc>(() => AuthBloc(get<IAuthRepository>()));
> 
>   ...
> 
>   return get;
> }
> ```
> 
> This is my main.dart
> 
> ```
> Future<void> main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   await Firebase.initializeApp();
>   configureInjection(Environment.dev);
>   runApp(MyApp());
> }
> ```
> 
> Here is where I'm trying to getIt
> 
> ```
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MultiBlocProvider(
>       providers: [
>         BlocProvider<AuthBloc>(
>           create: (context) {
>             return getIt<AuthBloc>() // <============ HERE
>               ..add(
>                 const AuthEvent.authCheckRequested(), 
>               );
>           },
>         ),
>       ],
>       child: MaterialApp(
>          ...
>       ),
>     );
>   }
> }
> ```
> 
> This is the injection.dart file
> 
> ```
> import 'package:get_it/get_it.dart';
> import 'package:injectable/injectable.dart';
> import 'package:sales_app/injection.config.dart';
> 
> final GetIt getIt = GetIt.instance;
> 
> @injectableInit
> void configureInjection(String env) {
>   $initGetIt(getIt, environment: env);
> }
> ```
> 
> This is the error message I'm getting
> 
> ```
> Object/factory with  type AuthBloc is not registered inside GetIt. 
> (Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
> Did you forget to register it?)
> 'package:get_it/get_it_impl.dart':
> Failed assertion: line 298 pos 9: 'instanceFactory != null'
> ```
> 
> These are my pubspeck.yaml dependencies
> 
> ```
> ...
> dependencies:
>   injectable: ^1.0.5
> ...
> dev_dependencies:
>   injectable_generator: ^1.0.6
> ...
> ```

Please were you able to find the issue? I am facing the same challenge?

**Comment by JustineUgo** [comment]
Just incase you need more information on how @migalv solved this issue, see [here](https://stackoverflow.com/questions/65145482/flutter-injectable-factory-not-registered-error)

**Comment by migalv** [comment]
Thank you @JustineUgo for adding the link. I forgot I opened this issue
