### ISSUE TITLE
Query: Best practice for injecting named types

### ISSUE THREAD

**Issue by mpowloka** [Milad-Akarie/injectable#156]
Hello!

I see there may be one missing point in the documentation. I don't see any explanation or any obvious way to inject differently named services to one client, regarding of the needs. Let me explain with an example. Here is how Injecting named types is explained according to documentation:

```
@named
@Injectable(as: Service)
 class ServiceImpl1 implements Service {}

@injectable
class MyRepo {
   final Service service;
    MyRepo(@Named.from(ServiceImpl1) this.service)
}
```

I have a similar case, but my abstract Service is a Strategy design pattern implementation. Because of that, in some parts of my application, I need an instance of MyRepo with ServiceImpl1 and in the other an instance of MyRepo with ServiceImpl2 injected.

The only way I imagine it right now is something like... this? I didn't manage to make it work yet:

```
@named
@Injectable(as: ServiceImpl1)
 class ServiceImpl1 implements Service {}

@named
@Injectable(as: ServiceImpl2)
 class ServiceImpl2 implements Service {}

@injectable
class MyRepo {
   final Service service;

    @factoryMethod
    MyRepo.impl1(@Named.from(ServiceImpl1) this.service)

    @factoryMethod
    MyRepo.impl2(@Named.from(ServiceImpl2) this.service)
}

final repoInstance1 = getIt<MyRepo>('impl1');
final repoInstance2 = getIt<MyRepo>('impl2');
```

As I said, I didn't really make it work yet. We could include instruction on how to achieve that :)

**Comment by michaelgobbers** [comment]
I'm currently trying a similar pattern. Any luck yet getting this to work?

**Comment by egonm12** [comment]
This works:
```
final repoInstance1 = getIt.get<MyRepo>(instanceName: 'impl1');
final repoInstance2 = getIt.get<MyRepo>(instanceName: 'impl2');
```
