### ISSUE TITLE
support for version 4.0.0 of get_it

### ISSUE THREAD

**Issue by easazade** [Milad-Akarie/injectable#16]
the new version 4 of get_it adds new features like creating factories that can accept parameters when creating a new instance with get_it

ecample:

```dart
    //adding factory that accepts parameters
    getIt.registerFactoryParam<MyClass ,String,void>( (s,i) => MyClass( param1:s , param2: i);

    //creating new instance
    var instance = getIt<MyClass>(param1: 'abc', param2: 3);
```

**Comment by Milad-Akarie** [comment]
Hey @easazade It's a work in progress.

**Comment by Milad-Akarie** [comment]
@easazade  GetIt 4.0.0 support was added in injectable 0.3.0 
Check it out!
https://github.com/Milad-Akarie/injectable#passing-parameters-to-factories
