### ISSUE TITLE
Dispose option not found

### ISSUE THREAD

**Issue by Rubywai** [Milad-Akarie/injectable#160]
How to dispose objects which are no longer needed?

**Comment by rmargolinross** [comment]
Along the lines of this, getIt allows registration of lazy singletons with a Disposable function. It would be nice to be able to tag those functions with an annotation to pass that along.

**Comment by Milad-Akarie** [comment]
Disposing of singletons was added to version 1.1.2 
https://pub.dev/packages/injectable#disposing-of-singletons
