### ISSUE TITLE
Could some of you watch the get_it_repo too?

### ISSUE THREAD

**Issue by escamoteur** [Milad-Akarie/injectable#166]
Hi.

I find it amazing what you do with injectable although I still prefer doing my registration manually :-)

As injectable gets more popular I ge more and more issues on the get_it repo from injectable users where I often don't know how to help.
could some of you also watch my repo and scan if new issues are injectable realated?
That would be a great help

Cheers
Thomas

**Comment by Milad-Akarie** [comment]
Hey @escamoteur 
I thank you for your great package. I'll make sure I hit the watch button.

**Comment by escamoteur** [comment]
thanks a lot
