### ISSUE TITLE
not generate Registering singletons in my injection.config.dart

### ISSUE THREAD

**Issue by jun-hak** [Milad-Akarie/injectable#167]
Hi!!

I have some question to use injectable plugin.

my pubspec.yaml

dependencies:
  get_it: ^5.0.3
  injectable: ^1.0.7

dev_dependencies:
  injectable_generator: ^1.0.5
  build_runner: ^1.10.2

In my dart file,

```
@lazySingleton
class RecordCubit extends Cubit<RecordState> {
```

In my injection dart file

```
final getIt = GetIt.instance;

@InjectableInit(
  initializerName: r'$initGetIt', // default
  preferRelativeImports: true, // default
  asExtension: false, // default
)
void configureDependencies(Env env) => $initGetIt(getIt, environment: env.name);
```

If i use "flutter pub run build_runner watch --delete-conflicting-outputs", then injection.config.dart is auto generated.
In my injection.config dart file

```
GetIt $initGetIt(
  GetIt get, {
  String environment,
  EnvironmentFilter environmentFilter,
}) {
  final gh = GetItHelper(get, environment, environmentFilter);
  gh.lazySingleton<BodyPart>(() => BodyPart());
  gh.lazySingleton<RecordCubit>(() => RecordCubit());
  gh.lazySingleton<SignInFacade>(() => SignInFacade());
  return get;
}
```

I expect to register my lazySingleton class in injection.config, however, there is no registerLazySingleton..

I want to register my lazySingleton class using build_runner.

What can i do if registerLazySingleton is generated automatically..? 

Thank you.

**Comment by Milad-Akarie** [comment]
Hello @jun-hak  lazySingleton is a shortcut for registerLazySingleton
