### ISSUE TITLE
Changing multiple @RegisterAs(...) order return error

### ISSUE THREAD

**Issue by guyluz11** [Milad-Akarie/injectable#17]
On pure dart when using multiple `@RegisterAs(...)` for the same class and the current environment is not the first one in the order it throws exception:

`Unhandled exception:
Invalid argument (Object of type AnimalAbstract is not registered inside GetIt.
 Did you forget to pass an instance name? 
(Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;)): AnimalAbstract
#0      GetIt.get (package:get_it/get_it.dart:76:7)
#1      GetIt.call (package:get_it/get_it.dart:87:12)
#2      main (file:///D:/Programes/pure_dart/example_app/bin/main.dart:9:21)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
Observatory listening on http://127.0.0.1:60312/pqHMAqnPCWo=/`

**Comment by Milad-Akarie** [comment]
Hey @guyluz11 Multiable @RegisterAs isn't supported as you can not register multi instances with the same type inside get_it.
What are you tyring to do?

**Comment by guyluz11** [comment]
If I understood correctly `@RegisterAs(..., env: ...)` is the new way to do `@Bind.toType(..., env: ...)`
I am following this [tutorial on youtube](https://youtu.be/KNcP8z0hWqs?t=745)
And when I use `@Bind.toType` I get 

> Annotation must be either a const variable reference or const constructor invocation

**Comment by Milad-Akarie** [comment]
@guyluz11 There was a breaking change since then. Please revisit the README file

**Comment by Milad-Akarie** [comment]
@guyluz11 I'm closing this now if you have any further question please let me know
