### ISSUE TITLE
Migrating the package to Null safety?

### ISSUE THREAD

**Issue by ganeshrvel** [Milad-Akarie/injectable#170]
I use injectable in my app and it is one of the major null safety migration blocker. We had appreciate if you could migrate the package to null safety.

**Comment by britannio** [comment]
Duplicate of https://github.com/Milad-Akarie/injectable/issues/147

I use this package in several apps so it's a blocker for migrating these apps to null safety.

**Comment by Milad-Akarie** [comment]
@ganeshrvel  nullsafety version was just released 
https://pub.dev/packages/injectable/versions/1.2.0-nullsafety
https://pub.dev/packages/injectable_generator/versions/1.2.0-nullsafety
