### ISSUE TITLE
Please update to use get_it 6.x.x

### ISSUE THREAD

**Issue by eggnstone** [Milad-Akarie/injectable#173]
get_it (which injectable depends on) is now in version 6.0.0 which officially supports null safety.
I can't update my get_it dependency because of injectable.

**Comment by Milad-Akarie** [comment]
@eggnstone nullsafety version was just released 
https://pub.dev/packages/injectable/versions/1.2.0-nullsafety
https://pub.dev/packages/injectable_generator/versions/1.2.0-nullsafety
