### ISSUE TITLE
Inject Firebase Analytics

### ISSUE THREAD

**Issue by pxsanghyo** [Milad-Akarie/injectable#174]
I'm pretty sure I'm doing something wrong here but here goes...

I'm trying to inject FirebaseAnalytics but it says "FirebaseAnalytics is not registered inside GetIt."

Here is how I registered it. Note: FirebaseAuth works..

```
@module
abstract class FirebaseModule {
  @lazySingleton
  FirebaseAuth get firebaseAuth => FirebaseAuth.instance;

  @lazySingleton
  FirebaseAnalytics get firebaseAnalytics => FirebaseAnalytics();
}
```

Here is the generated code

```
Future<GetIt> $initGetIt(
  GetIt get, {
  String environment,
  EnvironmentFilter environmentFilter,
}) async {
  final gh = GetItHelper(get, environment, environmentFilter);
  final firebaseModule = _$FirebaseModule();
  gh.lazySingleton<FirebaseAnalytics>(() => firebaseModule.firebaseAnalytics);
  gh.lazySingleton<FirebaseAuth>(() => firebaseModule.firebaseAuth);
}
```

And the code that fails.. which is the first call to the supposedly injected instance of FirebaseAnalytics

```
await g<FirebaseAnalytics>().setAnalyticsCollectionEnabled(false);
```

Please help

**Comment by Milad-Akarie** [comment]
@pxsanghyo  does FirebaseAuth.instance return a future?

**Comment by eggnstone** [comment]
Maybe stupid question: did you call the generated $initGetIt() in your app before trying to get?

**Comment by pxsanghyo** [comment]
Sorry for the late response.

@eggnstone yep I ran $initGetIt first then initialize Firebase then tried to get FirebaseAnalytics but it says not injected error.

@Milad-Akarie No, FirebaseX.instance doesn't return a future. I'm using other FlutterFire packages like firestore, crashlytics, performance, auth and the problematic analytics. Other than analytics, the rest inject fine without error.

This is the rest of code...

```
@module
abstract class FirebaseModule {
  @lazySingleton
  FirebaseAuth get firebaseAuth => FirebaseAuth.instance;

  @lazySingleton
  FirebaseAnalytics get firebaseAnalytics => FirebaseAnalytics();

  // FirebaseCrashlytics - No web support
  @lazySingleton
  Option<FirebaseCrashlytics> get firebaseCrashlytics =>
      kIsWeb ? none() : some(FirebaseCrashlytics.instance);

  // FirebasePerformance - No web support
  @lazySingleton
  Option<FirebasePerformance> get firebasePerformance =>
      kIsWeb ? none() : some(FirebasePerformance.instance);

  @lazySingleton
  FirebaseFirestore get cloudFirestore => FirebaseFirestore.instance;
}
```

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final String environment = Environment().getOrCrash();
  injectDependencies(environment);

  await Firebase.initializeApp();
  await g<FirebaseAnalytics>().setAnalyticsCollectionEnabled(false);
  await g<Option<FirebaseCrashlytics>>().fold(
    () {},
    (instance) async {
      await instance.setCrashlyticsCollectionEnabled(false);
      FlutterError.onError = instance.recordFlutterError;
    },
  );
  await g<Option<FirebasePerformance>>().fold(
    () {},
    (instance) async {
      await instance.setPerformanceCollectionEnabled(false);
    },
  );
  if (environment == Environment.DEV) {
    final host = defaultTargetPlatform == TargetPlatform.android
        ? '10.0.2.2'
        : 'localhost';
    g<FirebaseFirestore>().settings = Settings(
      host: '$host:8080',
      sslEnabled: false,
      persistenceEnabled: false,
    );
  }

  runApp(App());
}
```

```
final GetIt g = GetIt.instance;

@injectableInit
Future<void> injectDependencies(String environment) async {
  $initGetIt(g, environment: environment);
}
```

Thanks for looking into it. I'm stuck as to why this doesn't work... pretty sure it's something stupid I did.

**Comment by Milad-Akarie** [comment]
I'm not sure what's going on here.
have you tried initializing Firebase before preforming the injection? 
```dart
await Firebase.initializeApp();
final String environment = Environment().getOrCrash();
injectDependencies(environment);
...
```

**Comment by pxsanghyo** [comment]
Thanks for the suggestion but sadly it didn't work.

This is the error just in case...

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: 'package:get_it/get_it_impl.dart': Failed assertion: line 316 pos 7: 'instanceFactory != null': Object/factory with  type FirebaseAnalytics is not registered inside GetIt.
(Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
Did you forget to register it?
```

**Comment by pxsanghyo** [comment]
It seems FirebaseAnalytics is “wired” differently.. I’m not sure if this is the reason for it not injecting like others but let me paste the code here so you can see.

FirebaseAnalytics doesn’t have a constructor specified or a static getter for instance and uses `_platformInstance`.

```dart
/// Firebase Analytics API.
class FirebaseAnalytics {
  final _platformInstance = FirebaseAnalyticsPlatform.instance;
  // ...
}
```

However other Firebase packages uses a similar pattern as the FirebaseFirestore example below.

```dart
/// Firebase Firestore API.
class FirebaseFirestore extends FirebasePluginPlatform {
  /// The [FirebaseApp] for this current [FirebaseFirestore] instance.
  FirebaseApp app;

  FirebaseFirestore._({/*required*/ this.app})
      : super(app.name, 'plugins.flutter.io/firebase_firestore');

  /// Returns an instance using the default [FirebaseApp].
  static FirebaseFirestore get instance {
    return FirebaseFirestore.instanceFor(
      app: Firebase.app(),
    );
  }
}
```

Again, I’m not sure if that makes a difference. I just noticed it so I was wondering if that was the reason.

**Comment by pxsanghyo** [comment]
Hmm it seems it's not just Analytics that doesn't get injected. I commented out Analytics and now it says Crashlytics (the next one from main) is not injected.

**Comment by pxsanghyo** [comment]
God.. I knew it was something stupid. Sorry for wasting your time.

**Comment by Milad-Akarie** [comment]
@pxsanghyo if we all couldn't see it then it must be a tricky mistake, you should share what went wrong in case someone else faces the same issue.

**Comment by spareblock** [comment]
Sorry, it was my fault. I thought it was FirebaseModule that was not injecting because of the error it output so when I asked the question I deleted out other injected modules to keep it short and specific to Firebase.

When I realized none of my modules were getting injected, I realized one of the module was preResolved. I just had to await it.

Your first comment asking if Firebase instance returns a Future was basically right.

Sorry for wasting your time.

**Comment by pxsanghyo** [comment]
Sorry, it was my fault. I thought it was FirebaseModule that was not injecting because of the error it output so when I asked the question I deleted out other injected modules to keep it short and specific to Firebase.

When I realized none of my modules were getting injected, I realized one of the module was preResolved. I just had to await it.

Your first comment asking if Firebase instance returns a Future was basically right.

Sorry for wasting your time.

**Comment by ariefwijaya** [comment]
So, what is the solution ? how you make it works? @pxsanghyo

**Comment by pxsanghyo** [comment]
@ariefwijaya My problem was `$initGetIt` was async but I didn't await for it.

```dart
void main() async {
  await injectDependencies();
}
```

**Comment by ariefwijaya** [comment]
Nice thank you, my problem solved now!
