### ISSUE TITLE
injectable_generator pub.dev installing information

### ISSUE THREAD

**Issue by rubgithub** [Milad-Akarie/injectable#18]
Hi, just an info: https://pub.dev/packages/injectable_generator#-installing-tab- 

Add this to your package's pubspec.yaml file:
dependencies:

Instead of
dev_dependencies:

**Comment by Milad-Akarie** [comment]
Hey, @rubgithub The installation file is actually automatically generated, I have no idea how I can alter it, do you?

**Comment by rubgithub** [comment]
Ok, I didn't know that was automatically generated,
