### ISSUE TITLE
Generated file obstructing null-safety migration

### ISSUE THREAD

**Issue by wayne-werner** [Milad-Akarie/injectable#183]
I am attempting to migrate my application to null safety.  Following the guidelines, I am trying to migrate my all of my dependencies, which includes injectable.  After all of my dependencies are migrated I will then update my pubspec.yaml to min dart sdk of 12.0.0, which will turn on null safety for my app itself.

When I migrate injectable to null safety and generate, however, the generated file contains null safety constructs requiring 12.0.0 for my app to compile.

Non-null-safety generated version:
```
_i1.GetIt $initGetIt(_i1.GetIt get,
    {String environment, _i2.EnvironmentFilter environmentFilter}) {
```
null-safety generated version:
```
_i1.GetIt $initGetIt(_i1.GetIt get,
    {String? environment, _i2.EnvironmentFilter? environmentFilter}) {
```

Unfortunately, this hampers my ability to follow the migration guidelines.  It means I cannot update injectable without updating the min sdk, while I have packages I can not yet update.  Also, because of conflicting analyzer package and crypto package used by analyzer between the null/non-null packages used in common with freezed and json-serializable as well as injectable, I am prevented from updating those packages as well until I can update injectable.  Neither freezed nor json-serializable seem to generate code that breaks app compilation without updating to min 12.0.0.  I also have another package, uuid which uses crypto, so that also won't allow me to update until I update injectable.

Is there anyway I can possibly work around this, or can the offending generated code be modified to allow me to update injectable before actually modifying my min sdk to 12.0.0?

**Comment by DenisGL** [comment]
Yes, you need to add "userNullSafety: false" to @InjectableInit annotation:

```
@InjectableInit(usesNullSafety: false)
void configureAppInjection(final getIt, String environment) {
  $initGetIt(getIt, environment: environment);
}

```

**Comment by wayne-werner** [comment]
I didn't see that anywhere...  I'll give it a try.
I assume that I can remove that when I actually get to the point where I migrate the app itself.  If this works, I'll be down to two dependencies requiring null safety updates before I can do that.  Thanks!
