### ISSUE TITLE
Package is not available.

### ISSUE THREAD

**Issue by kim-mini6** [Milad-Akarie/injectable#187]
Because no versions of build_runner match >1.12.2 <2.0.0 and build_runner 1.12.2 depends on build >=2.0.0 <2.1.0, build_runner ^1.12.2 requires build >=2.0.0 <2.1.0.

And because injectable_generator >=1.2.0-nullsafety depends on build ^1.6.3, build_runner ^1.12.2 is incompatible with injectable_generator >=1.2.0-nullsafety.

So, because dolink_app depends on both injectable_generator ^1.2.0 and build_runner ^1.12.2, version solving failed.
pub get failed (1; So, because dolink_app depends on both injectable_generator ^1.2.0 and build_runner ^1.12.2, version solving failed.)

Is there a solution?

**Comment by Milad-Akarie** [comment]
Have you tried version 1.2.0? Without the nullsafety

**Comment by kim-mini6** [comment]
yes.

injectable_generator: ^1.2.0
build_runner: ^1.12.2

my package

**Comment by Milad-Akarie** [comment]
@kim-mini6  is this still in issue in latest version? 
```yaml
injectable 1.2.2
injectable_generator 1.2.2
```

**Comment by kim-mini6** [comment]
I am using it well now.

thank you.
