### ISSUE TITLE
Scope Support

### ISSUE THREAD

**Issue by AndyDavidJoyce** [Milad-Akarie/injectable#189]
Hi! 

Im looking at using injectable, however, one feature that that i need to use that I have not seen mentioned in the documentation is scopes. Is this currently supported by injectable?

**Comment by Milad-Akarie** [comment]
Hey! @AndyDavidJoyce, I didn't get the chance to play with scopes yet, could you show me a brief example on how you're using them manually?

**Comment by creativepsyco** [comment]
Sample Test [here](https://github.com/fluttercommunity/get_it/blob/ae4a05b8e7dc91b777d56db57c26d611ed978736/test/scope_test.dart)

A brief explanation is [here](https://github.com/fluttercommunity/get_it#scopes)

Perhaps a brief API could look like:

```dart
@module
@installIn('account_scope')
```

and when `getIt.pushScope('account_scope')` is called, these registrations could happen.

Something along the lines of [Hilt](https://developer.android.com/training/dependency-injection/hilt-android#inject-interfaces) - the scoped component based DI framework for Android.

**Comment by alexander-shustanov** [comment]
Hi! Any news about the issue?
Actually, the di config code won't become more difficult:

```dart
_i1.GetIt $initGetIt(_i1.GetIt get,
    {String? environment, _i2.EnvironmentFilter? environmentFilter}) {
  final gh = _i2.GetItHelper(get, environment, environmentFilter);
  
  get.onScopeChanged = (pushed) {
    if(pushed) {
      switch(get.currentScopeName) {
        case "scope1":
          // register all "scope1" dependencies 
          // ...
          break;
        case "scope2":
          // register all "scope2" dependencies 
          // ...
          break;
      }
    }
  };
  
  // register all default dependencies
  // ...
  return get;
}
```

**Comment by jtdLab** [comment]
Hi. Any news about this? Would be really great to have this feature.

**Comment by fdelucchijr** [comment]
I'm just waiting for this feature to integrate injectable in my company's mobile app. @Milad-Akarie, I'm happy to wait as long you need!!!

**Comment by elias8** [comment]
➕1
