### ISSUE TITLE
Use constants to control whether to inject

### ISSUE THREAD

**Issue by windrunner414** [Milad-Akarie/injectable#191]
I don't want to inject a dev config in prod env.Now the code like below:
```
@dev
class DevConfig {}
@prod
class ProdConfig{}
$initGetIt(getIt,environment:prod);
```
but the DevConfig still be injected, so dart will not remove it from the compiled app.I want to use a constant to control whether it is injected.generated code like this
```
if (injectDev) singleton<Config>(DevConfig(), registerFor: {_dev})
```
then
```
$initGetIt(getIt,environment:kReleaseMode?prod:dev,control:{dev:!kReleaseMode})
```

**Comment by mrverdant13** [comment]
An alternative would be to generate separated injector functions. One per flavor/environment.
Regarding the ones that use filters, they could be grouped in yet another isolated injector function.
