### ISSUE TITLE
Injectable is throwing "Missing dependencies in" error.

### ISSUE THREAD

**Issue by ganeshrvel** [Milad-Akarie/injectable#193]
flutter doctor 
```
Flutter 2.1.0-13.0.pre.574 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 02efffc134 (31 hours ago) • 2021-04-10 03:49:01 -0400
Engine • revision 8863afff16
Tools • Dart 2.13.0 (build 2.13.0-222.0.dev)
```

  injectable_generator: ^1.2.2
  get_it: ^6.0.0
  injectable: ^1.2.2

When i try to run the build runner it is throwing:
```
[WARNING] injectable_generator:injectable_config_builder on lib/common/di/di.dart:
Missing dependencies in squash_archiver/common/di/di.dart

[ABCRepository] depends on unregistered type [ABCDataSource] from package:my_app/abc_data_source.dart
[XYZRepository] depends on unregistered type [XYZDataSource] from package:my_app/xyz_data_source.dart

```

Nothing has changed, I just tried to migrate the app to null safety.

```dart
@lazySingleton // I even tried @LazySingleton()
class ArchiveDataSource {
}

```

Nothing seems to be working. What should I do?

**Comment by mosabalrsaheed** [comment]
I am getting the same warning message, yet everything is working as expected.

And the same reason as well just migrated to null safety. 

False Positives Maybe?

**Comment by Abdktefane** [comment]
I am getting the same warning message

**Comment by duyhungtnn** [comment]
After migrated to null safety. I am getting the same warning too. 

Everything is working as before but so much a noisy warning.

**Comment by adamsmaka** [comment]
as mentioned in #125 use `ignoreUnregisteredTypes: [ABCDataSource]` in your `InjectableInit` configuration to mute the warnings
