### ISSUE TITLE
Feature Request: Annotation for TargetPlatform

### ISSUE THREAD

**Issue by mars3142** [Milad-Akarie/injectable#212]
Problem:
I do have an abstract class **PlatformClass** and two implementations **PlatformClassAndroid** and **PlatformClassIOS**. Because they use different implementations, I would like to use dependency injection depending on the target platform.

For **DEV** and **PROD** I can switch, but not for target. That's why I wish, there would also be an annotation for TargetPlatform or something like that.

**Comment by mars3142** [comment]
Oh, you can combine Environment and Platform with that filter? So I'm able to have 4 implementations and it will work?

**Comment by Milad-Akarie** [comment]
we're only using Environments here, and yes you can use as many envs as you can, you can even implement your own Environments filter

**Comment by Milad-Akarie** [comment]
```dart
configInjector(getIt,
      environmentFilter: NoEnvOrContainsAll(
        {
          Environment.dev,
        // here we're passing an environment based on platform
          Platform.isAndroid ? android.name : ios.name,
        },
      ));
```

**Comment by mars3142** [comment]
Hmm. But it will be real overhead to create new "environments" like "androidDev", "androidProd", "iosDev", "iosProd" instead of just "android", "ios". Because dev and prod already exists and later I need the combination for windows, linux and macos, fuchsia... as well. So I need to create my own matrix, instead of just use predefined target platforms. It would be worse, if I add "profile" as well, so I need to create "androidProfile" and "iosProfile". An annotation would be really slim down the boilerplate code.

But if this is the only way to go, I have to go this way.

**Comment by Milad-Akarie** [comment]
@mars3142 injectable supports multi environments, you can have something like this 

```dart
@dev
@android
@Injectable(as: AndroidService)
class PlatformClassAndroid extends PlatformClass {}
```

**Comment by mars3142** [comment]
Now I understand. Thanks.
