### ISSUE TITLE
Is it possible to preResolve singleton without defining Module?

### ISSUE THREAD

**Issue by AlexandrFarkas** [Milad-Akarie/injectable#219]
I mean, you can define factoryMethod with async, but you still need to call getIt.getAsync(). 
@preResolve just does nothing.

**Comment by Milad-Akarie** [comment]
@AlexandrFarkas  annotate the class not the factory method with @preResolve

```dart
@preResolve
@singleton
class MySingleton{
  @factoryMethod
  static MySingelton init(...);
}
```

**Comment by AlexandrFarkas** [comment]
Thanks a lot.
I think, that you should add it to documentation, because 'preResolve' docs say only about Futures.

```
/// Futures annotated with [preResolve]
/// will be pre-awaited before they're
/// registered inside of GetIt
```

**Comment by Milad-Akarie** [comment]
@AlexandrFarkas  will do.
