### ISSUE TITLE
Registering third party FirebaseAuth

### ISSUE THREAD

**Issue by sterrenburg** [Milad-Akarie/injectable#22]
I am trying to use Mockito to mock the functionality of the third party class `FirebaseAuth` class in the test environment. 

`injectible` is at version `^0.2.3` and `injectible_generator` is at version `^0.2.4`.

When trying this, I first created an injectable mock class in the test environment.

```dart
/// Mock class for FirebaseAuth
@RegisterAs(FirebaseAuth, env: Environment.test)
@injectable
class MockFirebaseAuth extends Mock implements FirebaseAuth {}
```

In the test file, I configure `get_it` in test mode and then try to mock some functionality of `FirebaseAuth`.

```dart
// * firebase_auth_test.dart

void main() {
  // Run `$initGetIt(GetIt.instance) in test mode before all tests
  setUpAll(() {
    TestWidgetsFlutterBinding.ensureInitialized();
    configure(injectable.Environment.test);
  });

  // Tests that want access to `getIt<FirebaseAuth>()` go here.
  test('should be able to mock getIt FirebaseAuth instance', () {
    final firebaseAuth = getIt<FirebaseAuth>();
    when(firebaseAuth.toString()).thenAnswer((_) => 'I am a MockFirebaseAuth');
  });
}
```

When running this test, this error is thrown during `configure`:
```shell
'package:get_it/get_it_impl.dart': Failed assertion: line 248 pos 14: 'instanceFactory != null': No type FirebaseAuth is registered inside GetIt.
 Did you forget to pass an instance name? 
(Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;)
```

Am I providing the `MockFirebaseAuth` incorrectly? I tried something similar without environments, but then it is difficult to expose the regular `FirebaseAuth` in the prod/dev environment.

**Comment by Milad-Akarie** [comment]
Hey, @sterrenburg How does your generated code look like?

**Comment by sterrenburg** [comment]
To simplify the use case, I created [a new repository](https://github.com/sterrenburg/mock_test_app) for this issue. 

This is the generated code for the implemented snippets from my previous comment.

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

import 'package:mocktestapp/mock.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:get_it/get_it.dart';

void $initGetIt(GetIt g, {String environment}) {
  //Register test Dependencies --------
  if (environment == 'test') {
    g.registerFactory<FirebaseAuth>(() => MockFirebaseAuth());
  }
}

```

I am not experienced with get_it, but the generated code seems OK. It exposes `MockFirebaseAuth` as `FirebaseAuth` in the test environment, which is configured during the test with `configure(injectable.Environment.test);`

Running the test from the repository, the error is the same:

```shell
'package:get_it/get_it_impl.dart': Failed assertion: line 248 pos 14: 'instanceFactory != null': No type FirebaseAuth is registered inside GetIt.
 Did you forget to pass an instance name? 
(Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;)
```

**Comment by Milad-Akarie** [comment]
@sterrenburg looks like you forgot to pass the environment string to $initGetIt
instead of just passing Getit instance
```dart
void configure(String environment) =>$initGetIt(getIt);
```
pass the environment string to $initGetIt()
```dart
void configure(String environment) =>
    $initGetIt(getIt, environment: environment);
```

**Comment by sterrenburg** [comment]
Thank you, this alongside a wrongly configured abstract class were the culprits. You saved me a lot of headache!
