### ISSUE TITLE
Is it possible to use Injectable in a multi-module project?

### ISSUE THREAD

**Issue by giovanigm** [Milad-Akarie/injectable#222]
Hello! I'm trying to use Injectable in a multi-module project, but I'm not figuring out how to do it.

Is there a way to make it work? If so, could you update the docs with an example?

Thanks in advance!

**Comment by trigri1** [comment]
I am trying to achieve the same. Have you been able to find something helpful? Thanks

**Comment by duyhungtnn** [comment]
You could do something like that 

- Keep only one instance of `GetIt`.
- Any module has it own `init.dart` and `init.config.dart`
```
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'init.config.dart';

late final GetIt module1Inject;

@injectableInit
Future<void> configureInjection(GetIt inject) async {
  $initGetIt(inject);
  module1Inject = inject;
}

```
- Create `GetIt` instance with configureInjection() may be in the main module (main.dart) 
- Pass the `GetIt` instance to the module and add the configure for each module 

```
configureInjection() 
module1.configureInjection(getIt) 
```

after that, any configuration on `module 1` is added to the `GetIt` instance configuration.

**Comment by giovanigm** [comment]
Worked like a charm! Thanks @duyhungtnn !!
