### ISSUE TITLE
Can't register a dependency with type Function(<anytype>)?

### ISSUE THREAD

**Issue by gasaichandesu** [Milad-Akarie/injectable#224]
Consider following code:
```dart
@Injectable()
class ServiceA {
  final Function(int a)? dependency;

  ServiceA({
    @factoryParam this.dependency,
  });
}

@Injectable()
class ServiceB {
  ServiceB(ServiceA serviceA);
}
```

Running injectable_generator gives following error:
```
line 21, column 29 of .: Expected to find ';'.
   ╷
21 │ gh.factoryParam<_i5.ServiceA, dynamicFunction(int)?, dynamic>((dependency, _) => _i5.ServiceA(dependency: dependency));
   │                             ^
```

I suppose the problem is caused by `dynamicFunction` part, which means that generator incorrectly resolves function type. Is it a bug or intended behavior? Also, generator works fine if type of dependency is Function? instead of Function(int)?.

**Comment by Nikitae57** [comment]
Have the same problem
