### ISSUE TITLE
Update analyzer version to ^2.0.0

### ISSUE THREAD

**Issue by akarabach** [Milad-Akarie/injectable#227]
Faced with old analyzer version 1.5.0. 
![image](https://user-images.githubusercontent.com/12261380/126453451-b2b87654-613d-46c0-8e69-59f762002e8a.png)

**Comment by fikretsengul** [comment]
Yes, please. Is it safe to use "dependency_overrides" ?

**Comment by rokk4** [comment]
please update analyzer dep. Thanks!

**Comment by proninyaroslav** [comment]
The current version of `flutter stable` is still stuck using `meta: 1.3.0`, so analyzer 2.0.0 is incompatible with it.

**Comment by brizaldi** [comment]
Hi @Milad-Akarie any update about this?
