### ISSUE TITLE
How to give the factory param a name?

### ISSUE THREAD

**Issue by Haidar0096** [Milad-Akarie/injectable#235]
I have the logger registered this way:

```
@module
abstract class RegisterModule {
  Logger logger(@factoryParam Level? logLevel) => Logger(level: logLevel);
}
```

I am getting it when I need it, like this:

`final Logger logger = serviceLocator.get<Logger>(param1: Level.debug);`

Is there a way to change the `param1` name to something else like `logLevel`, i.e. I want to write this:

`final Logger logger = serviceLocator.get<Logger>(logLevel: Level.debug);`

**Comment by Milad-Akarie** [comment]
@Haidar0096  unfortunately that can not be done.
