### ISSUE TITLE
Trouble initialising Hive with Injectable

### ISSUE THREAD

**Issue by Schallabajzr** [Milad-Akarie/injectable#247]
When running the build runer generate method I get the following output.
```
[ApproverLocalDataSourceImpl] depends on unregistered type [HiveInterface] from package:hive_flutter/adapters.dart

Did you forget to annotate the above class(s) or their implementation with @injectable?
or add the right environment keys?
```

The dependency injection works if I initialize it like this
```
//Service Locator
final sl = GetIt.instance;

@InjectableInit(
  initializerName: r'$initGetIt',
  preferRelativeImports: true,
  asExtension: false,
)
@InjectableInit(generateForDir: ['lib'])
void configureDependencies() {
  sl.registerLazySingleton<HiveInterface>(() => Hive);
  $initGetIt(sl);
}
```

How can I generate the above line using RegisterModule

if I add
```
@module
abstract class RegisterModule {

  @lazySingleton
  HiveInterface get hive => Hive;

  ...
}
```

inside the RegisterModule I still get the
`[ApproverLocalDataSourceImpl] depends on unregistered type [HiveInterface] from package:hive_flutter/adapters.dart
` message.

**Comment by ZanSchaffer** [comment]
I init hive above dependency injection in my main method.
```
void main() async {
  await Hive.initFlutter();
  di.configureDependencies();
  runApp(const MyApp());
}
```

**Comment by godofsleepy** [comment]
https://github.com/Milad-Akarie/injectable/issues/74 there are some example how to initialize Hive, maybe it's helpful

**Comment by Schallabajzr** [comment]
> @Schallabajzr why two annotations of @InjectableInit ?

I don't remember anymore this issue isn't relevant anymore. Feel free to close it.
