### ISSUE TITLE
Auto injection / real DI

### ISSUE THREAD

**Issue by subzero911** [Milad-Akarie/injectable#248]
I played around with this package and found that current `injectable` implementation is not a real DI, but just an IoC-container. It means you can resolve dependencies from container like this `var concreteType = getIt<IType>()`, but container doesn't actually injects dependencies into classes. "Fair" DI frameworks inject their dependencies automatically.

Here is a simple example:
![image](https://user-images.githubusercontent.com/12999702/134983492-46c983e4-2aca-4aad-a482-d1f9752a988a.png)
Here _api is filled automatically:
![image](https://user-images.githubusercontent.com/12999702/134983581-9577c34f-7487-4e8b-abe0-7162b1186ff5.png)
It produces the following output:
![image](https://user-images.githubusercontent.com/12999702/134983667-51f04fda-3304-47ed-b1d8-27f854c89f72.png)
But you still have to use manual resolving:  
![image](https://user-images.githubusercontent.com/12999702/134984187-8655051a-9f7f-4664-9bf9-2180fa287a7d.png)
Any `context.read<T>()` / `container.resolve<T>() / GetIt.get<T>()`  etc. is a violating of DI principle.
Seems like there's no way to avoid it.
This makes the whole package meaningless. Why should I go through all my codebase and decorate all the classes with tons of attributes to get the config file (which I can easily construct by myself), if I still have to manually resolve classes?

Look at Zenject, it uses C# reflection and automatically binds abstract interaces to concrete implementations: https://github.com/modesttree/Zenject
You write the installer
```csharp
  InstallDependencies() {
    Container.Bind<IController>().To<GameController>();
  }
```
Here magic happens:

```csharp
[Inject]
IController _myController;

void wakeUp() {
  _myController.doSmth(), // _myController already has an instance of type GameController here
}
```

And you are guaranteed this field is not null, and you always have a right instance.
AFAIK other DI frameworks (Guice, Dagger, Ninject) follows the same principle.

Do you have any ideas how to achieve it in Dart?

**Comment by leoshusar** [comment]
I was thinking about the same thing actually and I believe there is no simple way to do it (I might be wrong), because Dart has no proper reflection support and Flutter doesn't support `mirrors`.

The only way I can think of now is using `reflectable` package, which relies on code generation.
Another idea which might work is to automatically generate factory constructors with `getIt<Something>()`, but it would just move `getIt` from one place to another and you would have to inject via constructor only.

**Comment by subzero911** [comment]
Sorry, if I seemed rude. You're right, I just want to point on this downside.

**Comment by subzero911** [comment]
@leoshusar 
You can do it at the code generation step.
As far as I know, `jugger_generator` uses this approach.
If you forgot to provide some dependencies, the build runner will just fail.
