### ISSUE TITLE
Injecting @GeneratedMock() into @Environment("test")

### ISSUE THREAD

**Issue by lloydrichards** [Milad-Akarie/injectable#249]
I'm building out a project at the moment with a focus on TDD, all my unit tests have been going great with Mockito where I can mock the repository using their `@GenerateMocks([IAuthRepository])` generator.  However, as I'm getting into the widget tests I'm finding it hard stub the mocked classed when injected.

Currently, I'm creating a mocked class and registering it under the test environment:
 ```dart
@Environment("test")
@LazySingleton(as: IAuthRepository)
class MockFirebaseAuthFascade with Mock implements IAuthRepository {}
```

and then in my `main()` I can setup using the `configureInjection(Environment.test);` and then get my mock class using `getIt<IAuthRepository>()`.
```dart
void main() {
  setUpAll(() async {
    configureInjection(Environment.test);
  });

testWidgets(
        'GIVEN form is initial state '
        'WHEN ElevatedButton is pressed '
        'THEN see two error messaged below TextField', (tester) async {
      // Arrange
      await tester.pumpWidget(
        MaterialApp(
          localizationsDelegates: const [
            Localize.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: Localize.delegate.supportedLocales,
          home: BlocProvider(
            create: (context) => getIt<SignInFormBloc>(),
            child: const Scaffold(
              body: SignInForm(),
            ),
          ),
        ),
      );
      final mockAuth = getIt<IAuthRepository>();
      final Finder signIn =
          find.byKey(const Key("auth_sign_in_with_email_button"));
      // Act
      await tester.pumpAndSettle();
      await tester.tap(signIn);
      await tester.pump(const Duration(seconds: 1));
      // Assert
      verifyNever(mockAuth.resetPassword(email: anyNamed("named")));
  });
}
```

What's happening though is that I'm not able to use `anyNamed("named")` as it's required the same type as my implements IAuthRepository.  I'm also getting messages about the IAuthRepository returning NULL instead of the stubbed values that I assert with `when`

All in all, I'm a little lost around the best practice for combing Injectable and Mockito for widget testing so if anyone has any suggestions or words of wisdom it's much appreciated.

**Comment by kzawadi** [comment]
Hello for me I have some questions on how you did inject the bloc and repositories for unit testing.

**Comment by lloydrichards** [comment]
i use @injectableInit to create a configureInjection function based on an environment and then call this normally in the void main().  for widget tests I can do the same using a test environment and then in the setUp() I can call the configureInjection with the test environment.

this way all my injected dependencies are in the test, but since I mock out the repository and inject it as IRepository (while extending the generated mock) then I can cast the IRepository from the test environment as the mock version without it breaking my when()

hope that makes sense, feel free to ask more questions

**Comment by kzawadi** [comment]
Okay, let me recall this ... in my Domain, I register injectables with the production environment (is it also necessary to annotate them with the test environment, or is the test environment annotated in testing only).

fine example look at this (https://github.com/ResoCoder/flutter-ddd-firebase-course)

now it has no testing but everything like repositories, blocs are gotten by getIt<somebloc>()  ... now how do I set up this for unit testing without limiting the uses of that good injection methodology.

**Comment by lloydrichards** [comment]
The only things you need to register with `@injectable` are those that have dependencies that stretch between your application and infrastructure layers.  The domain repositories are agnostic of all dependencies and shouldn't be injected.

In the domain you create the contract:
```
abstract class IRepo {
...
}
```

In the Infrastructure you define the implementation:
```
@Environment("dev")
@LazySingleton(as: IRepo)
class MyRepo extends IRepo {
final MyDependency _dep;
MyRepo(this._dep)
}
```

And then in your application you call the domain version of the repository and then inject it with the version of your `getIt()`:
```
@injectable
class MyBloc extends Bloc<MyState, MyEvent>{
final IRepo _repo;
...
}
```

Injectable will swap out the IRepo with whichever LazySingleton you have specified in the Infrastructure layer with all its dependencies.  Allowing you to have different repositories for dev, testing, prod etc

With unit testing, it depends what you are testing but the main thing will be adding the mocked dependencies so you can stub their calls.  Most of the time you just make an instance of your repo with the mock, not using Injectable:

```
test((){
MockDep mockDep =MockDep();
MyRepo repo = MyRepo(mockDep);

...
}
```

**Comment by kzawadi** [comment]
oh Got it. Thanks man

**Comment by sbalex27** [comment]
Still no news on this issue?
I need a scalable, more clean and tidy solution :(
