### ISSUE TITLE
How to register singleton as 2 different types?

### ISSUE THREAD

**Issue by pro100svitlo** [Milad-Akarie/injectable#261]
I have next class:
```dart
class MyService implement InterfaceOne,  InterfaceTwo{
```

I would like to have access via `get_it` to both `InterfaceOne` and `InterfaceTwo`. But `LazySingleton` allows me to use only one `as:`...

Is there any way except doing a manual workaround like next:
```dart
GetIt.instance.registerLazySingleton<InterfaceOne>(
      () => GetIt.instance.get<MyService>());
GetIt.instance.registerLazySingleton<InterfaceTwo>(
      () => GetIt.instance.get<MyService>());
```

**Comment by pro100svitlo** [comment]
Any suggestion or idea?

**Comment by matthias-steinkamp** [comment]
I tried something like 3rd party integration with a module like this:

```dart
@module
abstract class RegisterInterfaces {
  @LazySingleton(as: InterfaceOne)
  InterfaceOne get interfaceOne  => getIt<MyService>();

  @LazySingleton(as: InterfaceTwo)
  InterfaceTwo get interfaceTwo => getIt<MyService>();
}
```

However, the generated injection config did not work.

**Comment by nuunoo1977** [comment]
did you found any solution?  thanks

**Comment by pro100svitlo** [comment]
Nope, there are two workarounds: manual and module (described above)
