### ISSUE TITLE
Registering generated retrofit API class

### ISSUE THREAD

**Issue by sterrenburg** [Milad-Akarie/injectable#27]
I am using [`retrofit`](https://pub.dev/packages/retrofit) to generate a Rest API and I would like to register the generated API class using `injectable`.

`injectible` is at version `^0.2.3` and `injectible_generator` is at version `^0.2.4`.

### What works
This is the class (_without_ using `injectable`) that generates the API using `retrofit`.

```dart
// * api_client.dart

part 'api_client.g.dart';

@RestApi(baseUrl: 'https://example.com/api/v1/')
abstract class ApiClient {
  factory ApiClient.dio(Dio dio, {String baseUrl}) = _ApiClient;

  @GET('?summaryRaw')
  Future<Summary> getSummary();
}
```

The generated file from `retrofit` now works as expected:

```dart
// * api_client.g.dart

// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'api_client.dart';

// **************************************************************************
// RetrofitGenerator
// **************************************************************************

class _ApiClient implements ApiClient {
  _ApiClient(this._dio, {this.baseUrl}) {
    ArgumentError.checkNotNull(_dio, '_dio');
    this.baseUrl ??= 'https://example.com/api/v1/';
  }

  final Dio _dio;

  String baseUrl;

  @override
  getSummary() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final Response<Map<String, dynamic>> _result = await _dio.request(
        '?summaryRaw',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'GET',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    final value = Summary.fromJson(_result.data);
    return Future.value(value);
  }
}

```

### What goes wrong
I created an injectable data source class that registers a final field `ApiClient`.
```dart
//* api_data_source_dio.dart

@prod
@injectable
class ApiDataSourceDio implements ApiDataSource {
  ApiDataSourceDio([ApiClient apiClient])
      : _apiClient = apiClient ?? getIt<ApiClient>();

  final ApiClient _apiClient;

  @override
  Future<Summary> getSummary() => _apiClient.getSummary();
}
```

When running the generator (without any annotation), I get this error **as expected**:
```shell
...
[WARNING] injectable_generator:injectable_config_builder on lib/injection.dart:
Injectable Generator --------------------------------------------------

[ApiDataSourceDio] depends on [ApiClient] which is not injectable!

Did you forget to annotate the above classe(s) or their implementation with @injectable?
------------------------------------------------------------------------
...
```

After annoting `ApiClient` with `@injectable` and @factoryMethod` (in `api_client.dart`) and running the generator, a new error is thrown:
```shell
...
[SEVERE] injectable_generator:injectable_builder on lib/features/api/data/datasources/api_client.dart:
Error running Instance of 'InjectableGenerator'
Unresolvable Asset from String in dart:core/string.dart.
[WARNING] injectable_generator:injectable_config_builder on lib/injection.dart:
Injectable Generator --------------------------------------------------

[ApiDataSourceDio] depends on [ApiClient] which is not injectable!

Did you forget to annotate the above classe(s) or their implementation with @injectable?
------------------------------------------------------------------------

[INFO] Running build completed, took 13.4s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 97ms

[SEVERE] Failed after 13.5s
pub finished with exit code 1
```

### My questions

1. Is it possible to somehow annotate `ApiClient`, so that the generated class from `retrofit` can be exposed via `injectable`? 

2. If this is not possible, could I somehow manually register the generated class using `get_it`?

I realize that especially question 2 might be outside the scope of this package. If you feel like these questions do not belong here, let me know and I will look elsewhere!

**Comment by Milad-Akarie** [comment]
Hey, @sterrenburg  I'm glad you're relying on the lib. 
The build I'm working on right now is going to handle your case completely. 
but for now, where are you passing the baseURL from? do you need to pass it in the static create fun? 
```dart
 factory ApiClient.dio(Dio dio, {String baseUrl})
```
 if you, for example, could make the create function look like this
```dart
 factory ApiClient.dio(Dio dio)
```
then simply annotate the create func with @factoryMethod and injectable will treat it like a named constructor

```dart
@injectable
abstract class ApiClient{
@factroyMethod
 factory ApiClient.dio(Dio dio)
}
```

as I said the next build is going to include get_it 4.0.0 support that means FactoryParams are gonna be supported so passing a string like baseUrl in your case will be possible.

**Comment by Milad-Akarie** [comment]
v0.3.0 will handle your case using factoryParams
```dart
@injectable
abstract class ApiClient{
@factroyMethod
 factory ApiClient.dio(Dio dio,{@factoryParam String baseUrl});
}
```

**Comment by sterrenburg** [comment]
For the time being, I switched to manually implementing the endpoints using `dio` (e.g. without `retrofit`).

I ignored the `baseUrl` since I made it positional, but that does explain the `Unresolvable Asset` error from my original post.

Thank you for your contribution, I will use the new `factoryParam` once ^0.3.0 is available!

**Comment by Milad-Akarie** [comment]
@sterrenburg  v0.3.0 is released!
