### ISSUE TITLE
Something like `@order` to force registration ordering?

### ISSUE THREAD

**Issue by fzyzcjy** [Milad-Akarie/injectable#272]
Hi thanks for the lib!

I have some singletons that should be registered in predetermined order, while they have no dependency to each other. (For example, at constructor they `addListener` to something and I want the listeners to be in some predetermined order).

Problem is, how to achieve it in injectable? With Java Spring's dependency injection, I can use the `@Order(123)` annotation. Thus I would appreciate it if I could do similar things in Dart/Flutter as well.

**Comment by casvanluijtelaar** [comment]
plus there are still a bunch of issue where it's generating dependencies in the wrong order and this would allow us to manually fix it without having to edit the generated file every build.

**Comment by Milad-Akarie** [comment]
@fzyzcjy @casvanluijtelaar  done in version 2.0.0 
https://github.com/Milad-Akarie/injectable#manual-order

**Comment by fzyzcjy** [comment]
Congratulations! (after a year)
