### ISSUE TITLE
Depends on unregistered type warning

### ISSUE THREAD

**Issue by joeldegerman99** [Milad-Akarie/injectable#274]
Hello,

 I am getting some [xxxxx] depends on unregistered type [xxxxx] from package:xxxxxxxx when building

I am passing a custom class as a factoryParam and it works and all but i get a warning since my factoryParam class has a dependency on a enum type.

```
enum SearchType { people, opportunities, customers }

class SearchCubitConfig {

  SearchCubitConfig({this.type, this.query = ''});

  final SearchType? type;
  final String query;
}

class SearchModelCubit extends Cubit<SearchModelState> {
  SearchModelCubit(this.repository, @factoryParam this.config)
      : assert(config != null),
        super(const SearchModelState()) {
    _search();
 }
```

This is my code (i use a build.yaml file to automatically register cubits as injectable)

Everything works as expected and i get the `SearchCubitConfig` class passed as an argument and i can use in the cubit code, but the warning is super annoying. Is there anyway to get rid of it?

Thanks!

**Comment by joeldegerman99** [comment]
@Milad-Akarie if you could answer me it would be great! :)

**Comment by Milad-Akarie** [comment]
@joeldegerman99  factory prams should be automatically ignored, no idea what's going on here.
you can always manually ignore

```dart
@InjectableInit(
  /...
  ignoreUnregisteredTypes: [TypeToIgnore],
)

**Comment by joeldegerman99** [comment]
@Milad-Akarie I think I might have found a cause for this issue, it seems when a factoryParam class is imported using a `barrel` file the generator has a hard time figuring out that it should be ignored. 

i.e on one class that is injected using factoryParam it required a `BuildContext` property, the `BuildContext` was imported from `widgets.dart` and not `material.dart`, on another class that was going to be injected I imported the `BuildContext` from `material.dart`.

When I then passed the BuildContext to the `ignoreUnregisteredTypes` and imported it using `material.dart` the issue was gone for the class with the `BuildContext ` imported from `material.dart` but not the `BuildContext` from `widgets.dart` 

Hope this helps
