### ISSUE TITLE
How to inject Floor Database Class

### ISSUE THREAD

**Issue by Abdelrhman-Mahmoud96** [Milad-Akarie/injectable#282]
I'm creating a database using floor package [https://pub.dev/packages/floor](url)
i don't know how to use injectable to inject the database class here:
```
@TypeConverters([StatusTypeConverter, DateTypeConverter])
@Database(version: kVersion, entities: [Note])
abstract class AppDatabase extends FloorDatabase{
  NoteDao get noteDao;
}
```
my Dao:
```
@dao
abstract class NoteDao{
  @Query('SELECT * FROM $kTableName')
  Stream<List<Note>> getNotes();
}
```

and of course when i try to run the code generator i get this message:

> [NoteDatabaseRepository] depends on unregistered type [AppDatabase] from package:visual_notes/data/database/app_database.dart.
Did you forget to annotate the above class(s) or their implementation with @injectable?
or add the right environment keys?

my NoteDatabaseRepository:
```
@Injectable(as: NoteRepository)
class NoteDatabaseRepository implements NoteRepository{
  NoteDatabaseRepository({required this.database});

  final AppDatabase? database;

  @override
  Stream<List<Note>> getNotesFromDatabase() {
    return database!.noteDao.getNotes();
  }
```
the NoteRepository:
```
abstract class NoteRepository{
  Stream<List<Note>> getNotesFromDatabase();
}
```
i tried to create a module for the AppData class like this:
```
@module
abstract class DatabaseModule{
  @lazySingleton
  Future<AppDatabase> get appDatabase =>
      $FloorAppDatabase.databaseBuilder(kDatabaseName).build();
}
```
but i still get the same message, so what am i suppose to do here?

**Comment by leoshusar** [comment]
Hi, did you try to add `@preResolve` annotation to your module?
Like:
```dart
@module
abstract class DatabaseModule{
  @lazySingleton
  @preResolve
  Future<AppDatabase> get appDatabase =>
      $FloorAppDatabase.databaseBuilder(kDatabaseName).build();
}
```
You are currently registering `Future<AppDatabase>`, not the actual `AppDatabase`.

**Comment by Abdelrhman-Mahmoud96** [comment]
@leoshusar tried that but i still get the same error, i am also getting similar error which i think related to the AppDatabase class problem:

> [UseCaseAddNote] depends on unregistered type [NoteRepository] 

the generated code:
```
 await gh.lazySingletonAsync<_i3.AppDatabase>(() => databaseModule.appDatabase,
      preResolve: true);

  gh.factory<_i4.NoteRepository>(
      () => _i5.NoteDatabaseRepository(database: get<_i3.AppDatabase>()),
      registerFor: {_dev});

  gh.singleton<_i6.UseCaseAddNote>(
      _i6.UseCaseAddNote(noteRepository: get<_i4.NoteRepository>()),
      registerFor: {_dev});
```
i don't know what am i doing wrong here ?

**Comment by leoshusar** [comment]
Since you've added `preResolve`, you also need to change your configure call to `Future<void>`:
```dart
Future<void> configureDependencies() => $initGetIt(getIt);
```
and await it in your main (or wherever you are calling it):
```dart
void main() async {
  await configureDependencies();
  ...
}
```
Or did you try this already?

**Comment by Abdelrhman-Mahmoud96** [comment]
@leoshusar yes i tried that before, same result

**Comment by leoshusar** [comment]
Could you try to make a minimal repro project you would be able to share?

**Comment by Abdelrhman-Mahmoud96** [comment]
@leoshusar I'm reverting back to Get_It for now, but thank you for helping.
I will keep this open maybe someone would have used injectable with Floor before and tell us how they did it, because I think that there is a problem with the Floor package that injectable can't deal with.

**Comment by Manmapi** [comment]
Here my way to use Injectable with Floor 

```
part 'app_database.g.dart';
// ignore_for_file: depend_on_referenced_packages

@prod
@preResolve
@singleton
@Database(version: 1, entities: [Task, WatchData, HealthData, HeartRateData])
abstract class AppDatabase extends FloorDatabase {
  TaskDao get taskDao;
  WatchDao get watchDao;
  HealthDao get healthDao;
  HeartRateDao get heartRateDao;
  @factoryMethod
  static Future<AppDatabase> create() {
    return $FloorAppDatabase.databaseBuilder(Env.config.apiHost).build();
  }
}
```
