### ISSUE TITLE
FEATURE REQUEST: Add 2 annotations @preResolve + @factoryMethod

### ISSUE THREAD

**Issue by wer-mathurin** [Milad-Akarie/injectable#284]
I would expect

```
@Singleton(as: IConfigReader )
class ConfigReader extends IConfigReader {
@preResolve
@factoryMethod
static Future<ConfigReader> initialize() async {...}
...
}
```

to generate this
` await gh.singletonAsync<IConfigReader>(()  =>  ConfigReader.initialize(), preResolve: true);`

Or
Add a preResolve to
@FactoryMethod(preResolve: true)

**Comment by Milad-Akarie** [comment]
@wer-mathurin  done in version 2.0.0 
https://github.com/Milad-Akarie/injectable#factorymethod-and-postconstruct-annotations
https://github.com/Milad-Akarie/injectable#pre-resolving-futures
