### ISSUE TITLE
Trying to use retrofit with injectable

### ISSUE THREAD

**Issue by MHKalantarian** [Milad-Akarie/injectable#285]
I have encountered an error, I'm trying to inject Dio into Retrfit Client as a singleton and I can't seem to figure it out.

The error is:

    Expected a value of type 'Dio', but got one of type 'Null'

Here is my network module:

    @module
    abstract class NetworkModule {
      @Named('BaseUrl')
      String get baseUrl => 'https://test.com/api/';
    
      @lazySingleton
      Dio dio(@Named('BaseUrl') String url) => Dio(
          BaseOptions(baseUrl: url, headers: {'Content-Type': 'application/json'}));
    
      @preResolve
      Future<SharedPreferences> get prefs => SharedPreferences.getInstance();
    }

and here is my rest client:

    @injectable
    @singleton
    @RestApi()
    abstract class RestClient {
      @factoryMethod
      factory RestClient(@factoryParam Dio dio) = _RestClient;
    
      @POST('register')
      Future<User> register(@Body() User request);
    
      @POST('login')
      Future<User> login(@Body() User request);
    }

**Comment by leoshusar** [comment]
Hi, here is how I am doing it. I also have separate `abstract ArticleService` (the main point of dependency injection is to be able to switch your implementations registered under single interface), but your case should work too:
```dart
@Injectable(as: ArticleService)
@RestApi()
abstract class RestArticleService implements ArticleService {
  @factoryMethod
  factory RestArticleService(Dio dio) =>
    _RestArticleService(dio);
}
```

Also you cannot use both `@injectable` and `@singleton` - the `@injectable` already registers it as a factory.

Try to remove one of those annotations and the `@factoryParam`.

**Comment by MHKalantarian** [comment]
> Hi, here is how I am doing it. I also have separate `abstract ArticleService` (the main point of dependency injection is to be able to switch your implementations registered under single interface), but your case should work too:
> 
> ```dart
> @Injectable(as: ArticleService)
> @RestApi()
> abstract class RestArticleService implements ArticleService {
>   @factoryMethod
>   factory RestArticleService(Dio dio) =>
>     _RestArticleService(dio);
> }
> ```
> 
> Also you cannot use both `@injectable` and `@singleton` - the `@injectable` already registers it as a factory.
> 
> Try to remove one of those annotations and the `@factoryParam`.

Thank you, but where do you get the Dio object? I have custom options and don't want to use a default Dio

**Comment by leoshusar** [comment]
My Dio object is registered as a `@module` like yours, although I'm not using `lazySingleton`, but I guess this shouldn't be a problem:
```dart
abstract class RegisterModule {
  @singleton
  Dio dio(AppConfig config) {
    final dio = Dio()
      ..options.baseUrl = config.apiUrl;

    return dio;
  }
}
```

**Comment by MHKalantarian** [comment]
> My Dio object is registered as a `@module` like yours, although I'm not using `lazySingleton`, but I guess this shouldn't be a problem:
> 
> ```dart
> @module
> abstract class RegisterModule {
>   @singleton
>   Dio dio(AppConfig config) {
>     final dio = Dio()
>       ..options.baseUrl = config.apiUrl;
> 
>     return dio;
>   }
> }
> ```

Removing @singleton & @factoryParam resolved the issue. Thank you
