### ISSUE TITLE
[feature request] add annotation for service initialization

### ISSUE THREAD

**Issue by leoshusar** [Milad-Akarie/injectable#287]
I would love to have an annotation similar to [`@PostConstruct`](https://www.baeldung.com/running-setup-logic-on-startup-in-spring#1-the-postconstruct-annotation) in Java Spring.

My use case are services with `initialization` method, such as service which needs to load settings from internet.
It would look like this:

```dart
@Singleton(as: MyService)
class MyServiceImpl implements MyService {
  final RemoteService _remoteService;
  late final String _someData;

  const MyServiceImpl(this._remoteService);

  @postConstruct
  Future<void> initialize() async {
    _someData = await _remoteService.getData();
  }
}
```

My request is similar to #284, but I think this would be much better than creating service using static method like this:
```dart
@Singleton(as: MyService)
class MyServiceImpl implements MyService {
  final RemoteService _remoteService;
  late final String _someData;

  const MyServiceImpl(this._remoteService);

  @preResolve
  @factoryMethod
  static Future<MyService> create(RemoteService remoteService) async {
    final service = MyServiceImpl(remoteService);
    service._someData = await _remoteService.getData();
    return service;
  }
}
```

**Comment by naamapps** [comment]
+1

**Comment by Milad-Akarie** [comment]
@leoshusar done in version 2.0.0
https://github.com/Milad-Akarie/injectable#factorymethod-and-postconstruct-annotations
