### ISSUE TITLE
Issue with initialization of ObjectBox

### ISSUE THREAD

**Issue by JakubNeukirch** [Milad-Akarie/injectable#290]
Hi, I am having an issue with providing `Store` from `objectbox` library with module. While running `build_runner` i am getting error "type 'DynamicElementImpl' is not a subtype of type 'ClassElement' in type cast". When I remove providing of `Store`, build_runner succeeds.

Here is my module:
```
@module
abstract class RegisterModule {
  @lazySingleton
  @preResolve
  Future<Store> get store async {
    return await openStore();
  }
}
```

What else I can provide to make investigation easier?

**Comment by koraxis** [comment]
I have a similar issue with ObjectBox
