### ISSUE TITLE
Is it possible to make web only injection?

### ISSUE THREAD

**Issue by mirkancal** [Milad-Akarie/injectable#291]
I've separated the environments by web and mobile. Both my WebDownloader and MobileDownloader are registered as ImageDownloader(abstract class). But since WebDownloader's file has dart:js and dart:html imports, app throws:

`Error: Not found: 'dart:html'` errors

Is there any other way to make generated file doesn't import the file with web imports at all?

**Comment by leoshusar** [comment]
This has to be done compile time, you have 2 ways (afaik):
1) use conditional import, explained for example [here](https://www.reddit.com/r/FlutterDev/comments/kngr6h/import_package_only_when_user_is_running_web/)
2) create plugin, you will have a package for each platform you want to support with the platform specific code (can also be Dart only) and then one main package with the abstract interface. Compiler will then use the correct platform package.

First way is simpler for things like single class, but I think you will have to name those classes the same (you cannot have one named `Mobile` and the other `Web` I believe). With the second way wou'll have much more flexibility, but might be overkill for your need.

**Comment by mkysel** [comment]
use https://pub.dev/packages/universal_html?
