### ISSUE TITLE
What if we implemented multiple abstract classes?

### ISSUE THREAD

**Issue by SungilJung** [Milad-Akarie/injectable#294]
What if we implement multiple abstract classes?
I don't know how to proceed if the Test class implements A, B, C, D.

**Comment by svsk417** [comment]
Same for me. Seems like this is not supported. The only way around seems to use a module for that: 
```
@module
abstract class MyModule {
  @Singleton
  MyImplementation myImplementation() => return MyImplementation();
  
  @Singleton 
  MyFirstAbstractClass myFirstAbstractClass(MyImplementation myImplementation) => return myImplementation;
  
  @Singleton 
  MySecondAbstractClass mySecondAbstractClass(MyImplementation myImplementation) => return myImplementation;
}
```

**Comment by shtse8** [comment]
Same for me. I would like to see something like: (but currently not supported.)

```dart
@injectable
@asSelf
@as(InterfaceA)
@as(InterfaceB)
class Implementation implements InterfaceA, InterfaceB { }
```

**Comment by mitissen** [comment]
Is there any problem implementing something the suggestion of @shtse8 ? Or is there an argument against it?

Would be a elegant solution
