### ISSUE TITLE
Missing dependencies should cause an error instead of a warning

### ISSUE THREAD

**Issue by mateusfccp** [Milad-Akarie/injectable#303]
Currently, when the dependency tree has resolution problems, the code generation command throws a warning. Example:

```
[WARNING] injectable_generator:injectable_config_builder on bin/main.dart:
Missing dependencies in plugin_test/bin/main.dart

[A] depends on unregistered type [B] from package:package/src/file.dart

Did you forget to annotate the above class(s) or their implementation with @injectable? 
or add the right environment keys?
```

However, because it's thrown a warning instead of an error, the build command returns a success value (0).

When using this package in a CI/CD infrastructure, it would be much better if the build returned an error, so we could detect it at the compile time automatically.

Maybe you don't want to make this the default behavior, but we could have at least a way to configure `builder.yaml` so that this is the behavior.

**Comment by Milad-Akarie** [comment]
@mateusfccp I've included an optional flag in version 2.0.0
`@InjectableInit(throwOnMissingDependencies: true)`
