### ISSUE TITLE
What's the differences between Singleton and Injectable? Dependency Injection in Flutter - Type of declaration for the get_it/injectable package

### ISSUE THREAD

**Issue by alperefesahin** [Milad-Akarie/injectable#308]
I want to learn the differences between Singleton and Injectable declarations. I just know that the Singleton provides only one instance, and for the injectable, it provides a new instance when we use/call it, every time.

I tried to understand completely, but there are some things that I can not get it. I think I need one example for this.

I can give an example for it, and please share your knowledge and ideas with using the below example:

Example:

_**Let's assume we use firebase login with email and password. It does not matter what we use for state management. So, should it be singleton or injectable? I thought that we need to use injectable since for every login we need a new request for the service.**_

For the singleton (or lazySingleton) I can not give another example for this example, since I do not get it exactly. Please give me your knowledge to solve this problem. For what situation do we need lazysingleton or singleton?

Thanks

**Comment by svsk417** [comment]
Hi @alperefesahin,
you have to use a singleton everywhere, where you want to hold state information for the complete runtime of the app. 
This could be e.g. an access/refresh token pair. You would use a factory or injectable with things that need to be initialized freshly every time it is used. This could for instance be a bloc or cubit that gets initialized when the BlocProvider is creating it and destroyed when the BlocProvider is removed from the view.
