### ISSUE TITLE
get_it 4.0.0 needs a named "instanceName" argument

### ISSUE THREAD

**Issue by ResoDev** [Milad-Akarie/injectable#31]
Hello! I absolutely love the new changes. 

The get_it interface changed because of the possible factory parameters. While this code generated after using `@Named` was correct with pre-4.0.0 get_it
```dart
g.registerLazySingleton<LocalForecastCache>(() => HiveForecastCache(
      g<Box<List<ForecastDto>>>('weatherForecast')));
```
it should now use a named argument like this:
```dart
  g.registerLazySingleton<LocalForecastCache>(() => HiveForecastCache(
      g<Box<List<ForecastDto>>>(instanceName: 'weatherForecast')));
```

**Comment by Milad-Akarie** [comment]
@ResoDev  fixed in injectable_generator 0.3.1.
 waiting for the upcoming tutorial :D
