### ISSUE TITLE
[Feature] Inject the factory function itself instead of the class

### ISSUE THREAD

**Issue by naamapps** [Milad-Akarie/injectable#312]
Hey,
I tried injecting the factory function itself instead of the class like this:
```
final ProfileService Function({String? instanceName, dynamic param1, dynamic param2}) factoryFunc;

PoolManager(this.factoryFunc);
```
However this doesn't work when generating. throw this error:
`ProfileService Function({String instanceName, dynamic param1, dynamic param2}) is not a class element`

I expect the generator to inject the factory function like so in the $initGetIt function (Notice how the `get<ProfileService>` doesn't have closing parenthesis) - this will inject the factory func.
`gh.lazySingleton<PoolManager>(PoolManager(get<ProfileService>));`

Also when inject the factory func, the order of the initialization will be affected, like injecting the actual class.

Maybe also add a typedef for this factory function so it will be easier to read and write.

Why we need this feature?
When moving from C# to dart, in C# the DI can also inject the factory function itself from the get go.
This is needed when creating a pool of a service, so creating the service will be effortless - just call the factory func.
I know I can just call `locator<ProfileService>` inside PoolManager, but the ordering of the initializations can be a problem because Injectable generator doesn't know PoolManager uses this service at all.

Let me know your thoughts,
And please advise on alternatives if you can.

Thanks

**Comment by Milad-Akarie** [comment]
@naamapps first things first, I this doable using `get_it`?

**Comment by naamapps** [comment]
Actually I didn't check if it's possible with get_it, I'll do it and get back to you
