### ISSUE TITLE
Update injectable_generator to Analyzer 5.2.0

### ISSUE THREAD

**Issue by guyluz11** [Milad-Akarie/injectable#315]
Please update `injectable_generator` package `analyzer` dependency to version `5.2.0`

Getting conflict with other packages like freezed 

```
Running "flutter pub get" in vernet...                          
Because no versions of injectable_generator match >1.5.4 <2.0.0 and injectable_generator 1.5.4 depends on analyzer ^4.0.0, injectable_generator ^1.5.4 requires analyzer ^4.0.0.
And because freezed >=2.2.1 depends on analyzer ^5.2.0, injectable_generator ^1.5.4 is incompatible with freezed >=2.2.1.
So, because vernet depends on both freezed ^2.2.1 and injectable_generator ^1.5.4, version solving failed.
pub get failed (1; So, because vernet depends on both freezed ^2.2.1 and injectable_generator ^1.5.4, version solving failed.)

```

 Thanks.

**Comment by naamapps** [comment]
@Milad-Akarie Now that #310 is merged, please release a version to pub.dev

**Comment by Milad-Akarie** [comment]
@naamapps done, sorry for the delay, I was in hurry I released injectable instead injectable_generator.

**Comment by naamapps** [comment]
@Milad-Akarie New version is still not released.

**Comment by dustincatap** [comment]
It seems that the version 1.5.4 from pub.dev does not include the change for selecting the newer analyzer version

![image](https://user-images.githubusercontent.com/56006524/200151307-cbcb950d-c27d-45f3-9eb0-9f5e1cf1bafe.png)


For the meantime, use:

```yml
injectable_generator:
  git:
    url: https://github.com/amondnet/injectable.git
    path: injectable_generator
```
