### ISSUE TITLE
Incompatible version injectable_generator in pub.dev

### ISSUE THREAD

**Issue by sachebotarev** [Milad-Akarie/injectable#316]
Hi @Milad-Akarie 
In master branch and pub.dev for package injectable pubspec.yaml  file has version analyzer: ">=4.6.0 <6.0.0"
But injectable_generator in pub.dev in pubspec.yaml  file has  still  version analyzer: ^4.0.0 
(In master branch  of injectable_generator version already - analyzer: ">=4.6.0 <6.0.0")

Please, update injectable_generator on pub.dev

**Comment by Milad-Akarie** [comment]
I really thought I pushed it, how none said anything until now? 
updated to 1.5.5
