### ISSUE TITLE
[Feature] PreResolve Async Singleton

### ISSUE THREAD

**Issue by Jozott00** [Milad-Akarie/injectable#319]
First of all, thanks for the great package!

## Problem

If you want to define a singleton that cannot be constructed synchronously, then you can define the following  
```dart
@singleton
class Database {

  @factoryMethod
  static Future<Database> create() async {...}
}
```

The problem with this is that all constructors that depend on `Database` must call getIt async with `await get.getAsync<Database>()` so that they are also async. 

One workaround for this, is to use the `@module` annotation with `@preResolve`, which awaits the factoryMethod and defines a synchronous singleton.
```dart
@module
abstract class RegisterDatabase {

  @preResolve
  @singleton
  Future<Database> get database => Database.create();
}
```

## Solution

It would be great if we could use the `@preResolve` annotation on factory methods:
```dart
@singleton
class Database {

  @preResolve
  @factoryMethod
  static Future<Database> create() async {...}
}
```
So the singleton is created in the same way as it is when using `@module` with `@preResolve`.

**Comment by Jozott00** [comment]
This issue is a duplication of #284 and #287, so I will close this issue.

**Comment by Milad-Akarie** [comment]
done in version 2.0.0
https://github.com/Milad-Akarie/injectable#factorymethod-and-postconstruct-annotations
https://github.com/Milad-Akarie/injectable#pre-resolving-futures
