### ISSUE TITLE
The method 'init' isn't defined for the type 'GetIt'.

### ISSUE THREAD

**Issue by RizanPSTU** [Milad-Akarie/injectable#326]
I am getting this error. init function is not defined in the getit

<img width="862" alt="Screenshot 2022-11-24 at 10 06 46 PM" src="https://user-images.githubusercontent.com/32144390/203827531-f44ba22f-a8c9-4670-a2eb-1c5c2dcd693b.png">

My get it and injectable version
<img width="599" alt="Screenshot 2022-11-24 at 10 08 04 PM" src="https://user-images.githubusercontent.com/32144390/203827655-153bf7d4-6133-4b3e-8179-192da08401e2.png">

**Comment by Milad-Akarie** [comment]
asExtension should be true

**Comment by devkaio** [comment]
> asExtension should be true

Same problem.

```dart
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

final getIt = GetIt.instance;

@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: true,
)
void configureDependencies() => getIt.init();
```
![image](https://user-images.githubusercontent.com/3959419/203849783-bc58416b-bfcc-4b33-9710-bb45b55bf136.png)

**Comment by Milad-Akarie** [comment]
Annotate at least one injectable class for the method yo get generated

**Comment by RizanPSTU** [comment]
asExtension  = true
At least one injectable class for the method.
Also add import 'injection.config.dart';

Worked now
