### ISSUE TITLE
Order of micro package

### ISSUE THREAD

**Issue by kennir** [Milad-Akarie/injectable#327]
Hi

I want to initialize the main package first and then the micro package, because app (main package) should provide some strings for micro package.

Perhaps we could add an option to control the order between the main and the micro package ?

**Comment by Milad-Akarie** [comment]
@kennir   done in version 2.1.0 make sure you upgrade the generator as well

you can now do something like this
```dart
@InjectableInit(  
  externalPackageModulesBefore: [  
  ExternalModule(AwesomePackageModule),  
  ExternalModule(ThirdPartyMicroModule),  
 ],  
 externalPackageModulesAfter: [  
  ExternalModule(CoolPackageModule),  
 ],)  
void configureDependencies() {}
```

**Comment by kennir** [comment]
@Milad-Akarie Wow, What a quick response, Thank you very much
