### ISSUE TITLE
Can microPackage be scoped?

### ISSUE THREAD

**Issue by Ne0n11** [Milad-Akarie/injectable#329]
can microPackage be scoped? And also, When you use scoped InjectableInit, why list of Modules imports doesn't affect anything.

**Comment by Milad-Akarie** [comment]
@Ne0n11 for the time being it does not.
I didn't understand the second part of your question. 

how do you imagine microPackages scope support to be?

**Comment by Ne0n11** [comment]
So, let's say we have:
1) Module, that contains service, we would like to use.
```
class LocationPackageModule extends _i1.MicroPackageModule {
  /// initializes the registration of main-scope dependencies inside of [GetIt]
  @override
  _i2.FutureOr<void> init(_i1.GetItHelper gh) {
    gh.lazySingleton<_i3.LocationService>(
      () => _i3.LocationService(),
      dispose: (i) => i.onDispose(),
    );
  }
}
```

2) InjectableScope for delivery screen:
```
_i1.GetIt initDeliveryScope(
  _i1.GetIt getIt, {
  _i1.ScopeDisposeFunc? dispose,
}) {
  return _i2.GetItHelper(getIt).initScope(
    'delivery',
    dispose: dispose,
    init: (_i2.GetItHelper gh) {
      gh.lazySingleton<_i3.DeliveryRepository>(() => _i3.DeliveryRepository());
      gh.factory<_i5.DeliveryCubit>(() => _i5.DeliveryCubit(
            gh<_i3.DeliveryRepository>(),
            gh<_i4.LocationService>(),
          ));
    },
  );
}
```

So, I would like to supply LocationModule for my DeliveryScope iniitializer,so then inside init for the scope - first module initialize, then scope, with all scoped dependencies.

And after that, when I go to delivery page, I would start scope in initState and popIt in dispose. Hope that makes sense)

**Comment by Milad-Akarie** [comment]
@Ne0n11 so the scope initializing is triggered by the root package then the scoped module will be called inside of it.

```dart
_i1.GetIt initDeliveryScope(
  _i1.GetIt getIt, {
  _i1.ScopeDisposeFunc? dispose,
}) {
  return _i2.GetItHelper(getIt).initScope(
    'delivery',
    dispose: dispose,
    init: (_i2.GetItHelper gh) {

   // the module will be initialized her!

      gh.lazySingleton<_i3.DeliveryRepository>(() => _i3.DeliveryRepository());
      gh.factory<_i5.DeliveryCubit>(() => _i5.DeliveryCubit(
            gh<_i3.DeliveryRepository>(),
            gh<_i4.LocationService>(),
          ));
    },
  );
}
```

**Comment by Ne0n11** [comment]
Yeah, if that is possible

**Comment by Milad-Akarie** [comment]
How does this look? 

```dart
@InjectableInit(
  externalPackageModulesBefore: [
    ExternalModule(LocationPackageModule, scope: 'delivery'),
  ],
)
void configInjection(){}
```

**Comment by Ne0n11** [comment]
It looks ok, maybe could be even without specifing scope, but that is up to you.

**Comment by Milad-Akarie** [comment]
how would injectable know the target scope then?

**Comment by Ne0n11** [comment]
I mean, that module would be completely separate, so whenever you find externalPackages specified for scoped InjectableInit, you just put that module in, no?

**Comment by Milad-Akarie** [comment]
@Ne0n11 the ExternalModule itself has no scope information, so you need to specify what scope you needed in in the root package

**Comment by Milad-Akarie** [comment]
@Ne0n11  done in version 2.1.0 make sure you upgrade the generator as well
