### ISSUE TITLE
Generating Mockito classes

### ISSUE THREAD

**Issue by sterrenburg** [Milad-Akarie/injectable#33]
Hello, `v0.3.0` is working great!

Would it be possible to generate Mockito classes using `injectable`?

Currently, I am creating Mock classes ad hoc in the test file. This is an example of the abstract injectable class `MyService`.

```dart
// * my_service.dart

@prod
@injectable
abstract class MyService {
@factoryMethod
factory MyService.fromImplementation() => SomeImplementation();

Future<void> doSomething();
}
```

```dart
// * some_test_using_my_service.test.dart

class MockMyService extends Mock implements MyService {}

void main() {
MyService mockMyService;

setUp(() {
mockMyService = MockMyService();
}

...
}
```
I would like to inject the mock class in the test environment, so that it is reusable in other tests. We could simply copy the mock class into every test, but I bet we can save a few key strokes.

I tried by adding a factory method like so:
```dart
@injectable
abstract class MyDependency {
@factoryMethod
factory MyDependency.fromImplementation() => SomeImplementation();

@factoryMethod
factory MyDependency.fromMock() => MockMyDependency();

Future<void> doSomething();
}
```
Is it possible to annotate these factory methods with `@prod` and `@dev`?

This idea feels wrong since we need to import Mockito and the mock class into `my_service.dart`.

Can you think of a good way to generate the mock classes and add them to the test environment?

**Comment by Milad-Akarie** [comment]
@sterrenburg excuse my delay I thought this was an old issue.
Anyways.. this's what I would do
```dart
@injectable
class BackendService {}

@RegisterAs(BackendService, env: 'test')
@injectable
class BackendServiceMock extends Mock implements BackendService {}
```
Generated code 

```dart
g.registerFactory<BackendService>(() => BackendService());

  //Register test Dependencies --------
  if (environment == 'test') {
    g.registerFactory<BackendService>(() => BackendServiceMock());
  }
```

Is this what you're looking for?

**Comment by dricholm** [comment]
@Milad-Akarie 
I tried out your above method, but for it to work I have to declare the mock class in the same file as the normal implementation. So it would go into the lib folder. But that also means we would have to import mockito inside the lib folder. According to the [Dart website](https://dart.dev/tools/pub/dependencies#dev-dependencies):

> The rule for deciding between a regular or dev dependency is simple: If the dependency is imported from something in your lib or bin directories, it needs to be a regular dependency. If it’s only imported from test, example, etc. it can and should be a dev dependency.

This way it will affect the production builds too if I understand correctly. At least the built apk files were different.

For now I just declare the Mock classes inside the test folder and write tests without using injectable for it. Do you have any other recommended ways for this?

**Comment by sterrenburg** [comment]
I haven't tried as of late, but I ran into the same problems with the `lib` directory. 

For now, I still declare local Mock classes so there are no funky dependencies in the test files. Especially relative import paths (which sometimes seem necessary in the `test/` directory) caused some issues with `injectable`.

**Comment by Milad-Akarie** [comment]
hmmmmm @sterrenburg @dricholm  What do you guys suggest? 
would making another configureTestDependencies method that only registers deps inside of the the test folder be good enough? 
something like 

```dart
@InjectableInit(generateFor:['test'])
void configure() {
  $initGetIt(getIt);
}
```

**Comment by sterrenburg** [comment]
> hmmmmm @sterrenburg @dricholm What do you guys suggest?
> would making another configureTestDependencies method that only registers deps inside of the the test folder be good enough?
> something like
> 
> ```dart
> @InjectableInit(generateFor:['test'])
> void configure() {
>   $initGetIt(getIt);
> }
> ```

That seems like a good approach. 

What I have been doing is calling a `setUpAllForTest` function before every test that uses injectable classes, like this:

```dart
// <project_root>/test/test_dependency_injection.dart

Future<void> setUpAllForTest() async {
  setUpAll(() async {
    await configure(Environment.test);
    TestWidgetsFlutterBinding.ensureInitialized();
  });
}
```

The caveat with this approach is that test files import this file only via relative path (e.g. `import '../../../../test_dependency_injection.dart';`). Not sure if this is a problem on my side, the dart ecosystem or Injectable.

**Comment by dricholm** [comment]
@Milad-Akarie Thank you for the response! That could maybe work. I tried out how it would look. So I created a file in the test folder. 

test/test_injection.dart:
```dart
import './test_injection.iconfig.dart';

final GetIt getIt = GetIt.instance;

@RegisterAs(AuthRepository, env: Environment.test)
@lazySingleton
class MockAuthRepository extends Mock implements AuthRepository {}

@RegisterAs(RegisterBloc, env: Environment.test)
@injectable
class MockRegisterBloc extends MockBloc<RegisterEvent, RegisterState>
    implements RegisterBloc {}

@injectableInit
void configureInjection(String environment) {
  $initGetIt(getIt, environment: environment);
}
```

So when I run the build_runner, this will cause it to create an additional iconfig file: one for the lib and one for the test folder. For now it of course includes every environment in both files. If I understood you correctly the proposal would change that and only include the correct one for each file.

However when importing from the test folder it now uses different paths: `import 'asset:app_pkg/test/test_injection.dart';` so this would have to be relative inside the test folder: `import './test_injection.dart';`.

In this case does [overwriting registrations](https://pub.dev/packages/get_it#overwriting-registrations) work? Or does it have to be enabled from injectable. 

Also if testing the actual class would the registration need to be manually overwritten for example in the `setUp()` part of the test and then retrieved from the injector? Or should the class be created manually and just use the injector for the dependencies?

**Comment by sterrenburg** [comment]
> Also if testing the actual class would the registration need to be manually overwritten for example in the setUp() part of the test and then retrieved from the injector? Or should the class be created manually and just use the injector for the dependencies?

I have been wondering about this as well. What kind of works is providing an optional constructor parameter like this:

```dart
// api_repository_impl.dart
@prod
@singleton
@RegisterAs(ApiRepository)
class ApiRepositoryImpl implements ApiRepository {
  ApiRepositoryImpl([ApiDataSource apiDataSource])
      : _apiDataSource = apiDataSource ?? getIt<ApiDataSource>();

  final ApiDataSource _apiDataSource;
```

It's quite a lot of manual boilerplate, but now you can test like this:

```dart
// api_repository_impl_test.dart

class MockApiDataSource extends Mock implements ApiDataSource {}

void main() async {
  await setUpAllForTest();

  ApiRepositoryImpl apiRepository;
  ApiDataSource mockApiDataSource;

  setUp(() {
    mockApiDataSource = MockApiDataSource();
    apiRepository = ApiRepositoryImpl(mockApiDataSource);
  });

  ...
```

The good: you can easily test and mock any class.
The bad: this still has a mock class local to the file.

**Comment by Milad-Akarie** [comment]
@sterrenburg @dricholm I added the implementation we discussed before, can you guys check it out and share your thoughts? 

`@InjectableInti(generateForDir:['test]):`

 // generateForDir defaults to ['lib','bin']
```
injectable: 0.4.0
injectable_generator: 0.4.0
```

**Comment by aashir-khan** [comment]
Hey there, I tried out 0.4.0, here's what I found from my attempt:

Trying to do:

```dart
// test/test_injection.dart
@InjectableInit(generateForDir: ['test'])
void configureTestInjection() => $initGetIt(getIt);

final GetIt getIt = GetIt.instance;

@lazySingleton
@Injectable(as: DataConnectionChecker)
class MockDataConnectionChecker extends Mock implements DataConnectionChecker {}
```

generates

```dart
void $initGetIt(GetIt g, {String environment}) {
  g.registerLazySingleton<MockDataConnectionChecker>(
      () => MockDataConnectionChecker());
}
```

Which is incorrect as it should be

```dart
void $initGetIt(GetIt g, {String environment}) {
  g.registerLazySingleton<**DataConnectionChecker**>(
      () => MockDataConnectionChecker());
}
```

On the other hand if I use the deprecated RegisterAs syntax 

```dart 
@RegisterAs(DataConnectionChecker)
```

Then it generates the correct code

The way I'm using this in my test is like:

```dart
import 'package:data_connection_checker/data_connection_checker.dart';
import 'package:my_package/path/to/network_info_impl.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';

import '../../test_injection.dart';

void main() {
  setUpAll(() async {
    configureTestInjection();
    TestWidgetsFlutterBinding.ensureInitialized();
  });

  group('isConnected', () {
    test('should forward the call to DataConnectionChecker.hasConnection', () async {
      // arrange
      final mockDataConnectionChecker = getIt<DataConnectionChecker>();
      final networkInfo = NetworkInfoImpl(mockDataConnectionChecker);
      final tHasConnectionFuture = Future.value(true);

      when(mockDataConnectionChecker.hasConnection).thenAnswer((_) => tHasConnectionFuture);

      // act
      final result = networkInfo.isConnected;

      // assert
      expect(result, tHasConnectionFuture);
    });
  });
}
```

Which works!

**Comment by Milad-Akarie** [comment]
Hey @aashir-khan Singleton and LazySingleton are sub types of injectable, so what you need to use is
@LazySingleton(as: Type) instead of @Injectable(as:...)

**Comment by aashir-khan** [comment]
Ahh I see, yes that works, hmm I didn't see `LazySingleton` in the API reference except in the context of something called signalsReady. The example previous to the example was speaking about signalsReady but then the example with LazySingleton was in the same sentence after that so it wasn't clear what exactly LazySingleton was, I see what it does now, thanks

**Comment by Milad-Akarie** [comment]
Ya I guess that wasn't documented properly.

**Comment by sterrenburg** [comment]
This looks promising! Haven't tried it out yet, but sounds like a good solution.

> I wonder if there is a way to automate even dependency injection for the class you are trying to test (in my case NetworkInfoImpl -> used in dev and prod env) rather than instantiating the class yourself

Regarding this, I've had success by providing an optional constructor parameter like so:

```dart
// api_repository_impl.dart
@prod
@singleton
@RegisterAs(ApiRepository)
class ApiRepositoryImpl implements ApiRepository {
  ApiRepositoryImpl([ApiDataSource apiDataSource])
      : _apiDataSource = apiDataSource ?? getIt<ApiDataSource>();

  final ApiDataSource _apiDataSource;
```

This approach works for me by _not_ assigning a constructor parameter, leading to the getIt instance of whichever dependency the class needs.

**Comment by dricholm** [comment]
@Milad-Akarie I also tried 0.4.0, it now correctly generates lib and test codes separately. Thank you!

I also noticed most annotations have CamelCase classes and a lowercase const also. Since adding parameters to them needs the class variant I wanted to replace everything to use the classes, but some annotations do not have classes visible from outside the `injectable_annotations.dart` (e.g. `RegisterModule()`, `FactoryMethod()`). Which is the recommended use? I guess it does not seem to matter which is used, right?

@sterrenburg I wanted to try your method of optional constructor parameters. It works okay when building and running the app, but in case of tests the constructor always got null as parameter it seems. Could it be somehow because of imports? Now there are two `injection.iconfig.dart` files: one in lib and one in test. GetIt should be a singleton, so I am not sure. I use package imports inside lib and relative imports inside test folders.

**Comment by Milad-Akarie** [comment]
Hey @sterrenburg 
first of all.. RegisterAs is deprecated now you should switch to using the as property inside of injectable or it's subs.

```dart
@Singleton(as: ApiRepository)
class ApiRepositoryImpl implements ApiRepository { }
```
I'm not sure about the second part but if you register `ApiDataSource` under prod env and you don't pass the env key to the main initGetIT function then it won't be registered. 

so basically what I'm thinking is finding a way to call both

```
configureMainDeps(Env.test)
configureTestDeps()
```
in your setupAll() method

**Comment by Milad-Akarie** [comment]
Hey @dricholm The docs says we should be using  lower camel cased constants if we're not passing any parameters and use the class constructor if we have parameters to pass.  

I should've deprecated the lower cased constants so avoid confusion.

**Comment by sterrenburg** [comment]
> @sterrenburg I wanted to try your method of optional constructor parameters. It works okay when building and running the app, but in case of tests the constructor always got null as parameter it seems. Could it be somehow because of imports? Now there are two injection.iconfig.dart files: one in lib and one in test. GetIt should be a singleton, so I am not sure. I use package imports inside lib and relative imports inside test folders.

I haven't experienced the dependencies being `null` that I can remember, but that's mostly because the getIt instances are only used in `prod` for me. My tests still use the "manual" method without any `test` environment ([like this](https://github.com/sterrenburg/flutterhole/blob/81bcea4fdf95a76842c46c8cc54c968678cef196/test/features/pihole_api/data/repositories/api_repository_impl_test.dart#L22-L33)). I couldn't get the injectable mockito classes working from within the `test` directory, so this manual approach works OK-ish.

> Hey @sterrenburg
first of all.. RegisterAs is deprecated now you should switch to using the as property inside of injectable or it's subs.

Thank you for the reminder! This snippet was from `v0.3.5`, but it should be altered for the new interface.
