### ISSUE TITLE
Name of MicroPackageModule contains "_" (is not pascal case)

### ISSUE THREAD

**Issue by jtdLab** [Milad-Akarie/injectable#332]
Hey when using the micropackages feature from a package called `foo_bar_baz` the generated MicroPackageModule is named `Foo_bar_bazPackageModule` which is not a good dart class name. The generated class should be named with pascal case so its `FooBarBazPackageModule`.  Using latest injectable + injectable_generator

**Comment by Milad-Akarie** [comment]
fixed in injectable_generator 2.1.3
