### ISSUE TITLE
preferRelativeImports: true Does not work

### ISSUE THREAD

**Issue by botty87** [Milad-Akarie/injectable#345]
Using the previous version (1.#.#) the generated config.dart has the relative imports. With the current version it does not work, it never creates relative imports.

**Comment by nickesk** [comment]
I am also seeing this behavior, and it's preventing me from using injectable in my test directory, as it generates absolute imports of the form:
```dart 
import '/myPackage/test/mocks/mock_user_repo.dart' as _i4;
```
Which is not a valid path.

**Comment by khalilyamoun** [comment]
> I am also seeing this behavior, and it's preventing me from using injectable in my test directory, as it generates absolute imports of the form:
> 
> ```dart
> import '/myPackage/test/mocks/mock_user_repo.dart' as _i4;
> ```
> 
> Which is not a valid path.

My team is currently facing the same issue in test/ directory.

![image](https://user-images.githubusercontent.com/10196307/223105094-d85fb828-8019-4c63-9817-03e7a8101d86.png)

**Comment by justinschier** [comment]
This is also an issue for me - I need relative imports to work so that I con configure a different injection config for my test environment.
