### ISSUE TITLE
Feature: add ability to annotate top-level functions

### ISSUE THREAD

**Issue by bytes7bytes7** [Milad-Akarie/injectable#349]
Can you add ability to annotate top-level functions? Because there is at least one case when I need it:
```dart
void registerMappers(Mapster mapster) {
  _mapster
    ..register(
      MapperMeta.one(UserToUserResponseMapper.new),
    )
    ..register(
      MapperMeta.three(UserUserPostToLikedPostNotification.new),
    );
}
```
This method should be called when program starts (in get_it `init()` method).
I can suggest `setup`, `topLevel`, `setupMethod` annotations for this case.

**Comment by Milad-Akarie** [comment]
@bytes7bytes7 registering functions is not yet supported by get_it, I'll see if I can work around it.
