### ISSUE TITLE
How to inject dependencies in a flutter multi module project

### ISSUE THREAD

**Issue by VNAPNIC** [Milad-Akarie/injectable#351]
I have created a project with clean architecture and I have 2 modules in it, domain and data:

```cmd
mainProject
  - dataModule
  - domainModule
  lib
```

I'm using the injectable package to implement the dependency injection but I don't know if there is a way to implement dependency injection in this structure.

**Comment by svsk417** [comment]
We did so. You can just use a micropackage: 
Place this into your dataModule within a file named data.dart and in your domain module within a file named domain.dart, which will lead to the generation of data_module.dart and a domain_module.dart respectively
```dart
@InjectableInit.microPackage()
initMicroPackage() {}
```
Then within your lib, where the DI is setup, you can do like: 
```dart
@InjectableInit(
    initializerName: 'init',
    preferRelativeImports: true,
    includeMicroPackages: false,
    asExtension: true,
    externalPackageModulesBefore: [ExternalModule(DataModule), ExternalModule(DomainModule)])
Future<void> configureDependencies(String environment) async {
  await getIt.init(environment: environment);
}
```
