### ISSUE TITLE
Trouble with using @InjectableInit.microPackage()  

### ISSUE THREAD

**Issue by juskek** [Milad-Akarie/injectable#355]
Hi there! Great package I'm loving it

I have the following folder structure:
```
/
- lib/
    - ioc/
        - container.dart
- packages/
    - package_one/
        - lib/
            - package_one.dart
```

Was just trying to use @InjectableInit.microPackage() to register package_one, and tried to follow the example in this [issue](https://github.com/Milad-Akarie/injectable/issues/351)
<details>
<summary>Code example</summary>

```dart
// lib/ioc/container.dart
final getIt = GetIt.instance;

@InjectableInit(
  initializerName: r'$initGetIt', // default
  preferRelativeImports: true, // default
  includeMicroPackages: true,
  asExtension: false, // default
  externalPackageModules: [],
)
void configureDependencyInjection(String environment) =>
    $initGetIt(getIt, environment: environment);

```

```dart
// packages/package_one/package_one.dart

library package_one

// export statements

@InjectableInit.microPackage()
initMicroPackage() {} // will not be called but needed for code generation 
```
</details>

However, when I run build_runner a PackageOneModule file is not generated. Am I approaching this wrong?

**Comment by Milad-Akarie** [comment]
@juskek build_runner needs to run for each package -> you have to be in /package_one directory when you run it
