### ISSUE TITLE
[feature] Add a possibility to instantiate the constructor with default parameters

### ISSUE THREAD

**Issue by bambinoua** [Milad-Akarie/injectable#358]
For example I have a class:
```dart
@injectable
class Thing {
  Thing({this.id, this.name = ''})

  final int? id;
  final String name;
}
```
The generated code is:
```dart
gh.factory<_1.Thing>(() => Thing(
  id: gh.get<int>(),
  name: gh.get<String>(),
));
```
But I need just a cretion by default (without parameters initialization), i.e.
```dart
gh.factory<_1.Thing>(() => Thing());
```

Is it possible to add a boolean to `@Injectable` which allows to choose how to generate the factory?

**Comment by Milad-Akarie** [comment]
It would be cleaner to have a named construct with the default values 
e.g

@factoryMethod // tell injectable to use this construct
Thing.default(): name = '';

**Comment by bambinoua** [comment]
The better way is:
```dart
class Thing {
  Thing({this.code = ''});

  final String code;

  @factoryMethod
  Thing.builder() : this();
}
```
