### ISSUE TITLE
example "awesome.module.dart" getting pulled into injection.config.dart during build runner generation

### ISSUE THREAD

**Issue by jmandawg** [Milad-Akarie/injectable#363]
During config generation for some reason the "awesome.module.dart" module is getting pulled into our config.dart as an import:

```
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

// ignore_for_file: unnecessary_lambdas
// ignore_for_file: lines_longer_than_80_chars
// coverage:ignore-file

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:awesome/awesome.module.dart' as _i3;
import 'package:get_it/get_it.dart' as _i1;
import 'package:injectable/injectable.dart' as _i2;
```

If we delete the example file from the pub_cache it works like normal:

`rm -rf .pub-cache/hosted/pub.dev/injectable-2.1.1/example/`

Injectable 2.1.1
flutter 3.10.2

**Comment by anggaaryas** [comment]
same. i get this error in CI CD. so frustating to find where awesome package it is. But i cant produce in my pc

**Comment by Milad-Akarie** [comment]
@jmandawg @anggaaryas I have no idea why this's happening but I removed the micro-package from example folder, so things should be okay now?

**Comment by jmandawg** [comment]
Thanks let me know when you push a new release and i will test it.  
I do have my .pub-cache located in the project root directory so not sure if that is causing it to get scanned somehow:

`export PUB_CACHE="$(pwd)/.pub-cache"`

**Comment by anggaaryas** [comment]
> @jmandawg @anggaaryas I have no idea why this's happening 

same. hmm maybe it is build runner's bug, not this library bug 🤔 . my current solution is downgrade to 1.5.3

**Comment by Milad-Akarie** [comment]
@jmandawg @anggaaryas injectable 2.1.2 does not has the micro-package 'awesome' in it's example folder

**Comment by jmandawg** [comment]
@Milad-Akarie it looks like the issue is here:

https://github.com/Milad-Akarie/injectable/blob/master/injectable_generator/lib/generators/injectable_config_generator.dart#L94

`
if (!isMicroPackage && includeMicroPackages) {
      await for (final match
          in Glob('**.module.dart', recursive: true).list()) {
        final commentAnnotation = File(match.path).readAsLinesSync().first;
`

The problem is if .pub-cache folder is in the same directory as you are running build-runner in it will find all modules.dart.  
Maybe it would make more sense to use (untested):

`Glob('${generateForDir}/**.module.dart', recursive: true)`

so it only scans the directory you want generated for.
