### ISSUE TITLE
Migrate injectable_generator to Dart 3.0

### ISSUE THREAD

**Issue by tungpham6195** [Milad-Akarie/injectable#364]

**Comment by tungpham6195** [comment]
> Hi @tungpham6195 I can see that it is compatible, ![image](https://user-images.githubusercontent.com/9304740/241899571-5779053c-1a67-4a7f-baeb-9a27e10737a5.png)
> 
> Can you elaborate on what else is missing?

Hi @guyluz11 , the generator is throwing an error about the new syntax of [switch](https://dart.dev/language/branches#switch-expressions) while running through the dart file which contains them

for example:
![Screenshot 2023-05-30 at 16 50 58](https://github.com/Milad-Akarie/injectable/assets/22440318/3081dba4-829a-4276-91b8-a7b72c7712df)
![Screenshot 2023-05-30 at 16 51 18](https://github.com/Milad-Akarie/injectable/assets/22440318/3613421e-6efc-4b33-b8d8-cd9c85284d31)

**Comment by Milad-Akarie** [comment]
@tungpham6195 just tested this and it seems to work, try overriding build_runner version  to 2.4.4 and see if you still get the error?

**Comment by Milad-Akarie** [comment]
@tungpham6195 I updated the dart constrains to   ">=2.17.0 <4.0.0" in version 2.1.6
close the issue if this fixes your problem

**Comment by tungpham6195** [comment]
@Milad-Akarie thanks, i think the problem is at my side, because of cached .dart_tool is mixup with dart dart 2.0 so it throws that error. It works very well after i ran `flutter clean` command

**Comment by Milad-Akarie** [comment]
@tungpham6195 I needed to upgrade the constrains anyways.
it's safe to close I guess
