### ISSUE TITLE
dynamic is not a class element

### ISSUE THREAD

**Issue by nkrmr** [Milad-Akarie/injectable#368]
Hi,

I tried to install this repository: https://github.com/fikretsengul/flutter_advanced_boilerplate

But when I launch the app, I have this error that seems to come from injectable : 

<img width="1088" alt="Screenshot 2023-05-31 at 16 26 35" src="https://github.com/fikretsengul/flutter_advanced_boilerplate/assets/686395/1cf00b5d-4963-486d-8af5-5b3ad190e4d3">

My Flutter config is

<img width="819" alt="Screenshot 2023-05-31 at 16 27 16" src="https://github.com/fikretsengul/flutter_advanced_boilerplate/assets/686395/045951c6-bd2c-4919-b3a9-ba0a592dbfb8">

I'm on Mac os 13.4

Do you have any idea what's going on?

Best regards,

**Comment by BradyEdgar94** [comment]
Any help for others getting this issue? Would be good to add why you stopped contributing to this thread.
