### ISSUE TITLE
Dependency in external module

### ISSUE THREAD

**Issue by lpickford-pixelbeard** [Milad-Akarie/injectable#380]
Is it possible to pass a dependency into an external module? My use case is as follows:

- Commons logic between multiple apps is abstracted into an independent package
- The "commons" package uses `@InjectableInit.microPackage()`
- The "commons" package requires the implementing app to provide a config to properly instantiate, with a module in the "commons" package such as:
```
@module
abstract class ExampleModule {
  @preResolve
  Future<Config> get example => getIt<Config>();
}
```
- The implementing app register a `Config` in a module such as:
```
@module
abstract class ConfigModule {
  @preResolve
  Future<Config> get config async =>
      Config();
}
```

Is there a way I can have the `Config` from the implementing app instantiated to be consumed by the "commons" package?

**Comment by aleexam** [comment]
Same question
