### ISSUE TITLE
Environments do not work when using scopes

### ISSUE THREAD

**Issue by meg4cyberc4t** [Milad-Akarie/injectable#386]
Hi.
In my project, I use two scopes as two steps of loading the application: "SplashServices" (loading on the native splash screen) and "Services" (loading on the animated flutter screen). As a result, after generation, I get two functions:
```dart
Future<_i1.GetIt> initSplashServicesScope(
  _i1.GetIt getIt, {
  _i1.ScopeDisposeFunc? dispose,
})...

_i1.GetIt initServicesScope(
  _i1.GetIt getIt, {
  _i1.ScopeDisposeFunc? dispose,
})...
```

I also use environments to separate working and test implementations of classes, for example:

```dart
gh.singleton<_i25.AuthRepository>(
    _i26.AuthRepositoryImpl(gh<_i21.AuthRemoteDataSource>()),
    registerFor: {
      _release,
      _debug,
    },
  );
gh.singleton<_i25.AuthRepository>(
  _i27.MockAuthRepository(gh<_i6.Faker>()),
  registerFor: {_mock},
);
```

But the argument for environments for scopes functions is not registered.

I use initialization only in two scopes, so I don't have a common init function.
But if I want to register a class outside of the scopes, the init function is registered with the desired parameter "environment".

```dart
_i1.GetIt init(
  _i1.GetIt getIt, {
  String? environment,
  _i2.EnvironmentFilter? environmentFilter,
})
```

If you do not register classes without scopes, the init function will not be registered accordingly :(.

My question is: **Am I doing what I'm doing right?** Or is it a builder's mistake? It won't be difficult for me to use the init function to initialize environments, but this function just isn't generated.

Thanks

**Comment by Milad-Akarie** [comment]
Hey @meg4cyberc4t, the registering of environ has to be done by the main scope because it's not logical to register different environments for different scopes. 

 I edited the code so the main init function is always generated even if it has no classes to register. 
 
  injectable_generator: 2.3.0

**Comment by meg4cyberc4t** [comment]
Thanks!
