### ISSUE TITLE
Injectable 2.2.0 error flutter_test

### ISSUE THREAD

**Issue by lucasdidur** [Milad-Akarie/injectable#387]
Because injectable_generator >=2.2.0 depends on collection ^1.18.0 and every version of flutter_test from sdk depends on collection 1.17.1, injectable_generator >=2.2.0 is incompatible with flutter_test from sdk.
So, because app depends on both flutter_test from sdk and injectable_generator ^2.2.0, version solving failed.

Using flutter 3.10.6

**Comment by Milad-Akarie** [comment]
@lucasdidur reverted in injectable_generator: 2.3.0
Thanks for reporting.
