### ISSUE TITLE
not getting right init with config preResolve (not getting a Future)

### ISSUE THREAD

**Issue by nowjordanhappy** [Milad-Akarie/injectable#390]
I'm using a module and @preResolve but getting wrong generated file. It seems init functions is not generated as a Future:

Module:
`

    @module
    abstract class OnboardingModule{

    //Register use cases
    @singleton
    @preResolve
    GetDocumentsType get documentsType => GetDocumentsType();

      //Register view models
      @singleton
      SignInViewModel get signInViewModel => SignInViewModel();
    
      @singleton
      SignUpViewModel get signUpViewModel => SignUpViewModel(documentsType);
     }
`

And the code generated has errrors:
<img width="644" alt="Screenshot 2023-08-12 at 01 19 40" src="https://github.com/Milad-Akarie/injectable/assets/26355419/5c38d46c-ecb8-474a-a13a-8612dba82a90">

And dependencies:
`  
get_it: ^7.6.0

  injectable: ^2.2.0
`

And dev_dependencies:
`  
  injectable_generator: ^2.3.0

  build_runner: ^2.4.6

"flutterSdkVersion": "3.10.3",
`

**Comment by Milad-Akarie** [comment]
@nowjordanhappy I believe the issue here is that you're trying to `preResolve` a non-async dependency, `GetDocumentsType` is not a future why are you trying to preResolve it? 
There should be a check from the injectable_generator side to prevent these cases.

**Comment by nowjordanhappy** [comment]
Thanks!
