### ISSUE TITLE
Pre-resolving singleton

### ISSUE THREAD

**Issue by m4ff** [Milad-Akarie/injectable#40]
First of all, thank you for creating this package!

I have a use case where I would like to do something like the following:
```
@singleton
class ApiClient {
  @factoryMethod  
  @preResolve
  static Future<ApiClient> create() async {
    ....
    return apiClient;
  }
}
```

Unless I'm missing something, to achieve that I currently have to write the following code:
```
@registerModule
abstract class ApiCientModule {
  @preResolve
  Future<ApiClient> create() async {
    ....
    return apiClient;
  }
}

class ApiClient {
  ...
}
```

This is significantly more clunky. Would it be possible to add support for pre-resolving async factory methods?

**Comment by Milad-Akarie** [comment]
Hey @m4ff ,  try annotating the class not the factory method

```dart
@preResolve
@singleton
class ApiClient {
  @factoryMethod  
  static Future<ApiClient> create() async {
    ....
    return apiClient;
  }
}
```

**Comment by m4ff** [comment]
Thanks, that works! Can I suggest you add that example to the documentation? I am sure it will be helpful to others in the future.

**Comment by Milad-Akarie** [comment]
sure
