### ISSUE TITLE
[Feature Request] Fire an 'object constructed' callback

### ISSUE THREAD

**Issue by Adam-Langley** [Milad-Akarie/injectable#405]
Hi Milad,

I would very much love get_it to implement this feature, however I think that's unlikely to happen - and to be honest, it's not necessary, as I rely heavily on injectable and that's a good place for this.

Could we have the `$initGetIt` method accept a callback that receives objects as they are instantiated?

It would look something like this:

this is an example of the 'new' generated code.
Note how the constructed 'ConnectivityService' is passed through the 'asyncInstanceCallback'...
```
 await gh.singletonAsync<_i4.ConnectivityService>(
    () {
      final i = asyncInstanceCallback(_i4.ConnectivityService());
      return i.init().then((_) => i);
    },
  );
```

```
// a synchronous callback method that will
// get called every time an object is created synchronously
T syncCallback<T>(T instance){
  return instance;
}

// an asynchronous callback method that will
// get called every time an object is created asynchronously
Future<T> asyncCallback<T>(T instance) async {
  return instance;
}

$initGetIt(getIt, environment: environment, syncInstanceCallback: syncCallback, asyncInstanceCallback: asyncCallback)
```

Why do I want this?

I want to be able to decorate my service class with various behavior contracts, such as 'Initializable', and when the object is instantiated, the 'instance callback' can test the object for being an implementation of various contracts, and act appropriately.

for example:

```
// (my callback handler)
// performs some reaction to an object being created.
// This method returns the instance to make the generated code very simple (just 'passes' the instance through)
// However, also has the ability to 'wrap' the instance on its way through... just an added bonus!
T syncCallback<T>(T instance){
  if (instance is Initializable){
    _initializationWorker.registerInstance(instance);
  }
  return instance;
}

```

**Comment by Milad-Akarie** [comment]
Hey @Adam-Langley, this use case is new to me, but what comes to mind after reading this is the possibility of using a register module, to build your IniitlizableService, decorate it then register it

```dart
@module
abstract class InitializableRegisterModule {
  @Singleton()
  Future< InitializableServivce1> buildService1(Dep1 dep1, Dep2 dep2) {
    /// build, initialize return fro registration
  }

  @Singleton()
  Future< InitializableServivce2> buildService2(Dep1 dep1, Dep2 dep2) {
    /// build, initialize return fro registration
  }
}
```
dep1/2 will be injected for you to be used inside of the factory method buildService

**Comment by Adam-Langley** [comment]
Hi @Milad-Akarie -
indeed, this is how I currently achieve my needs, however, I have many services, and following this process increases my plumbing code by an order of magnitude - adding this feature would absorb this commonality into the infrastructure.

When I get the time, I'll look at doing a PR for you to consider.

Thanks,

**Comment by Adam-Langley** [comment]
Hi @Milad-Akarie 

I had a look at how to implement this, and started modifying the code builder. I had it mostly done, then I realised, I could actually just make a small change to the getItHelper which would meet my needs.
I *believe* this would turn it from a "object instantiated" hook, to just an "object retrieved" hook.
However, because the first instantiation is also a retrieval, this is fine by me - as I get at least 1 opportunity to inspect the instance, and act on its contract.

With this small change, I can now remove dozens of lines of @module code and proxy "builder" functions. and replace ALL of it, with just this:

```
// initialize getit. Pass my 'retrieval' callback, which will get fired when an object is obtained from getit.
$initGetIt(
  getIt, 
  environment: environment, 
  retrievalCallback: retrievalCallback)

Object retrievalCallback(Object service) {
  if (service is Initializable){
    // do some work here, in my case it's "initializable" related stuff...
  }
  return instance;
}
```

Please consider this pull.
If there is a better way you'd prefer me to do it to be fit for inclusion, please let me know.

Thanks,

**Comment by Adam-Langley** [comment]
Hi again @Milad-Akarie,

After spending a little more time experimenting with this - I found that my "cheap" solution wasn't actually catching all scenarios. It only hooked the creation where the instance was a *dependency*, and not when it was the actual service being requested by the developer.

As such, I've written the "proper" code-gen version. It simply wraps all places where the constructor is called.
Usage is the same.

Example output from code-generator:
```
// code removed for brevity...

// initializes the registration of main-scope dependencies inside of GetIt
Future<_i1.GetIt> $initGetIt(
  _i1.GetIt getIt, {
  String? environment,
  _i2.EnvironmentFilter? environmentFilter,
  T Function<T>(T)? instanceCallback, // this is new
}) async {
  final gh = _i2.GetItHelper(
    getIt,
    environment,
    environmentFilter,
  );
  final cb = instanceCallback ?? <T>(p0) => p0; // ensure callback is at least initialized to a benign pass-through
  final controlMasterDetailStoreModule = _$ControlMasterDetailStoreModule();

// code removed for brevity...

  await gh.singletonAsync<_i3.ConnectivityStore>(
    () {
      final i = cb(_i3.ConnectivityStore()); // <-- see the new 'cb' invocation here
      return i.init().then((_) => i);
    },
    registerFor: {_PRODUCTION},
    preResolve: true,
  );
  gh.factory<_i4.ControlMapper>(
    () => cb(_i4.ControlMapper()), <-- see the new 'cb' invocation here
    registerFor: {_PRODUCTION},
  );
  gh.factoryParamAsync<_i5.ControlMasterDetailStore, String?, dynamic>(
    (
      hazardId,
      _,
    ) =>
        cb(controlMasterDetailStoreModule.create(hazardId)), <-- see the new 'cb' invocation here
    registerFor: {_PRODUCTION},
  );

// code removed for brevity...
```

**Comment by Milad-Akarie** [comment]
guess it safe to close this now

**Comment by Adam-Langley** [comment]
Thanks @Milad-Akarie - yes all good here. Working well.
