### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by m4ff** [Milad-Akarie/injectable#41]
Is there currently a way to declare dependencies? The only way I found so far is to always use lazySingletons, so dependencies are injected only after they are all registered. This approach does not always work, for example, if some singletons need to be pre-resolved. In that case the initialisation order in `$initGetIt` matters, but I haven't found a way to control that order.

**Comment by Milad-Akarie** [comment]
@m4ff  injectable automatically orders dependencies by dependents so you should be fine.

**Comment by m4ff** [comment]
How is a dependency declared and injected? Is it enough to declare an instance variable like this?
```
@singleton
@preResolve
class ApiClient {
  // dependency
  final UserStore _userStore = GetIt.I<UserStore>();
  @factoryMethod
  static Future<ApiClient> create() async {
    ....
    return apiClient;
  }
}

@singleton
@preResolve
class UserStore {
  @factoryMethod
  static Future<UserStore> create() async {
    ....
    return userStore;
  }
}
```

**Comment by Milad-Akarie** [comment]
In flutter we use construct injection since we construct everything our selfs, so in your case

```dart
@singleton
@preResolve
class ApiClient {
  @factoryMethod
// declare it as an injected dependency and injectable will take care of it
  static Future<ApiClient> create(UserStore _userStore) async {
    ....
    return apiClient;
  }
}
```

**Comment by Milad-Akarie** [comment]
also I wouldn't recommend alot of preResolving since this may slow your startup time. consider using async factories.

**Comment by m4ff** [comment]
Thanks, it's all clear now!
