### ISSUE TITLE
injectible: Multi user project compatibility ?

### ISSUE THREAD

**Issue by PDDStudio** [Milad-Akarie/injectable#42]
Hey again,

We're using version `0.3.0` in our project with multiple team members and operating systems (mostly Windows and Mac).
Today we had an issue with the generated `iconfig.dart` file in some merge requests on our git.

It seems like if a mac user runs `flutter packages pub run build_runner build` the output contains the *same content*, but in a *completely different order* than the output of the windows user running the same command.

The problem is that now the PR diffs contain huge changes even though there should be only one or two new lines for the new changes added. Sometimes this blocks PRs for no reasons and consumes time to resolve them by hand every time.

Maybe this has something to do with file tree walking when searching for annotations or something?

Is there a way to avoid this? Maybe alphabetical file tree walking can fix this?

Regards

**Comment by Milad-Akarie** [comment]
Hmm that's a tough one. deps are being sorted by dependents meaning  for example if we have two deps that depend on nothing injectable will not care about their order.. I guess I can try to sort them alphabetically before sorting them by dependents. 
only problem is that I don't have a windows machine anywhere near me lol

**Comment by PDDStudio** [comment]
Hi,
Sorry for the late reply. I've a Mac and a Windows machine here, so I can help you for testing if you need :)

**Comment by PDDStudio** [comment]
@Milad-Akarie I'm still happy to help you with this if you need me for testing.
You can also give me some short instructions on what to do then I could try open an MR.

**Comment by Milad-Akarie** [comment]
Hey, @PDDStudio Sorry for the delay,  I was actually planning on working on injectable today since I'm done fixing auto_route. I'll let you know.

**Comment by Milad-Akarie** [comment]
Hey @PDDStudio, I just pushed injectable_generator 0.3.4 and I added the alphabetical sort bit. 
can you please give it a test?

**Comment by PDDStudio** [comment]
Hey @Milad-Akarie 
I was now able to verify version `0.3.4`.  
Alphabetical ordering seems to fix the issue (as of now).  

What I did:
- Upgrade `injectable_generator` to `0.3.4`.
- Run `flutter packages pub run build_runner build` on Windows, committed the updated `iconfig.dart`.
- Check out the changes on Mac, run `flutter packages pub run build_runner build` again
- Checked git, no changes were made.

I would close this issue for now, as for me it seems to be fixed 👍 

Thank you for taking the time!
