### ISSUE TITLE
Dart 3 records (Tuples) are not supported

### ISSUE THREAD

**Issue by zaikaCorpsoft** [Milad-Akarie/injectable#420]
Showcase is next, we have a generic class parameterized with the record(Tuple)

@Injectable(as: Factory<ModelDto, (List<Model>, Pagination)>)
class ModelsFromDtoFactory implements Factory<ModelListDto, (List<Model>, Pagination)> {
 @override
  Future<(List<Note>, Pagination)> create(ModelListDto argument) async => //Transform
}

record in the injection container is added

//record generated without a prefix making it an error n the generated class
  gh.factory<_i13.Factory<_i14.ModelListDto, (List<Model>, Pagination)>>(() => _i45.ModelsFromDtoFactory(
// Something to inject, no matter regarding the case
        ));
        
 Additional checkup required

**Comment by Milad-Akarie** [comment]
Records were supported in the latest versions.
