### ISSUE TITLE
[Question] How to dispose an instance?

### ISSUE THREAD

**Issue by RollyPeres** [Milad-Akarie/injectable#43]
With get_it you can call unregister on an instance. Does injectable support unregistering so that one could pass a disposing function ?
Also, is there a way to reset a singleton/lazySingleton ?

**Comment by Milad-Akarie** [comment]
Hey @RollyPeres you can still do anything get_it supports. 
Injectable merely generates the registering functions which otherwise you would write manually.
So you can still use the GetIt instance you created at first and call your reset or unregister functions
for ex getIt. unregister(..)

**Comment by RollyPeres** [comment]
Hey, I'm aware of that, was more like curious if that could be achieved with injectable as well. Thanks @Milad-Akarie !
