### ISSUE TITLE
Proposal: Skip nullable/optional params in singletons

### ISSUE THREAD

**Issue by Albert221** [Milad-Akarie/injectable#432]
I have a class with a few constructor parameters, one of which is nullable (and let's say `@visibleForTesting`). When I mark this class with `@singleton`, `injectable` adds the singleton to `get_it` with this nullable parameter. There's no way to control that currently.

Could we add some `@skipParam` annotation or whatever to allow such behavior to be controlled?

**Comment by glebamichal** [comment]
Good point. Would be great to have it controlled.

**Comment by Milad-Akarie** [comment]
@Albert221 @glebamichal you can point injectable to what constructor to use, so in your case you'd create a constructor that's used for injection

```dart
class MyClass{
  MyClass(Service a, {nullableParam})// main constructor

 
  @factoryMethod // tell injectable to use this constructor instead, this could be factory, named constructor or static method
   MyClass.create(Service a) // used by injectable
 }
```
or maybe have the main constructor inject-safe and have another named MyClass.forTest() or something, injectable will use the main constructor by default.

**Comment by Albert221** [comment]
@Milad-Akarie and this is exactly what I did for my use-case :), but adding a small annotation is much easier and cleaner than repeating the constructor with its params and field initialization list

**Comment by Milad-Akarie** [comment]
@Albert221 @ignoreParam was added to the latest versions, make sure you update both librarys

**Comment by Albert221** [comment]
That was fast, thank you!
