### ISSUE TITLE
Type Alias error on generation

### ISSUE THREAD

**Issue by srdrymn** [Milad-Akarie/injectable#437]
I have a type alias as 

`typedef Json = Map<String, dynamic>;`

I also have a 

`@factoryParam Json? defaultHeaders`

in one of my `@injectable` classes in a `@module`

Before injectable_generator 2.5.0, the mapping in the generator config file for the factoryParam was a type of `Map<String, dynamic>?` which is fine. However, after upgraded to 2.5.0 the type alias mapped incorrectly as  `_i23.Json<String, dynamic>?` where _i23 is the dependency prefix. This mapping should either be the base type as before, or just `_i23.Json?`

**Comment by Milad-Akarie** [comment]
@srdrymn should be fixed in injectable_generator 2.5.1
Thanks for reporting.

**Comment by phamconganh** [comment]
@Milad-Akarie how can i get `_i23.Json`? i am using `@module` and it is not generating the correct typedef. I am using `injectable_generator: ^2.6.2`
