### ISSUE TITLE
Using dynamics with @factoryParam

### ISSUE THREAD

**Issue by siberiusfr** [Milad-Akarie/injectable#44]
Hello, thank you for this great library. It help a lot.

Here is my problem :
I'm using Injectable with Retrofit and Dio Library. I wanna pass the URL of the server to the constructor of Retrofit but it doesn't work with getIt.

Here my example :
```
@injectable
@RestApi(baseUrl: "https://ServerUrl")
abstract class UserRestClient {
  @factoryMethod
  factory UserRestClient(Dio dio, {@factoryParam String baseUrl}) = _UserRestClient;
  @GET("/users")
  Future<List<User>> getUsers();
}
}
```
it generate as the documentation the following code :

```
g.registerFactoryParam<UserRestClient, String, dynamic>(
      (baseUrl, _) => UserRestClient(g<Dio>(), baseUrl: baseUrl));
```

but when i want to pass the dynamic parameter  it doesnt work, i got compilation error
`final userRestClient = getIt<UserRestClient>(baseUrl:'https://AnotherServerUrl');//compilation error`

Is there something missing in my code?

What i want to do is the pass prod or dev URL to the app dynamically. I'm using another class as follwing :

```
abstract class Properties {
  String getRestEndPoint();
}
@injectable
@RegisterAs(Properties, env: Environment.dev)
class DevProperties implements Properties {
   @override
   String getRestEndPoint() => "https://DevServerUrl";
}
@injectable
@RegisterAs(Properties, env: Environment.prod)
class ProdProperties implements Properties {
   @override
   String getRestEndPoint() => "https://ProdServerUrl";
}
```
and call the rest client with dynamic parameter to inject this properties : 

```
String url = getIt<Properties>().getRestEndPoint();
final userRestClient = getIt<UserRestClient>(url ); 
```

Do i have something missing in my code or is it an issue?

**Comment by Milad-Akarie** [comment]
Hey @siberiusfr, try assigning your url to the named param1
`final userRestClient = getIt<UserRestClient>(param1: url ); `

**Comment by siberiusfr** [comment]
Oh so easy... thanks a lot Milad for this fast answer :)
Then sorry it's not an issue...
