### ISSUE TITLE
Because injectable_generator >=2.6.0 depends on injectable ^2.4.0 which depends on meta ^1.12.0, injectable_generator >=2.6.0 requires meta ^1.12.0. And because every version of flutter from sdk depends on meta 1.11.0, injectable_generator >=2.6.0 is incompatible with flutter from sdk. So, because depends on both flutter from sdk and injectable_generator ^2.6.1, version solving failed.

### ISSUE THREAD

**Issue by Saidjamol** [Milad-Akarie/injectable#441]
This error occurred when updating the injectable_generator version to 2.6.1.

Because injectable_generator >=2.6.0 depends on injectable ^2.4.0 which depends on meta ^1.12.0, injectable_generator >=2.6.0 requires meta ^1.12.0. And because every version of flutter from sdk depends on meta 1.11.0, injectable_generator >=2.6.0 is incompatible with flutter from sdk. So, because depends on both flutter from sdk and injectable_generator ^2.6.1, version solving failed.

flutter doctor:
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4 23E214 darwin-arm64, locale en-AF)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by Milad-Akarie** [comment]
Hey @Saidjamol should be fixed in 2.4.1
