### ISSUE TITLE
Support @RegisterAs with generics

### ISSUE THREAD

**Issue by pro100svitlo** [Milad-Akarie/injectable#45]
I have an abstract class
```dart
abstract class Mapper<Input, Output> {
  Output map(Input input);

  List<Output> mapList(List<Input> inputs) => inputs.map((input) => map(input)).toList();
}
```

Also I have a class that extend mapper:
```dart
class DtoToEntityMapper extends Mapper<Dto, Entity> {

  @override
  Entity map(Dto input) {
    ...
  }
}
```

What I need is create a lazy singleton and register it as `Mapper<Dto, Entity>` :
```dart
@RegisterAs(Mapper<Dto, Entity>)
@lazySingleton
class DtoToEntityMapper extends Mapper<Dto, Entity> {
   ... 
}
```
But instead I get an error:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/12133914/78371134-d3c3fd00-75c7-11ea-8877-fe5618fd7a8a.png">

**Comment by Milad-Akarie** [comment]
Hey, @pro100svitlo 
you don't need to specify the generics manually as injectable automatically obtains them from the actual implementation. 
so this
```dart
@RegisterAs(Mapper)
@lazySingleton
class DtoToEntityMapper extends Mapper<Dto, Entity> {
   ... 
}
```
will generate this
```dart
g.registerLazySingleton<Mapper<Dto,Entity>(() => DtoToEntityMapper());
```

**Comment by pro100svitlo** [comment]
Nice!

Thanks 👍 

So as a suggestion - it would be nice to have this describen in doca in more explicit way 🙏
