### ISSUE TITLE
Generics in @registerModule

### ISSUE THREAD

**Issue by saschaernst** [Milad-Akarie/injectable#46]
Something like

```
class LocalStringLoader extends StringLoader {}

class DocumentService<T extends StringLoader> {
  final T _loader;

  DocumentService(this._loader);
}

@registerModule
abstract class RegisterModule {
  @singleton
  DocumentService<LocalStringLoader> get localDocumentService;
}
```
results in 

The argument type 'dynamic' can't be assigned to the parameter type 'LocalStringLoader'.
The name 'T' isn't a type so it can't be used as a type argument.
Try correcting the name to an existing type, or defining a type named 'T'.

as it generates

```
@override
  DocumentService<LocalStringLoader> get localDocumentService =>
      DocumentService(_g<T>());
```

Is that a bug, a missing feature, or am I doing something wrong?

Cheers and thanks for your hard work on all these fantastic libraries, Sascha

**Comment by Milad-Akarie** [comment]
Hey @saschaernst sorry for the delay dude.. it was busy week. 
This scenario is now handled in injectable_generator 0.3.4. check it out!
