### ISSUE TITLE
Code generation is registering same factory twice

### ISSUE THREAD

**Issue by Haidar0096** [Milad-Akarie/injectable#49]
As the title says I have the problem:
```
  g.registerFactory<ThemeBloc>(() => ThemeBloc());
  g.registerFactory<ThemeBloc>(() => ThemeBloc());

```

I think you would want to reproduce the problem but I don't know how because I have no idea why is this happening
I have the ThemeBloc which extends Bloc and I annonated it with @injectable
then I run the build_runner command
Do you know what might be causing this?

**Comment by Milad-Akarie** [comment]
@Haidar0096 That's pretty weird. Do you have Auto registering on?

**Comment by Haidar0096** [comment]
what do you mean by auto registring
I follow the guidelines you put on the pub.dev to register the routes and the auto router

**Comment by Milad-Akarie** [comment]
@Haidar0096 are you talking about auto_route? I'm confused lol

**Comment by Milad-Akarie** [comment]
@Haidar0096 Could you remove the suffix Bloc from your class name and try again?

**Comment by Haidar0096** [comment]
Sorry that was a typo,I am talking about injectable 
here are some code snippets:
theme_bloc.dart:
```
@injectable
class ThemeBloc extends HydratedBloc<ThemeEvent, ThemeState> {
//some code
}
```
injection.iconfig.dart (the generated file):
```
void $initGetIt(GetIt g, {String environment}) {
//some code
  g.registerFactory<ThemeBloc>(() => ThemeBloc());
  g.registerFactory<ThemeBloc>(() => ThemeBloc());
//some code
}
```
injection.dart (where I define the configureInjection):

```
final GetIt getIt = GetIt.instance;

@injectableInit
void configureInjection(String env) {
  $initGetIt(getIt, environment: env);
}
```
main.dart:
```
Future<void> main() async {
//some code
  configureInjection(Environment.prod);
 //some code
}
```

Tell me if you need more info.
Also I tried to rename the class to ThemeB but something weird also happened
The generator registered ThemeB but also still registered ThemeBloc
The command I used is:
`flutter pub run build_runner watch --delete-conflicting-outputs`

**Comment by Milad-Akarie** [comment]
Where is it getting the ThemeBloc from then? Can you jump to the class
definition?

**Comment by Haidar0096** [comment]
No I can't the linter already gives an error saying cant find a declaration to go to
But since I changed the class name and it still produced the weird result I am suspecting it is something related to caching (or else where is it getting the class name from I mean the code generator)
I don't know how generating works anyway but that may help

**Comment by Milad-Akarie** [comment]
Ok try running

flutter packages pub run build_runner clean

**Comment by Haidar0096** [comment]
Yes it worked
I run your command
then i run ` flutter pub run build_runner watch --delete-conflicting-outputs`
and it worked
Thanks.
