### ISSUE TITLE
Multiple @RegisterAs

### ISSUE THREAD

**Issue by artemmmon** [Milad-Akarie/injectable#50]
Hi, Is it possible to attach **several** abstract classes to implementation? 
It would be very helpful, thanks :)
e.g. 

```
@RegisterAs(AuthorizationObserver)
@RegisterAs(UserProvider)
@singleton
class UserProviderBloc implements UserProvider, AuthorizationObserver {
...
}
```

--- or ----
`@RegisterAs([UserProvider, AuthorizationObserver])`

**Comment by Milad-Akarie** [comment]
Hey @artemmmon unfortunately, I don't think get_it or any other dependencies container supports registering under multiple types. containers are merely maps that use types as keys.

**Comment by jarekb123** [comment]
You can do it manually in Register module:

```dart
@singleton
@injectable
class UserProviderBloc implements UserProvider, AuthorizationObserver {
...
}

@registerModule
abstract class RegisterModule {
  @singleton
  UserProvider userProvider() => GetIt.I.get<UserProviderBloc>()

  @singleton
  AuthorizationObserver authObserver() => GetIt.I.get<UserProviderBloc>()
}

**Comment by artemmmon** [comment]
> You can do it manually in Register module:
> 
> ```dart
> @singleton
> @injectable
> class UserProviderBloc implements UserProvider, AuthorizationObserver {
> ...
> }
> 
> @registerModule
> abstract class RegisterModule {
>   @singleton
>   UserProvider userProvider() => GetIt.I.get<UserProviderBloc>()
> 
>   @singleton
>   AuthorizationObserver authObserver() => GetIt.I.get<UserProviderBloc>()
> }
> ```

Hmm. Nice idea! Thanks ;)
