### ISSUE TITLE
Breaks when used with i18n_extension

### ISSUE THREAD

**Issue by lukepighetti** [Milad-Akarie/injectable#51]
Whenever I use this package with `i18n_extension` I get this error

```
NoSuchMethodError: The getter 'major' was called on null.
Receiver: null
Tried calling: major
[SEVERE] injectable_generator:injectable_builder on test/widget_test.dart:
```

https://github.com/marcglasberg/i18n_extension/issues/30

**Comment by Milad-Akarie** [comment]
@lukepighetti Sorry for the delay. 
can you please tell me how to reproduce the error? 
I tried to use this extension but everything seems fine?

**Comment by lukepighetti** [comment]
Sorry I don't have a reproduction on hand. If you cannot reproduce it immediately I am happy to close this.
