### ISSUE TITLE
Parameter type error

### ISSUE THREAD

**Issue by mitty1987** [Milad-Akarie/injectable#52]
`UserDetailStore userDetailStore(User user) => UserDetailStore(user);`
====GENERATED CODE ====
`g.registerFactoryParam<UserDetailStore, User, dynamic>(
      (user, _) => registerModule.userDetailStore(user));`

When pass object(User) parameter, it can't import User dart.Is't only pass basic types?

**Comment by Milad-Akarie** [comment]
Hey @mitty1987  
Fixed in injectable_generator: 0.3.5
Thanks for reporting.
