### ISSUE TITLE
[Feature Request] Add @injectParam

### ISSUE THREAD

**Issue by TarekkMA** [Milad-Akarie/injectable#54]
Right now any providers with parameters in its declaration will be interpreted as ``registerFactoryParam``, but it would be a nice feature if we have an option to inject parameters from getting it. to modularize the code of custom initializers. 

What I suppose the code should look like.
```dart
@registerModule
abstract class RegisterModule {
  @lazySingleton
  Dio get dio => Dio(BaseOptions(baseUrl: "baseUrl"));

 @lazySingleton
  API api(@injectParam Dio dio) => API(dio)
} 
```
insted of using something like this
```dart
@registerModule
abstract class RegisterModule {
  @lazySingleton
  Dio get dio => Dio(BaseOptions(baseUrl: "baseUrl"));

 @lazySingleton
  API api() {
    final dio = sl.get<Dio>();
    return API(dio);
  }
```

**Comment by Milad-Akarie** [comment]
@TarekkMA  That's neat! might take me some time to implement though, I'm a little busy these days.

**Comment by TarekkMA** [comment]
okay, no problems, I will see if I manage to implement it and I will make a pull request.

**Comment by TarekkMA** [comment]
@Milad-Akarie I think it might be a better idea instead of introducing new annotation if we used ``@factoryParam`` in registerModule to explicitly tell injectable to generate marked parameters as FarcoryParams. and any other parameters should be injected.

As I see static methods annotated with ``@factoryMethod`` behave like that, only making FarcoryParams if parameters annotated with ``@factoryParam``.

the downside it that it might be a breaking change. the following code from the README in the proposed change would treat URL as something that can be injected from get_it.
```dart
@registerModule
abstract class RegisterModule {
   BackendService getService(String url) => BackendService(url);
}
```

what do you think? should we introduce @injectParam or the proposed change?

**Comment by Milad-Akarie** [comment]
@TarekkMA I'd go with the proposed change, so methods inside of register modules would act exactly the same as a factory method. 
That would also be easier to implement.
Did you already start working on this?

**Comment by TarekkMA** [comment]
No I was taking a look at the source code to get familiar with it

**Comment by Milad-Akarie** [comment]
@TarekkMA Actually your second suggestion makes it easy to implement so let me handle it.

**Comment by TarekkMA** [comment]
Okay, thanks a lot <3

**Comment by Milad-Akarie** [comment]
@TarekkMA I ended up refactoring alot of code and writing some tests in the process. 
anyways, it was Implemented as suggested in 
injectable: 0.4.0
injectable_generator: 0.4.0
Thanks for your efforts.
