### ISSUE TITLE
Repo size is too large

### ISSUE THREAD

**Issue by TarekkMA** [Milad-Akarie/injectable#56]
The repo size is too large about 120MB. it seems that gitignore was added later and flutter files were logged to git.
![Screen Shot 2020-05-07 at 1 46 53 AM](https://user-images.githubusercontent.com/6633545/81239272-a45c4200-9004-11ea-992f-0c13d094ea68.png)

**Comment by Milad-Akarie** [comment]
True, at some point I messed up and deleted the .gitignore file and when I added it back I didn't notice the repo size
