### ISSUE TITLE
Allow the same name for different class types

### ISSUE THREAD

**Issue by Pawelo93** [Milad-Akarie/injectable#60]
I was wondering if it would be hard to allow same names in @ Named annotation for diferent classes.
For example it would be nice to name few my databases 'local' and 'network'.

What you think about it?

**Comment by Milad-Akarie** [comment]
@Pawelo93 Please provide a code example, I'm not sure I understand your request.

**Comment by Pawelo93** [comment]
I would like to have two kinds of repositories (different type) and mark them @ Named('local') - now i have runtime exception that this name is already registered. 

Workaround is to use names lilke @ Named('local-repo1'), @ Named('local-repo2'). 

Is it possibe that lib should also look at class type instead of just name?

**Comment by Milad-Akarie** [comment]
Hey! @Pawelo93 unfortunately this's controlled by Get_it not injectable. if Get_it doesn't support it then I can't.

maybe try opening a request in the get_it repo?

**Comment by Pawelo93** [comment]
@Milad-Akarie I didnt know its part of get_it. Yes i opened issue there.  Thank you :)
