### ISSUE TITLE
injection.iconfig.dart not generated

### ISSUE THREAD

**Issue by jml90** [Milad-Akarie/injectable#61]
I created the injection.dart file inside the lib folder of my project with this code:

 ```
 import 'package:get_it/get_it.dart';
 import 'package:injectable/injectable.dart';

 final getIt = GetIt.instance;

 @injectableInit
 void configure() => $initGetIt(getIt);
```

When I run `flutter pub run build_runner watch --delete-conflicting-outputs ` the injection.iconfig.dart file it's not created so i can't resolve `$initGetIt(getIt)`

I'm running Flutter 1.17.0 from the stable channel.

**Comment by Milad-Akarie** [comment]
@jml90 Are you getting an error?

**Comment by jml90** [comment]
@Milad-Akarie no, it just don't create the file :(

I'll investigate more.

**Comment by jml90** [comment]
It works now @Milad-Akarie 

The only thing I changed is that I removed the lint plugin and the analysis_options.yaml rules.
I don't know if this could be the reason...

Anyway, the file gets generated now.  

Thanks for this amazing plugin.

**Comment by Milad-Akarie** [comment]
@jml90 That's great news! I'll investigate more about this issue but I'm closing this for now.

**Comment by rahulnakre** [comment]
Hey, I don't have the linting packages, and I'm experiencing the same issue

**Comment by AAverin** [comment]
Also stumbled into this now.
I did some changes to my classes, annotated some more for injection, but the file iconfig doesn't get created.
No visible errors from build_runner[](url)

**Comment by AAverin** [comment]
`injection.config.dart` is generated correctly, but not `injection.iconfig.dart`. Did I miss something? Should I use the `config` now?
