### ISSUE TITLE
Make injectable prettier? 

### ISSUE THREAD

**Issue by Milad-Akarie** [Milad-Akarie/injectable#62]
Hello guys!
I'd like some suggestions about annotations naming and possibly make use of common injection glossary.

for example 
I shortened `@registerModule` to be just `@module` like the one from dagger

I don't have a problem with most of the existing annotations but I don't like 
`@injectableInit`, so any suggestions on what it should be named instead?

**Comment by easazade** [comment]
i gotta say i really like this library
i think @tree would be nice. or something that implies creating a tree or dependency injection graph

**Comment by Milad-Akarie** [comment]
@easazade Thanks for your support, I was thinking maybe something common that's been used in a similar lib.

**Comment by aashir-khan** [comment]
I personally find the regular `lazySingleton` vs `LazySingleton` very confusing as they are very similar in spelling but do different things. Maybe a different name for `LazySingleton` would make it clearer the distinction? 

I'm also not sure what the difference between singleton and lazySingleton is. Seems like they are the same thing?

It might just be confusing to me

**Comment by Milad-Akarie** [comment]
Ya lazySingleton = const LazySingleton() 
And it can be used if you don't want to pass any parameters.
It might be a good idea to remove the field declaration and always use the constructor form.

Regarding the difference between Singletons and LazySingleton, Singletons are constructed as soon as they're registered but LazySingletons are not constructed until they're called/needed

**Comment by pro100svitlo** [comment]
another proposition:
`LazySinglton` can be converted to `Injectable(lazy: true)`

**Comment by cfregin** [comment]
I would suggest more Environment variables. I do not like abbreviations:) How about:

- Environment.development
- Environment.production
- Environment.test
- Environment.staging

At the moment, these are used like "OR" for injections: 
`@Injectable(as: Service, env: [Environment.dev, Environment.test])`

It would be really cool to have a platform tag as an "AND" as well:
`@Injectable(as: Service, env: [Environment.dev, Environment.test], platform: [Platform.web])`
and
`@Injectable(as: Service, env: [Environment.dev, Environment.test], platform: [Platform.mobile])`
or
`@Injectable(as: Service, env: [Environment.dev, Environment.test], platform: [Platform.iOS, Platform.android])`
would mean use this repository when in platform web AND (Environment.dev OR Environment.test)
