### ISSUE TITLE
Can't use latest injectable version 0.4.0

### ISSUE THREAD

**Issue by Reprevise** [Milad-Akarie/injectable#63]
The generator isn't compatible with 0.4.0, it only works with 0.3.0.
![image](https://user-images.githubusercontent.com/25782944/82124111-f589d580-976a-11ea-9084-259d95a6a29f.png)

**Comment by Milad-Akarie** [comment]
Hey @Reprevise  You were too quick dude lol
Just finished uploading injectable_generator:0.4.0
