### ISSUE TITLE
Binding abstract classes to implementations fails

### ISSUE THREAD

**Issue by xenoliss** [Milad-Akarie/injectable#65]
Hello,

First thank you so much for this amazing package !

Now I'm trying to register an `AuthRepository` that implements an `IAuthRepository` but the generated code does not import the `IAuthRepository` so I have to manually add the import statements in the generated file. Is this an expected behavior ?

My code looks something like this:
in domain/auth/repositories
```Dart
abstract class IAuthRepository {
  Future<Either<AuthFailure, UserDto>> registerUser({
    @required User user,
  });

}
```
in infra/auth/repository:
```Dart
@Injectable(as: IAuthRepository)
class AuthRepository implements IAuthRepository {
  AuthRepository({
    @required this.dataSource,
  });

  final IAuthDataSource dataSource;

  @override
  Future<Either<AuthFailure, UserDto>> registerUser({
    @required User user,
  }) async {
   ....
  }
}
```

And the generated file is:
```Dart
// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

import 'package:backend/infrastructure/auth/repositories/auth_repository.dart';
import 'package:backend/backend.dart'; // <== Useless import
import 'package:get_it/get_it.dart';

void $initGetIt(GetIt g, {String environment}) {
  g.registerFactory<IAuthRepository>( // Here can't resolve IAuthRepository because does not import the appropriate file
      () => AuthRepository(dataSource: g<IAuthDataSource>())); // Same here IAuthDataSource not resolved because not imported
}

```
Thanks in advance for your help.

**EDIT:** After investigating a bit I found that this is due to the export statements done in the backend.dart file of an Aqueduct project. Here is the file :
```Dart
/// backend
///
/// A Aqueduct web server.
library backend;

export 'dart:async'; // <== remember this one
export 'dart:io';

export 'package:aqueduct/aqueduct.dart';

export 'presentation/_core/channel.dart';

```

and now on my `AuthRepository` I have :
```Dart
import '...';

import 'dart:async'; // <== for the 'Future' type. Here if I import ../../../backend.dart that exports dart:async the generated file has the error mentionned above (no import statements)

@Injectable(as: IAuthRepository)
class AuthRepository implements IAuthRepository {
  AuthRepository({
    @required this.dataSource,
  });

  final IAuthDataSource dataSource;

  @override
  Future<Either<AuthFailure, UserDto>> registerUser({
    @required User user,
  }) async {
    ...
  }
}
```

**Comment by Milad-Akarie** [comment]
Hey @BaptisteOue I'm not sure what's going on here. I can't reproduce the issue you're talking about. 

Are you on flutter web?

**Comment by BaptisteOue** [comment]
Hello,

No I'm using Dart for **backend developpment** with the Aqueduct framework (another package).
I'm using Dart v2.7.2 (2.8 having some breaking changes with postgres package I'm waiting for them before upgrading my version).

Are get_it / injectable only supposed to be used for flutter ?

**Comment by Paradoxu** [comment]
Same was happening here using flutter, I solved using @LazySingleton(as: ...) instead of using @Injectable(as: ...).
