### ISSUE TITLE
Please add a LICENSE to the project

### ISSUE THREAD

**Issue by djensen47** [Milad-Akarie/injectable#66]
Folks who want to use this library in their projects need to know what LICENSE your code is covered under.

I suggest MIT. If you need something more restrictive but still very open Apache 2 is a good alternative.

Thanks for the great library!

**Comment by Milad-Akarie** [comment]
@djensen47 I though adding to the actual packages is the right thing to do. I'll just pull it out

**Comment by Milad-Akarie** [comment]
done

**Comment by djensen47** [comment]
> @djensen47 I though adding to the actual packages is the right thing to do. I'll just pull it out

I think you're right but I guess it's nice to have it in the root so that Github picks up the license as well. Thanks for doing this!
