### ISSUE TITLE
Consider 1.0.0 as next version

### ISSUE THREAD

**Issue by djensen47** [Milad-Akarie/injectable#67]
Per semver 0.x.y releases are considered to be breaking changes, which means that every time you release a new version right now, we have to read through CHANGELOG.

It's common these days to see packages with versions like 1.74.0 -- that's 74 non-breaking releases.

Thanks!

**Comment by djensen47** [comment]
If you feel, for some reason, the library isn't ready for 1.0.0, then please provide a changelog that lists out features, fixes, and breaking changes. Thanks!

**Comment by Milad-Akarie** [comment]
@djensen47 injectable has two separate packages, so every package has it's own license and ChangeLog files as required by pub.dev if I remember correctly.

**Comment by djensen47** [comment]
Thanks I completely missed that. Thanks for the great project!

**Comment by Milad-Akarie** [comment]
We're here! injectable: 1.0.0 check it out
