### ISSUE TITLE
Typo in @Environment

### ISSUE THREAD

**Issue by wrbl606** [Milad-Akarie/injectable#7]
Hey,
it's a silly mistake but fixing it will break app builds. Class `Environment` defined in `injectable_annotations.dart` have a typo and is currently (in version 0.2.0) named Envir**no**ment.

![obraz](https://user-images.githubusercontent.com/15102395/74149838-fe698900-4c08-11ea-9ba0-549576beabcf.png)

Here a [link](https://www.merriam-webster.com/dictionary/environment) to proper spelling if in question.

**Comment by ResoDev** [comment]
Didn't even notice that you added `test` as a constant @Milad-Akarie. +1 for that 👍👍👍

**Comment by Milad-Akarie** [comment]
@ResoDev  I saw somewhere it might be needed haha.

**Comment by Milad-Akarie** [comment]
@wrbl606 Thanks for pointing that out, Android studio wouldn't let me get a way with such a type but, spell checking in vs code is meh. 
fixed in v0.2.1
