### ISSUE TITLE
Wrong Lazy Singleton Binding

### ISSUE THREAD

**Issue by Vayth** [Milad-Akarie/injectable#70]
I'm updating injectable from 0.3.0 to 0.4.0 and changing `@RegisterAs` annotation into `@Injectable(as:)`. However `@lazySingleton` seems to generate wrong binding?

In 0.3.0 or 0.4.0 using `@RegisterAs`
```
@lazySingleton
@RegisterAs(IAuthRepository)
class FirebaseAuthRepository implements IAuthRepository {
  final FirebaseAuth _firebaseAuth;
  final GoogleSignIn _googleSignIn;
  ...
}
```
generates
```
g.registerLazySingleton<IAuthRepository>(
      () => FirebaseAuthRepository(g<FirebaseAuth>(), g<GoogleSignIn>()));
```
\
\
\
However in 0.4.0 using `@Injectable`, it generates `FirebaseAuthRepository` instead of `IAuthRepository`
```
@lazySingleton //or @singleton
@Injectable(as:IAuthRepository)
class FirebaseAuthRepository implements IAuthRepository {
  final FirebaseAuth _firebaseAuth;
  final GoogleSignIn _googleSignIn;
  ...
}
```
generates
```
g.registerLazySingleton<FirebaseAuthRepository>(
      () => FirebaseAuthRepository(g<FirebaseAuth>(), g<GoogleSignIn>()));
```
\
\
\
I tried removing `@lazySingleton` and it generates it right: `IAuthRepository`.
```
@Injectable(as:IAuthRepository)
class FirebaseAuthRepository implements IAuthRepository {
  final FirebaseAuth _firebaseAuth;
  final GoogleSignIn _googleSignIn;
  ...
}
```
generates
```
g.registerFactory<IAuthRepository>(
      () => FirebaseAuthRepository(g<FirebaseAuth>(), g<GoogleSignIn>()));
```

So I think the `@lazySingleton` annotation has some problem going on? Or is it the new behavior? Since it's replacing `@RegisterAs`, I thought it should have similar behavior.

**Comment by Milad-Akarie** [comment]
Hey @Vayth I guess the new approach wasn't documented properly. The whole idea was to make the code more compact, one annotation instead of two.
Singleton and LazySingleton are subs of Injectable so you don't use them WITH injectable but instead of, in your example that would be 

```dart
@LazySingleton(as: IAuthRepository)
class FirebaseAuthRepository implements IAuthRepository {}
```
