### ISSUE TITLE
Error running Instance of 'InjectableGenerator'

### ISSUE THREAD

**Issue by narcodico** [Milad-Akarie/injectable#71]
Hi @Milad-Akarie 👋

I keep getting this error, any clue why that might happen ? using latest versions.
```
Error running Instance of 'InjectableGenerator'
dynamic is not a class element
Cause: dynamic
```

Here's a sample [repo](https://github.com/RollyPeres/todos) showcasing the issue. If I don't specify any `sources` in `build.yaml` build runner finishes successfully but without iconfig generated, but if I try to specify in sources the path to locator file I get the error I mentioned above.

**Comment by Milad-Akarie** [comment]
Hey, @RollyPeres! This error means that the generator failed to resolve a dependency because it's not type hinted.
The attached module looks fine although multi environments aren't supported by injectable.
Can you please should me your build.yaml? do you have auto_register turned on?

**Comment by RollyPeres** [comment]
It's available on the repo @Milad-Akarie . There you go: https://github.com/RollyPeres/todos/blob/master/build.yaml
I didn't manually turn it on.

**Comment by Milad-Akarie** [comment]
hmm the build.yaml doesn't have anything that might infect injectable. 
Are you trying to register any other classes other than the ones in the module?

**Comment by RollyPeres** [comment]
@Milad-Akarie no, what you see in that repo is all I'm doing. You can run it locally to have a better grasp maybe.

> If I don't specify any `sources` in `build.yaml` build runner finishes successfully but without iconfig generated, but if I try to specify in sources the path to locator file I get the error I mentioned above.

This is the behavior you could try to reproduce. Since it's not a just a standard folder structure for a flutter app, might have to do with needing to explicitly set something in the `build.yaml` maybe.

**Comment by Milad-Akarie** [comment]
I just cloned your repo and added the following dev_dependencies to 
`todos/packages/todos/pubspec.yaml`
```
 build_runner:
 injectable_generator: 0.4.0
```
then run build_runner in this specific path
`todos/packages/todos`
and everything worked as expected.

**Comment by RollyPeres** [comment]
Thanks @Milad-Akarie , that would work indeed. What I'm actually after is being able to run the build runner from the `/todos` root folder since I will be having code gen in multiple packages within `packages/`. Hope that makes sense.

**Comment by Milad-Akarie** [comment]
I see.... and how do you add sources?

**Comment by RollyPeres** [comment]
@Milad-Akarie I have updated the repo with sources in `build.yaml`.
I've also added `freezed` to the repo for cross-reference.
Now when firing build_runner from the root `todos` folder we can notice that `.freezed.dart` class is being correctly generated, while the `.iconfig.dart` is not, and the error I mentioned appears.

Hope this helps 👍

**Comment by pro100svitlo** [comment]
in my case I get this error:
```dart
[SEVERE] injectable_generator:injectable_builder on lib/mapper/some_mapper.dart:
Error running Instance of 'InjectableGenerator'
RangeError (index): Invalid value: Only valid value is 0: 1
```

what does it mean?

**Comment by pro100svitlo** [comment]
solution described [here](https://github.com/Milad-Akarie/injectable/issues/74#issuecomment-636456289) didn't helped me

**Comment by pro100svitlo** [comment]
Hm, I solved the problem, but found an interesting details:
here  is my mapper:
```dart
@LazySingleton(as: Mapper)
class TaleEntityToTaleMapper extends Mapper<TaleEntity, Future<Tale>> {
}
```

The problem was cos of  `Future<Tale>`. As soon as  I removed it - it worked. 
@Milad-Akarie do you have any idea of these limitations?  🙏

**Comment by rackberg** [comment]
> 
> 
> Hm, I solved the problem, but found an interesting details:
> here is my mapper:
> 
> ```dart
> @LazySingleton(as: Mapper)
> class TaleEntityToTaleMapper extends Mapper<TaleEntity, Future<Tale>> {
> }
> ```
> 
> The problem was cos of `Future<Tale>`. As soon as I removed it - it worked.
> @Milad-Akarie do you have any idea of these limitations? 🙏

Hi @pro100svitlo,

I have the same problem that my build fails with the error you mentioned.
What are the limitations you found out?

Thank you in advance!
