### ISSUE TITLE
Undefined name 'Bind'

### ISSUE THREAD

**Issue by Liliana99** [Milad-Akarie/injectable#72]
Hi, thanks for wonderful job.
I have been faced with this issue :
@Bind.toType(ServiceImpl)  'Undefined name "Bind"' ?????

**Why I have this error?**

this is currently version of injectable that I have on my flutter project:
injectable: ^0.4.0
get_it: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator: ^0.4.0

**Comment by Milad-Akarie** [comment]
Hey @Liliana99 The Bind annotation has been deprecated for a while now. If you want to bind an abstract class to an Implementation use the 'as' property inside of injectable or it's subs


```dart
abstract class Service{}

// or Singleton(as: Service)
@Injectable(as: Service)
class ServiceImpl implements Service{}

```

**Comment by Liliana99** [comment]
Thanks,
