### ISSUE TITLE
Order for `preResolve`

### ISSUE THREAD

**Issue by pro100svitlo** [Milad-Akarie/injectable#74]
How can I order for `preResolve`d params?

Right now I have few parameters that marked with this annotation, but the generated `injectable` file has a wrong order. As a result - my app didn't launching correctly.

I am using `injectable_generator: 0.3.5`

Thanks!

**Comment by pro100svitlo** [comment]
Hm, I found that it was some bug with `injectable_generator: 0.3.5`.
So this one might be closed probably...

**Comment by pepusz** [comment]
Same here. 

We have an auth service that's using a local store service and inside the locator.registerSingleton the order is not correct, so the App crashes when the auth service would like to use the local store

**Comment by Milad-Akarie** [comment]
@pro100svitlo @pro100svitlo sorry for the delay guys I was on Eid vacation. Can you provide some examples of what exactly you're trying to do?

**Comment by pro100svitlo** [comment]
> Can you provide some examples of what exactly you're trying to do?

Sure 😉 
Here I have a module:
```dart
@registerModule
abstract class StorageModule {
  @preResolve
  @singleton
  @Named("cacheDirPath")
  Future<StringSingleLine> get cacheDirPath async {
    Directory appDocDir = await getApplicationDocumentsDirectory();
    return StringSingleLine(appDocDir.path);
  }

  @preResolve
  @singleton
  Future<HiveInterface> get hive async {
    final StringSingleLine cacheDirPath = getIt("cacheDirPath");
    Hive.init(cacheDirPath.getOrCrash());
    Hive.registerAdapter(TaleEntityAdapter());
    Hive.registerAdapter(CampaignEntityAdapter());
    Hive.registerAdapter(CampaignExtraVariantEntityAdapter());
    return Hive;
  }

  @preResolve
  @singleton
  Future<Box<TaleEntity>> get taleEntityBox => getIt<HiveInterface>().openBox<TaleEntity>("tales");

  @preResolve
  @singleton
  Future<Box<CampaignEntity>> get campaignEntityBox =>
      getIt<HiveInterface>().openBox<CampaignEntity>("campaigns");

  @preResolve
  @singleton
  @Named("settings")
  Future<Box> get settingsBox => getIt<HiveInterface>().openBox("settings");

  @preResolve
  @singleton
  @Named("taleUtilsStorage")
  Future<Box> get taleUtilsBox => getIt<HiveInterface>().openBox("taleUtilsStorage");

  @preResolve
  @singleton
  @Named("persistentState")
  Future<Box> get persistentStateBox => getIt<HiveInterface>().openBox("persistentState");
}
```

and here is the result of the generation:
```dart
  //Eager singletons must be registered in the right order
  final box = await storageModule.campaignEntityBox;
  g.registerSingleton<Box<CampaignEntity>>(box);
  final box1 = await storageModule.taleEntityBox;
  g.registerSingleton<Box<TaleEntity>>(box1);
  final box2 = await storageModule.taleUtilsBox;
  g.registerSingleton<Box<dynamic>>(box2, instanceName: 'taleUtilsStorage');
  final box3 = await storageModule.persistentStateBox;
  g.registerSingleton<Box<dynamic>>(box3, instanceName: 'persistentState');
  final box4 = await storageModule.settingsBox;
  g.registerSingleton<Box<dynamic>>(box4, instanceName: 'settings');
  final hiveInterface = await storageModule.hive;
  g.registerSingleton<HiveInterface>(hiveInterface);
  final stringSingleLine = await storageModule.cacheDirPath;
  g.registerSingleton<StringSingleLine>(stringSingleLine,
      instanceName: 'cacheDirPath');
```

**Comment by Milad-Akarie** [comment]
@pro100svitlo I'm guessing injectable is confused because you're resolving some deps manually, so it doesn't know about it. 
Please try the following:
first upgrade to
```
 injectable: 0.4.0
 injectable_generator: 0.4.0

```
then rewrite your code so this
 ```
@preResolve
  @singleton
  Future<Box<TaleEntity>> get taleEntityBox => 
 getIt<HiveInterface>().openBox<TaleEntity>("tales");
```
will look like this
@preResolve
  @singleton
  Future<Box<TaleEntity>> taleEntityBox(HiveInterface hive) => hive.openBox<TaleEntity("tales");
```
if use a function instead of a getter injectable will try to inject any dependency you you define in your func parameters. 
**Note** don't use getIt<T>() inside of your module
also pre-resolving alot of deps can slow your startup time so be careful of that.

**Comment by pro100svitlo** [comment]
> also pre-resolving alot of deps can slow your startup time so be careful of that. 

I am keeping in mind this one, thanks 👍 
Right now its fine.

I was trying to use `injectable_generator 0.4.0`, but I have another issue, described [here](https://github.com/Milad-Akarie/injectable/issues/71#issuecomment-632581529)

**Comment by Milad-Akarie** [comment]
could you try this?
`@InjectableInit(generateForDir: [''])`

**Comment by pro100svitlo** [comment]
sure. I will try it tomorrow ;-)

**Comment by pro100svitlo** [comment]
So, I fixed  issue with  order.  thanks.
But this  one  still didn't  helped me:
```dart
@InjectableInit(generateForDir: [''])
```

**Comment by zizo95** [comment]
> if you use a function instead of a getter injectable will try to inject any dependency you you define in your func parameters.
> so now injectable nows that TaleEntity depends on HiveInterface and it will register that first.

Hi @Milad-Akarie , This was a very helpful tip, maybe it should be in the docs to help others.

Thank you very much for your efforts.
