### ISSUE TITLE
@lazySingleton doesn't play well with @Injectable(as: T), worked with @RegisterAs(T)

### ISSUE THREAD

**Issue by wayne-werner** [Milad-Akarie/injectable#75]
Hi!
I have an abstract class, `IAuthFacade`, an implementation class `FirebaseAuthFacade `and an injectable bloc class `SignInFormBloc `whose constructor has a single parameter of an `IAuthFacade ` implementation.  This all worked with `@RegisterAs(T) ` but no longer works with `@Injectable(as: T)` when combined with `@lazySingleton`.
```
@lazySingleton
@RegisterAs(IAuthFacade)
class FirebaseAuthFacade...

```
used to generate:
```
  g.registerLazySingleton<IAuthFacade>(
      () => FirebaseAuthFacade(g<FirebaseAuth>(), g<GoogleSignIn>()));
  g.registerFactory<SignInFormBloc>(() => SignInFormBloc(g<IAuthFacade>()));

```
I can do:
```
@Injectable(as: IAuthFacade)
class FirebaseAuthFacade...

```
and get:
```
  g.registerFactory<IAuthFacade>(
      () => FirebaseAuthFacade(g<FirebaseAuth>(), g<GoogleSignIn>()));
  g.registerFactory<SignInFormBloc>(() => SignInFormBloc(g<IAuthFacade>()));

```
However adding the @lazySingleton back back in:
```
@lazySingleton
@Injectable(as: IAuthFacade)

```
Generates:
```
  g.registerFactory<SignInFormBloc>(() => SignInFormBloc(g<IAuthFacade>()));
  g.registerLazySingleton<FirebaseAuthFacade>(
      () => FirebaseAuthFacade(g<FirebaseAuth>(), g<GoogleSignIn>()));

```

Note that the registered singleton is on type FirebaseAuthFacade (the implementation class) and not the abstract IAuthFacade class!  This causes an exception at runtime (that the singleton is null). Not surprising as the singletons type is not correct and lookup therefore fails.

 The build runner also reports the following warning:
```
[WARNING] injectable_generator:injectable_config_builder on lib/injection.dart:
Injectable Generator ---------------------------------------------------

[SignInFormBloc] depends on [IAuthFacade] which is not injectable!

Did you forget to annotate the above classe(s) or their implementation with @injectable?

```
For now, I'm just not using `@lazySingleton` as I'm using the non-deprecated `@Injectable(as:..)` annotation, but as you can guess, I want lazy instantiation as, in the vast majority of cases, the user credentials are already stored locally and I don't need the FirebaseAuthFacade.

Thanks for your attention and a great package!

Wayne

**Comment by Milad-Akarie** [comment]
Hey @wayne-werner ya I should've designed that way but my aim was to use less annotations and make things more compact. 
Singleton and LazySingleton are actually subs of Injectable so they're meant to be used on their own.
so in your case that would be
`@LazySingleton(as: IAuthFacade)`

**Comment by wayne-werner** [comment]
Thanks for your quick attention!
I guess I'll have to read the docs more deeply... I find it a bit confusing that there are annotations that differ in name only by the initial capital and what the differences are.  Anyhow, `@LazySingleton(as:..)` was just what the doctor ordered.

Reading through the generated code has deepened my understanding of GetIt.  Thanks!
