### ISSUE TITLE
Injectable third party libraries with factory constructors

### ISSUE THREAD

**Issue by DFreds** [Milad-Akarie/injectable#8]
Dio is an abstract class with a factory for creation as shown.

```dart
abstract class Dio {
  factory Dio([BaseOptions options]) => createDio(options);
  // etc..
}
```

You can just normally create a new Dio instance by doing `Dio dio = Dio();`

If I try to register a third party module utilizing a `@registerModule`, it complains that the Dio class is abstract and doesn't use the factory. Is there anyway to utilize the injectable generator to automatically create a Dio instance or do I need to register it manually in my configure method?

I did it manually here: https://github.com/DFreds/mobx_injectable

**Comment by ResoDev** [comment]
While addressing this, could you please also look at working with classes such as `FirebaseAuth`?
It defines a static instance field so getting its instance is done like this:
```dart
FirebaseAuth.instance;
```

**Comment by cfregin** [comment]
Would be nice, if you could do something like this:
```
@injectable
@RestApi(baseUrl: 'https://someapi.com')
abstract class RestClient {
  @factoryMethod
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;
}

```

I was able to inject dio, retrofit and all with version 0.1.0..

**Comment by Milad-Akarie** [comment]
Hey @DFreds, you can now provide custom initializers in @registerModul like follows
`Dio get dio => Dio(...); // construct it the way you want`
Check out v0.2.2

**Comment by Milad-Akarie** [comment]
@cfregin 
You can now annotate abstract factory methods in v0.2.2 but how do you handle the base url?

**Comment by cfregin** [comment]
> @cfregin
> You can now annotate abstract factory methods in v0.2.2 but how do you handle the base url?

I hope, I can do that with `@registerModule`
and an environment affine Config. I will write an example.

**Comment by cfregin** [comment]
Ok. Your new version looks better now! I am playing around in a demo [injectable_demo.git](https://github.com/spielgestalt/injectable_demo.git). Normally I use FlavorConfig like described [here](https://medium.com/flutter-community/flutter-ready-to-go-e59873f9d7de). 
Ok.. It works:) 

- the example in injector.dart has a problem, importing PrettyDioLogger. (commented out)
- I defined `const development = 'development';` in injector.dart. Using this as annotation in my implementation files does not generate the _register*Dependencies. `@RegisterAs(ConfigDatasource, env: staging)` works.
- I am using [lint](https://pub.dev/packages/lint). Referencing Dio imports as `import 'package:dio/src/dio.dart';`. That will cause a implementation_imports warning. I usually comment my generated files with something like `// ignore_for_file: implementation_imports` or exclude the files in my `analysis_options.yaml`. But that's only a minor suggestion.

Neither the less: This package is becoming awesome!:) Thanks for your work!

**Comment by DFreds** [comment]
Amazing work! Thank you!

**Comment by Milad-Akarie** [comment]
Hey @cfregin, I gotta say your code is pretty neat. 
The generator recognizes an Environment const not a plain string so instead of 
const production = 'production';
declare it like this
const production = const Environment('production');
and if you need the string value you call name production.name;

regarding the custom initializer not importing it's dependencies PrettyDioLogger in your case that's a limitation and it's been mentioned in the docs.
as a work around you could register PrettyDioLogger as a dependency at least for now. 

usually what I would do is have an ApiClient extends DioForNative then hook up my baseUrl and all my interceptors inside of the client.
```dart
@lazySingleton
class ApiClient extends DioForNative{
   ApiClient() {
     options.baseUrl = 'base url';
     interceptors.add(interceptor);
     ...
   }
}
 ```
