### ISSUE TITLE
3rd party imports come from the "src" directory

### ISSUE THREAD

**Issue by ResoDev** [Milad-Akarie/injectable#81]
Hello! There has been the same issue reported a while ago (#12) and now the same error is back.
Given a module
```dart
import 'package:clock/clock.dart';
import 'package:injectable/injectable.dart';

@module
abstract class SharedInjectionModule {
  @prod
  Clock get clockProd => const Clock();
  @dev
  Clock get clockDev => const Clock();
}
```

The generated code imports `import 'package:clock/src/clock.dart';` which produces analyzer messages.

**Comment by Milad-Akarie** [comment]
@ResoDev  Fixed in injectable: 1.0.0 check it out
