### ISSUE TITLE
'injectable' or 'injectable_annotations'

### ISSUE THREAD

**Issue by olumidayy** [Milad-Akarie/injectable#87]
```
import 'package:injectable/injectable_annotations.dart';

abstract class Service {}

@RegisterAs(Service, env: 'dev')
@injectable
class ServiceImpl1 extends Service {}

@RegisterAs(Service, env: 'prod')
@injectable
class ServiceImpl2 implements Service {

}

@injectable
class MyRepository {
  MyRepository(@Named.from(ServiceImpl1) Service service);
}
```

The above code is from the [readme](https://pub.dev/packages/injectable#-example-tab-) for this plugin on pub.dev . The first line reads:
`import 'package:injectable/injectable_annotations.dart';`

this kept returning errors for me until i changed it to:
`import 'package:injectable/injectable.dart';`

Is it that both are correct and it was a result of my version or a mistake was made in the readme?

**Comment by Milad-Akarie** [comment]
Hey @olumidayy  this's the correct one 
`import 'package:injectable/injectable.dart';`
it seems it's a mistake in example readme file

**Comment by olumidayy** [comment]
Okay great! It'd be nice if that is seen to.
