### ISSUE TITLE
Query: Is it possible to get the current environment

### ISSUE THREAD

**Issue by AAllport** [Milad-Akarie/injectable#89]
Within our application we have a class that holds various configuration values.
There is a different config for each environment.

I'm aware I can create subclasses with the correct value but is it at all possible to pass the current environment into a factory, as this would allow me to wrap it in some sort of switch to return the correct config?

If not, could I request that feature?

**Comment by Milad-Akarie** [comment]
Hey @AAllport could you elaborate with some code?

**Comment by AAllport** [comment]
Currently, we have our `configureDependencies` as follows:
```dart
@injectableInit
Future<void> configureDependencies() async {
  const env = String.fromEnvironment('env', defaultValue: Env.PRODUCTION);
  getIt.registerSingleton<String>(env, instanceName: 'env');
  await $initGetIt(getIt, environment: env);
}
```
This allows us to access the environment from other modules like so:
`final env = getIt<String>(instanceName: 'env');`
Or like this:
```dart
@injectable
class FooService {
    final String env;
    FooService(@Named('env') this.env)
}
```

However, when injecting the environment like that, and trying to access it via `@Named` a warning is thrown during code-gen, since Injectable is not aware of the named injection.

Since `$initGetIt` accepts an `environment` param, it would be nice to have an official way of accessing it
Whether this is via the `@Named` annotation, or via a new annotation for the environment is neither here nor there personally,
However it feels like a seemingly common pattern to see within an application?

**Comment by Milad-Akarie** [comment]
@AAllport you need to register it using a module so injectable can know about it. 
```dart
@module
abstract class RegisterModule{
@named
 String get env => "env";
}
```

**Comment by AAllport** [comment]
The issue with that is you lose the ability to annotate with `@Environment("dev")` unless you both register it as a module and pass it into the `$initGetIt` function.

Having to pass it as both a module and a parameter feels like it's violating DRY

**Comment by Milad-Akarie** [comment]
@AAllport Do you have any suggestions? I thought about always injecting an env key internally with a special name then maybe add an extension to get_it so we can access the current env with something like `getIt.environment`
How does that sound?

**Comment by AAllport** [comment]
Sounds great!
I would suggest having a way away to inject the env via a classes constructor also, that could be via an `@Named` annotation.
This would allow the current environment to be used inside of an initialiser list, which I believe would be handy.

**Comment by fernando-s97** [comment]
Any updates on that?

**Comment by Milad-Akarie** [comment]
@fernando-s97  I totally forgot to close this issue, try this
`getIt<Set<String>>(instanceName: kEnvironmentsName);`
or inject them in a constructor 
`SomeConstructor(@Named(kEnvironmentsName) Set<String> envs);`
