### ISSUE TITLE
How do I dynamically change the a parameter in a lazySingleton class?

### ISSUE THREAD

**Issue by ganeshrvel** [Milad-Akarie/injectable#90]
### How do I dynamically change the a parameter in a lazySingleton class?

I am looking for a way to dynamically change the baseUrl in lazySingleton api class. How do I get that working?

My dio module
```dart
@module
abstract class DioDi {
  @lazySingleton
  Dio get dio => Dio();
}
```

ApiClient class
```dart
@lazySingleton
class ApiClient {
  final Dio dio;

  ApiClient(this.dio) {
    dio.options.baseUrl = env.apiBaseUrl;
    dio.options.connectTimeout = const Duration(seconds: 30).inMilliseconds;
    dio.options.receiveTimeout = const Duration(seconds: 30).inMilliseconds;
  }

  Future<Response> get(String path) async {
    /// ...
  }
}

```

This code throws `[ApiClient] depends on [String] which is not injectable!` error
```dart
ApiClient(this.dio, {String baseUrl}) {
  dio.options.baseUrl = apiBaseUrl ?? env.apiBaseUrl;
}
```

**Comment by Milad-Akarie** [comment]
Hey @ganeshrvel Get_it doesn't support singleton factory params which makes sense because if you're to have more that one instance then I guess  it's not a singleton anymore.
What you could do in your case is provide a named string instance that you can inject into your ApiClient 

```dart
@module
abstract class DioDi {
  @lazySingleton
  Dio get dio => Dio();

  @Named("baseUrl")
  String apiBaseUrl get => "myBaseUrl"; // or get it from your env

}
```
Then annotate your injected String with the @Named() and give it the same name of your Injectable String
```dart
ApiClient(this.dio, {@Named("baseUrl") String baseUrl}) {
  dio.options.baseUrl = apiBaseUrl;
}
```
Hope this helps!

**Comment by ganeshrvel** [comment]
@Milad-Akarie thanks. there is just one catch, I get the baseUrl from another api call, which is kind of dynamic. How do I dynamically pass it to the module?
```dart
abstract class DioDi {
  @lazySingleton
  Dio get dio => Dio();

  @Named("baseUrl")
  String apiBaseUrl get => "myBaseUrl"; // or get it from your env

}
```

**Comment by Milad-Akarie** [comment]
hmmm that's a tough one. I guess you could do something like this
```dart
 @Named("baseUrl")
 String apiBaseUrl(BaseUrlProvider provider) => provider.baseUrl;
```

**Comment by ganeshrvel** [comment]
Thanks!
