### ISSUE TITLE
Question: Register third party modules with parameters from main project

### ISSUE THREAD

**Issue by DFelten** [Milad-Akarie/injectable#99]
Thanks for this package, It works great! I've got a question and maybe someone here could help me with this approach. 

We've got a service and a repository, the repository is stored within a custom package from our team. The repository has an abstract class for the service as a parameter. 

It's working when we define the service and the repository within the module file like this:

```dart
@module
abstract class Modules {
  @LazySingleton(as: CustomPostService)
  PostService get postService => PostService(client: client);

  @lazySingleton
  CustomPostRepository get customPostRepository => CustomPostRepository(postService: postService);
}
```

The problem here is, that we have to define also the service here, which is a part of our main project. When using only the service, we could use an annotation to mark it as injectable.

```dart
@LazySingleton(as: CustomPostService)
class PostService extends CustomPostService {
  PostService({@required Client client})
      : super(
          client: client,
          accessToken: accessToken,
          baseUrl: baseUrl,
        );
}
```

But since we need the service as a parameter for the repository, this is not enough. We need no define the service also in the module file. 

Is there a possibility to define only the repository in the modules file?

**Comment by Holofox** [comment]
Considering that the service will already be registered in the container anyway, you can write like this:
```dart
@module
abstract class Modules {
  @lazySingleton
  CustomPostRepository customPostRepository({
    @required CustomPostService postService,
  }) => CustomPostRepository(postService: postService);
}
```

```dart
@LazySingleton(as: CustomPostService)
class PostService extends CustomPostService {
  PostService({@required Client client})
    : super(
    client: client,
    accessToken: accessToken,
    baseUrl: baseUrl,
  );
}
```
Perhaps I did not quite understand your question, but since you registered ```PostService``` as a ```CustomPostService```, henceforth you should only use ```CustomPostService```, since it is he who will be registered in your container with dependencies.

**Comment by Holofox** [comment]
Are you sure you need to use a module? You can register dependencies separately:
```dart
@LazySingleton(as: CustomPostService)
class PostService extends CustomPostService {
  PostService({@required Client client})
    : super(
    client: client,
    accessToken: accessToken,
    baseUrl: baseUrl,
  );
}
```

Register as an abstract class:
```dart
@LazySingleton(as: CustomPostRepository)
class PostRepository extends CustomPostRepository {
  const PostRepository({
    @required CustomPostService postService,
  }): super(postService: postService);
}
```

Register as interface:
```dart
@LazySingleton(as: IPostRepository)
class PostRepository implements IPostRepository {
  final CustomPostService _postService;
  
  const PostRepository(this._postService);
}
```

Register as a class:
```dart
@lazySingleton
class PostRepository {
  final CustomPostService _postService;
  
  const PostRepository(this._postService);
}
```

**Comment by DFelten** [comment]
Thanks for the quick response :) It works the way you described it in the first answer:

```dart
@module
abstract class Modules {
  @lazySingleton
  CustomPostRepository customPostRepository({
    @required CustomPostService postService,
  }) => CustomPostRepository(postService: postService);
}
```

So it's not necessary to define an additional PostRepository class.
